### ISSUE TITLE
"=" rendering weird in Ubuntu 16.04

### ISSUE THREAD

**Issue by szsdk** [be5invis/Sarasa-Gothic#10]
I have tried it in gnome-terminal and terminator, they all look like as below
![image](https://user-images.githubusercontent.com/6657200/34367600-9cf9f472-eae7-11e7-92cf-a9331b73d37b.png)
while everything works fine in latest archlinux gnome-terminal.

So I am wondering whether it is a system bug.

**Comment by dramforever** [comment]
I'm also affected by this. Fedora 27 almost fresh install, gnome-terminal

**Comment by be5invis** [comment]
Sarasa Term would be introduced in v0.5, just like Iosevka, which disables ligation.
Closed.
