### ISSUE TITLE
考虑在正式发布版本中加入slab-serif版本么

### ISSUE THREAD

**Issue by cloud-yu** [be5invis/Sarasa-Gothic#100]
请问后续release版本中会加入slab-serif版本么，感觉瘦长字体的英文还是slab-serif最惊艳。

**Comment by CyanoHao** [comment]
我 fork 了一个 slab-serif 版本：https://github.com/CyanoHao/Sarasa-Alternatives/tree/master

**Comment by cloud-yu** [comment]
> 我 fork 了一个 slab-serif 版本：https://github.com/CyanoHao/Sarasa-Alternatives/tree/master

厉害了，感谢~
