### ISSUE TITLE
输入">="会自动转换显示成"≥"

### ISSUE THREAD

**Issue by ChenShiYi** [be5invis/Sarasa-Gothic#101]
在中文后输入>=或者<=，看上去会显示为≥或者≤符号，但是这个符号实际长度又是2个字符。
更换别的字体没有出现这个现象，请问这是这个字体的特殊功能么？能不能不要这个转换？

**Comment by copyliu** [comment]
see https://typeof.net/Iosevka/ `Ligation Sets` part for detail

**Comment by be5invis** [comment]
This is considered as by-design.
Please use Sarasa Term instead.
