### ISSUE TITLE
Can‘t find it in Android studio

### ISSUE THREAD

**Issue by LawrenceGK** [be5invis/Sarasa-Gothic#104]

**Comment by LawrenceGK** [comment]
I reinstall the fonts file. I'm sure it' ok in other software.

**Comment by LawrenceGK** [comment]
yeah I know java hate modern typography. I mean maybe they gave up to adapt it.

**Comment by be5invis** [comment]
I can not help you so much about Java appliations. Perhaps you can try to restart PC so some weird cache (?) can restore.

**Comment by be5invis** [comment]
Or you can try to uninstall the existing installation and install the TTF version, which _may_ have better compatibiltiy.

**Comment by LawrenceGK** [comment]
Doesn't work. Anyway thx. <(＿ ＿)>

**Comment by vajacn** [comment]
新版 Windows 10 中安装字体会默认安装到%USERPROFILE%\AppData\Local\Microsoft\Windows\Fonts目录，在 Java 里是找不到的。
如果要把字体安装到 C:\Windows\Fonts，就是在安装字体的时候右击字体文件，选择「为所有用户安装」。
