### ISSUE TITLE
微软商店里面这个是官方版本的吗？

### ISSUE THREAD

**Issue by WangZishi** [be5invis/Sarasa-Gothic#105]
![image](https://user-images.githubusercontent.com/8288105/61505101-41b39e80-aa10-11e9-920d-963beb935458.png)
今天在微软商店里面看到了更纱黑体，想知道是否是官方的行为

**Comment by be5invis** [comment]
No.

**Comment by be5invis** [comment]
Sarasa is OSS so people can distribute it to elsewhere.
There are also many packages for Linux.
Closed.

**Comment by WangZishi** [comment]
那这是否说明了微软商店现在可以支持第三方上传字体了呢？

https://github.com/be5invis/Iosevka/issues/271#issuecomment-389411562_

**Comment by be5invis** [comment]
Maybe. I have not checked out Store's state for a while (busy with other stuff).

**Comment by kejaxe** [comment]
> 那这是否说明了微软商店现在可以支持第三方上传字体了呢？
> 
> [be5invis/Iosevka#271 (comment)](https://github.com/be5invis/Iosevka/issues/271#issuecomment-389411562)_

Here is this publisher's post about publishing fonts in Microsoft Store.
https://www.taoyouh.cn/archives/1728
