### ISSUE TITLE
为什么等宽字体显示这么奇怪，我这个效果是正常的吗？

### ISSUE THREAD

**Issue by wonderbeyond** [be5invis/Sarasa-Gothic#107]
这是我在 gist 上贴的一段代码（正是我当前的 fonts.conf 配置）：
https://gist.github.com/wonderbeyond/ba6a4a141626836ad35f846e46f5e90f

字体渲染效果如下：
![image](https://user-images.githubusercontent.com/228361/62017494-6d414080-b1e9-11e9-876d-4becfed16fb0.png)

我感觉效果很奇怪，请问这是符合逾期的吗？

**Comment by hongzk** [comment]
正常的。两个英文字符的占位合起来应该是一个正方形。
加上中文可以发现，等宽字体里面，中文字符的宽度是英文字符的两倍。

**Comment by wonderbeyond** [comment]
@hongzk 多谢解答！

我发现特定字符连接在一起，展现的形状发现了变化（或结合），影响阅读。
请问这是正常的吗？

```xml
    <selectfont>
        <rejectfont>
            <!--
            <glob>/usr/share/fonts/opentype/noto/*</glob>
            -->
        </rejectfont>
    </selectfont>
```

![image](https://user-images.githubusercontent.com/228361/62024825-ddab8a00-b208-11e9-8dbe-21f4c208d187.png)

**Comment by be5invis** [comment]
That's called "ligation".
The Term variant (named "Sarasa Term _whatever_") will turn them off.

**Comment by wonderbeyond** [comment]
@be5invis 多谢！换成 “Sarasa Term J” 我搞定了。
