### ISSUE TITLE
请问为什么我的等距更纱黑体并不是等距

### ISSUE THREAD

**Issue by KagurasakaAkuryou** [be5invis/Sarasa-Gothic#108]
![image](https://user-images.githubusercontent.com/28646046/62064260-0a8a8c00-b25f-11e9-8285-1b068ff47a25.png)

**Comment by leokvw** [comment]
https://zh.wikipedia.org/wiki/%E7%AD%89%E5%AE%BD%E5%AD%97%E4%BD%93

**Comment by be5invis** [comment]
Notepad++ again.
Notepad++'s text size **doesn't mean** how many pixels you are using, so you may need to adjust it to make the pixels become an even number.

**Comment by CyanoHao** [comment]
应该是没有勾选 “启用全局字号”，导致实际的字号不是 12pt。
![image](https://user-images.githubusercontent.com/14287996/62096821-87e1eb00-b2b7-11e9-85e5-3f52f3740539.png)

Notepad++ 的字号单位是 pt，字号 _x_ pt 和 _y_ px 的换算关系是
![y=\frac{x}{72}\times\mathrm{dpi}](http://www.sciweavers.org/tex2img.php?eq=y%20%3D%20%5Cfrac%7Bx%7D%7B72%7D%5Ctimes%5Cmathrm%7Bdpi%7D&bc=White&fc=Black&im=png&fs=12&ff=modern&edit=0)
在默认的 100% 缩放下（dpi = 96），3pt 的倍数对应的像素数都是偶数，能对齐的。其他字号就需要试一试了。

**Comment by KagurasakaAkuryou** [comment]
![image](https://user-images.githubusercontent.com/28646046/62116975-b2e73180-b2ed-11e9-8b64-053ae02a502d.png)
![image](https://user-images.githubusercontent.com/28646046/62117135-f6da3680-b2ed-11e9-8e97-014790d06878.png)
![image](https://user-images.githubusercontent.com/28646046/62117175-06597f80-b2ee-11e9-8640-463f465fc0be.png)
以上都是推荐分辨率 100%缩放

**Comment by be5invis** [comment]
This is the thing: GDI only support glyph widths bing integer pixels (while DWRITE/FreeType support fractional advance widths) so if the PPEM is not an even integer number (yes PPEM can be a faction too) then you won't have perfect alignment. Old Microsoft fonts like SimHei have `hdmx` tables to deal with such rounding errors, which are some data **very hard to maintain and automate**.
AFAIK there is some method to force NotePad++ to use DWRITE to deal with text, which should enable ligatures and fractional advance widths: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2287

**Comment by be5invis** [comment]
@CyanoHao GDI's "pt" seems related with (font's built-in) line height rather than a fixed DPI

**Comment by CyanoHao** [comment]
TTF 的黑魔法真多啊…… 😂

我试着给 Sarasa 写了 hdmx 表，从 11 到 48 的所有奇数 ppem，半角字符的宽度向上取整，全角字符宽度为半角字符的 2 倍，现在可以在 Notepad++ 里面对齐了。
![hdmx-sarasa](https://user-images.githubusercontent.com/14287996/62287931-ce893e00-b48d-11e9-9682-8e1b67824e93.png)

下载链接：https://pan.baidu.com/s/1xl5p2-NtNW6vmRCuiwXklQ

字体名前面加了 “hdmx: ”，可以直接安装，不会和现有的 Sarasa 字体冲突。
![fontname](https://user-images.githubusercontent.com/14287996/62288069-2758d680-b48e-11e9-9cf3-ab14c13a7ee7.png)

这是写 hdmx 表的 Python 程序：[build-hdmx-for-sarasa.zip](https://github.com/be5invis/Sarasa-Gothic/files/3456313/build-hdmx-for-sarasa.zip)（依赖 [fonttools](https://github.com/fonttools/fonttools)，很慢，处理一个 ttf 文件要 1 分多钟。）

**Comment by fireattack** [comment]
> Notepad++ again.
> Notepad++'s text size **doesn't mean** how many pixels you are using, so you may need to adjust it to make the pixels become an even number.

@be5invis: this bug is not notepad++ only though, I can reproduce it in notepad.exe with font size = 11.

**Comment by asmwarrior** [comment]
> > Notepad++ again.
> > Notepad++'s text size **doesn't mean** how many pixels you are using, so you may need to adjust it to make the pixels become an even number.
> 
> @be5invis: this bug is not notepad++ only though, I can reproduce it in notepad.exe with font size = 11.

Hi, I also see the same issue.

I'm currently see this issue in Code::Blocks IDE(in-fact, it happens in all wxWidgets based application) and notepad.exe(shipped by Windows), when the font size = 11, 
Two English characters' width is a bit wider than a single Chinese character. This won't happens in font size = 10 or 12.

I'm using the 等距更纱黑体 SC font which is the mono-space Simplified Chinese version.

Anyone know how to fix this issue?

**Comment by asmwarrior** [comment]
I just download the latest release from this site:

[CJK characters alignment issue in some applications · Issue #1 · jonz94/Sarasa-Gothic-Nerd-Fonts](https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/issues/1)

And it did solve my issue both in Code::Blocks and notepad.exe.

Thanks.
