### ISSUE TITLE
字母缩写意义

### ISSUE THREAD

**Issue by CharleyMorgan** [be5invis/Sarasa-Gothic#109]
我想问下等距更纱黑体 T SC的T代表什么意思

**Comment by CharleyMorgan** [comment]
文档上面也没有说明

**Comment by yoonhakcher** [comment]
[您好，有的](https://github.com/be5invis/Sarasa-Gothic#what-are-the-names)

**Comment by kinfables** [comment]
**包含样式**：
Sarasa Gothic / 更纱黑体：基于Noto Sans，全宽引号
Sarasa UI / 更纱黑体UI：基于Noto Sans，窄引号
Sarasa Mono T / 等距更纱黑体 T：基于losevka，有连字，全宽破折号
Sarasa Mono / 等距更纱黑体：基于losevka，有连字，半宽破折号
Sarasa Term：基于losevka，无连字，半宽破折号
**包含汉字字形**:
SC：简体中文
TC：台湾繁体中文
J：日文
HC：香港繁体中文

**Comment by gMan1990** [comment]
@kinfables `cl`和`k`呢

**Comment by kinfables** [comment]
@gMan1990 

根据 **[README.md](https://github.com/be5invis/Sarasa-Gothic/blob/master/README.md)** 中已给出的具体说明：
>  `CL`: Classical orthography 
>  `SC`, `TC`, `J`, `K`, `HC`: Regional orthography, following [Source Han Sans](https://github.com/adobe-fonts/source-han-sans) notations.

可知`CL`指旧字形，`K`指韩文。
