### ISSUE TITLE
关于全角引号的疑问

### ISSUE THREAD

**Issue by Heptazhou** [be5invis/Sarasa-Gothic#111]
https://github.com/be5invis/Sarasa-Gothic/issues/60#issuecomment-441252150
如您所说，等宽变体的弯引号都设计为半宽，但还是冒昧地问一下，可否考虑在 MonoT 字型中采用全宽的中文单、双引号？（` “” ‘’ `）

**Comment by be5invis** [comment]
No.
Closed as by design.

**Comment by be5invis** [comment]
Actually, I am planning to remove the `MonoT` version...

**Comment by Heptazhou** [comment]
感谢回复。
*****
> 
> 
> Actually, I am planning to remove the `MonoT` version...

好可惜…我个人还很喜欢`MonoT`的。
