### ISSUE TITLE
Add donate link

### ISSUE THREAD

**Issue by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [be5invis/Sarasa-Gothic#118]
Use your fonts for months, very nice look.
Thanks for your greate work.
but how can i pay a small donate to you ?
why not add donate link in this repository readme.md?
that let us can pay for use your good product.

**Comment by cwchien** [comment]
The author has a Patreon account, which I donate monthly with.
[Belleve Invis](https://www.patreon.com/user?u=5787198)

If you want a one-time donate, I'm afraid that you have to paid once then cancel the recurring monthly billing.
[Can I make a one-time payment?](https://support.patreon.com/hc/en-us/articles/204606215-Can-I-make-a-one-time-payment-)
