### ISSUE TITLE
what‘s the difference between Term, Mono, UI, and Gothic?

### ISSUE THREAD

**Issue by Summer-Arrival** [be5invis/Sarasa-Gothic#12]
Can't find the answer on web, and I want to use your font both in my windows 10 and VS Code,  could you give me a suggestion? THX

**Comment by chadluo** [comment]
There seems to be some info in [config.json](https://github.com/be5invis/Sarasa-Gothic/blob/master/config.json). Term and Mono are using [Iosevka](https://github.com/be5invis/Iosevka) as the Latin part, while UI and Gothic are using Noto-sans.

Iosevka itself is monospaced, and Term has some specific config about ligations and spacing. You might find some info from [Iosevka Readme](https://github.com/be5invis/Iosevka#build-your-own-style).

UI and Gothic differs in the `PWID` feature which I am not familiar with.

**Comment by be5invis** [comment]
- `Term`: Monospace, no ligature
- `Mono`: Monospace, have ligature
- `UI`: Proportional, narrow quote marks
- ` Gothic`: Proportional, full-width quote marks

**Comment by acgtyrant** [comment]
@be5invis Hi, is there any plan to support serif? Thank you.
