### ISSUE TITLE
found two words are not correct

### ISSUE THREAD

**Issue by hingbong** [be5invis/Sarasa-Gothic#120]
![image](https://user-images.githubusercontent.com/26398240/67252819-42dce780-f4a7-11e9-9567-821bbf4fac3a.png)
I am using sarasa-gothic-cl and found the "繼" and "名" are not correct

**Comment by ichiQhachi4** [comment]
This is indeed a bug or hinting error inside the character “繼”, however as for “名”, I suppose it is a design choice. The Classic Chinese doesn‘t have a strict design policy to follow.

**Comment by ichiQhachi4** [comment]
Addition to that, “等” and “管” has some minor hinting issue in certain size.
Take the default notepad as an example, 
![image](https://user-images.githubusercontent.com/31877509/68015935-53bf0180-fcce-11e9-84cb-cfbcca232888.png)
![image](https://user-images.githubusercontent.com/31877509/68015878-2b370780-fcce-11e9-97f0-270b49dc7fc4.png)
the horizontal stroke are supposed to be aligned.

**Comment by be5invis** [comment]
I have internal builds fixed all these failures.

**Comment by ichiQhachi4** [comment]
Any time table for release?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/68016263-6d6e3380-fc51-11e9-933b-6f294792a45b.png)
![image](https://user-images.githubusercontent.com/240091/68016277-75c66e80-fc51-11e9-96b3-582979338731.png)

(繼, 等, 管 at 14 and 16 ppem)

**Comment by ichiQhachi4** [comment]
That's really awesome!

**Comment by be5invis** [comment]
Closed as resolved.
Just wait a release or, if you have time, build from master.
