### ISSUE TITLE
Split font family into small zip .

### ISSUE THREAD

**Issue by netroby** [be5invis/Sarasa-Gothic#123]
Split font family into small zip .

Only want to download `Sarasa Mono T SC`

**Comment by CyanoHao** [comment]
Splitting font families does not help. (Archive size will be reduced by only ~20%, I guess.)

**Comment by CyanoHao** [comment]
Tip: TTC files can be also extracted from Arch Linux package, which is available on [archlinuxcn mirror](https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/any/) (`ttf-sarasa-gothic-<version>.pkg.tar.xz`).

**Comment by netroby** [comment]
I means it shoud split  `Sarasa Mono T SC`  family into  `Sarasa Mono T SC.tar.xz`

and we have these small package. do not need download a full big file.

**Comment by CyanoHao** [comment]
Many glyphs are shared among families.
Size of `sarasa-gothic-ttf.7z` is only slightly larger than `sarasa-monoT-sc.7z` (or `tar.xz`).

**Comment by netroby** [comment]
ok, ok. i know it .
