### ISSUE TITLE
ttc字体在注册表中注册的名字太长

### ISSUE THREAD

**Issue by lywind** [be5invis/Sarasa-Gothic#125]
ttc字体在注册表\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts中注册的名字很长，导致部分软件识别出现问题，例如Visual Studio 2015的安装程序就会因为这个问题导致无法打开

**Comment by lywind** [comment]
VS安装程序会报如下错误：
[3C74:19AC][2019-11-21T16:58:36]e000: MUX:  ERROR: “System.Windows.Media.FontFamily”的类型初始值设定项引发异常。
[3C74:19AC][2019-11-21T16:58:36]e000: MUX:  Stack:    在 System.Windows.Media.Typeface..ctor(FontFamily fontFamily, FontStyle style, FontWeight weight, FontStretch stretch)
   在 MS.Internal.Text.DynamicPropertyReader.GetTypeface(DependencyObject element)
   在 MS.Internal.Text.TextProperties.InitCommon(DependencyObject target)
   在 MS.Internal.Text.TextProperties..ctor(FrameworkElement target, Boolean isTypographyDefaultValue)
   在 System.Windows.Controls.TextBlock.GetLineProperties()
   在 System.Windows.Controls.TextBlock.EnsureTextBlockCache()
   在 System.Windows.Controls.TextBlock.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   在 System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Control.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.StackPanel.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   在 System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   在 System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Border.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Border.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   在 System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
   在 System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Controls.Border.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Window.MeasureOverrideHelper(Size constraint)
   在 System.Windows.Window.MeasureOverride(Size availableSize)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Interop.HwndSource.SetLayoutSize()
   在 System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   在 System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   在 System.Windows.Window.SetRootVisual()
   在 System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   在 System.Windows.Window.CreateSourceWindowImpl()
   在 System.Windows.Window.SafeCreateWindow()
   在 System.Windows.Window.ShowHelper(Object booleanBox)
   在 System.Windows.Window.Show()
   在 Microsoft.Devdiv.Bootstrapper.ManagedUx.RunUI(ViewModelCommonUi viewModel)
   在 Microsoft.Devdiv.Bootstrapper.ManagedUx.InternalRun()
   在 Microsoft.Devdiv.Bootstrapper.ManagedUx.Run()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by be5invis** [comment]
Install the TTF version instead.
Close as external.

**Comment by Rholais** [comment]
> Install the TTF version instead.
> Close as external.

How to select from TTF and TTC to use?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72493824-eacc2d80-37d6-11ea-87c2-cbbd71057afc.png)
Pick this in the download page.

**Comment by Rholais** [comment]
> ![image](https://user-images.githubusercontent.com/240091/72493824-eacc2d80-37d6-11ea-87c2-cbbd71057afc.png)
> Pick this in the download page.

Thank you!
Which one should I choose, TTC or TTF?

**Comment by Lemmingh** [comment]
@Rholais

I would recommend you to have a look at [Adobe's guide](https://github.com/adobe-fonts/source-han-serif/blob/release/README.md), more specifically, read the [official Source Han download guide](https://github.com/adobe-fonts/source-han-serif/raw/release/download-guide-source-han.pdf) first then the whole `README.md`.

**It's best to use TTC (for easy deployment, saving disk space, etc.), *unless* you face problems.**

---

The key difference between TTC and TTF is
a TTC file can contain **multiple** font resources, while a TTF file can contain only **one**.

Note that TTC and TTF were file formats of TrueType but now OpenType.

[OpenType](https://docs.microsoft.com/en-us/typography/opentype/) is a digital font technology which superseded TrueType. See these articles for details:

* [OpenType font file](https://docs.microsoft.com/en-us/typography/opentype/spec/otff) on Microsoft Docs
* [OpenType fonts features](https://www.adobe.com/products/type/opentype.html) on Adobe Type

---

The most common condition that **blocks** you from using TTC files is **the software you use doesn't support TTC** (in any aspect), for example, the problem discussed in this issue.

In this case, you have to pick proper TTF files.

---

A popular reason that you **prefer** TTF files is **you really only need a few fonts and do not need a comprehensive collection**, for example, you just want to install a font called “Sarasa Mono SC Regular”.

In this case, you'd better choose TTF files that meet your requirement exactly.
