### ISSUE TITLE
编译环境

### ISSUE THREAD

**Issue by transtone** [be5invis/Sarasa-Gothic#127]
请教一下作者的编译环境。

因为 windows terminal 只支持 regular 一种字重，这两天想在 windows 下自己编译这个字体，想用 semibold 的字重去渲染 regular 。

可好不容易装好了几个依赖的工具之后，编译到半路报错。
`python3`   `Node.js-10.x`, `otfcc`, `AFDKO`, `ttfautohint`, `windows vs2015工具包` 等 

于是想用 archlinux 来编译，同样安装了上述工具，结果同样卡在 `npm run build ttf` 的过程中。

错误忘记截图了。

因为没有找到可用的苹果系统，就暂时没测试 macos 环境了。

![image](https://user-images.githubusercontent.com/46688/70385849-1b48cc80-19cc-11ea-985a-bcce4a7a6adc.png)

**Comment by nobk** [comment]
一个不用编译的办法，安装的时候不安regular，或者进Fonts文件夹删掉它，就能默认显示更粗的字体了。
当然代价就是没有regular这个字重了。

**Comment by shellqiqi** [comment]
确实，我也遇到了一样的问题。请问你解决了吗？

**Comment by CyanoHao** [comment]
https://github.com/caryll/otfcc/pull/69 应该修复了这个问题。
c.c. @shellqiqi
