### ISSUE TITLE
TTC font cause matplotlib freezes

### ISSUE THREAD

**Issue by cloudhan** [be5invis/Sarasa-Gothic#13]
On Microsoft Windows [版本 10.0.16299.248] with `matplotlib 2.1.2` and `2.0.2`, there are some weird problems coupled with the ttc font (at least ver 0.5.1)

With `matplotlib 2.1.2`
``` python
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.show()  # this will cause a freeze
```

With `matplotlib 2.0.2`
``` python
import matplotlib.pyplot as plt  # this will cause a freeze
```

There is no WARN or ERROR throws and it just freezes the python session. Uninstalling all ttc fonts and switching back to ttf fonts solve these problems. These problems does not necessarily due to Sarasa-Gothic font build. I'm leaving this information here in case someone might encounter these problems. So feel free to close this issue.

There is also one more problem caused by ttc font:
With the deprecated Inziu CJK ttc font, it will cause the Visual Studio 2015 installer fail to start, about 1 year ago with some older Windows 10 build. I don't know if it still present in current Window 10 build.
Leaving this additional information here in case you want to investigate these issues (as a true insider of M$ ;)

**Comment by be5invis** [comment]
I think maybe you should open an issue on `matplotlib`. It may not able to correctly parse the TTC files (or not supporting TTCs with many subfonts).
