### ISSUE TITLE
Incorrect Glyphs of Classical Literature (CL) version 

### ISSUE THREAD

**Issue by NightFurySL2001** [be5invis/Sarasa-Gothic#131]
Characters below are incorrect when compared to other related glyphs of the same component:

併 | 值 | 偯 | 偺 | 偽 | 劆 | 即 | 吆 | 告 | 咚 | 暨 | 周 | 唷 | 啟 | 唬 | 嗡 | 嗦 | 嘀 | 嘟
嚎 | 姘 | 妍 | 姅 | 婊 | 嬤 | 巔 | 帟 | 廄 | 弒 | 拼 | 揍 | 教 | 材 | 杗 | 柺 | 榣 | 櫥 | 殺
氯 | 踩 | 躲 | 鄉 | 醣 | 銬 | 鑤 | 青 | 飲 | 顛 | 駢 | 鯛

These glyphs are reviewed from Big5 standard of first order Chinese characters and compared to Recommended Inherited Glyphs document on here: https://github.com/ichitenfont/inheritedglyphs.

![image](https://user-images.githubusercontent.com/33471049/72662150-a337e280-3a1e-11ea-8b1d-66697b14c634.png)

**Comment by be5invis** [comment]
CL simply used KR version of SHS to create that.
OTF overrides are welcome (though -- it may be hard to produce, especially Sarasa's script needs every weight).

**Comment by NightFurySL2001** [comment]
Is it possible to try [Genne Gothic](https://github.com/MoneMizuno/Genne-Gothic)?

**Comment by be5invis** [comment]
I suggest that you can detach all the "modified" glyphs out and create a subset OTF -- that will reduce the footprint and accelerate the building process.

**Comment by be5invis** [comment]
Also Sarasa is based on SHS 2+ (for the HC variant).

**Comment by edward-martyr** [comment]
@be5invis Could you clarify what you meant by "modified"? I believe Genne Gothic uses glyphs solely from SHS. Would it be possible to make Sarasa CL use a similar mapping scheme?

**Comment by NightFurySL2001** [comment]
I think @be5invis can directly use Genne Gothic as it use only glyphs from SHS. But the problem would be it is using 1.004 which has more classical literature version of glyphs. (or its only the HC variant that uses 2.0?) Genne Gothic do provide CMap with 1.004 in [here](https://github.com/MoneMizuno/Genne-Gothic/tree/master/Other/Other)

**Comment by be5invis** [comment]
@NightFurySL2001 Is it possible to only extract the characters that are _modified_ by Genne? So I can apply a “patch” to the CL variant.

**Comment by NightFurySL2001** [comment]
@be5invis i don't think Genne had modified any glyphs, just the CMap only, so I can't extract characters modified by Genne. I could try to do a CMap comparison with KR version if you need tho. (I don't have enough technical ability to differentiate and extract characters, sorry)

**Comment by be5invis** [comment]
@NightFurySL2001 Yeah, and you can create a subset font so I can use it.

**Comment by NightFurySL2001** [comment]
Ok, I'll try that then

**Comment by NightFurySL2001** [comment]
@be5invis Any specific range of subset that you want? The otf seem to be bigger in size after subsetting the following (from 14MB to 20MB):
{-U+2B1A
U+3001-33FF
U+A960-U+D7FB
U+FE10-U+1f521
All CID

**Comment by be5invis** [comment]
@be5invis Subset to only the characters you changed.

**Comment by be5invis** [comment]
@NightFurySL2001 Subset to only the characters you changed.

**Comment by NightFurySL2001** [comment]
@be5invis I'm not the author of that font, sorry

**Comment by NightFurySL2001** [comment]
@be5invis Although I'm not the author of the font of Genne Gothic, but I still tried to subset the font and leaving the CJK characters. Following ranges of characters are removed by importing the font to FontLab and sorting by unicode:
- U+007B-U+2B07 (1261 glyphs)
- U+A960-U+D7FB (11273 glyphs)
- All unused CID at end of font (21559 glyphs)
Please check if this is suitable. It still have a bit of inconsistency due to 65536 glyphs limit in OpenType fonts.
[GenneGothic-Reg_Nm.zip](https://github.com/be5invis/Sarasa-Gothic/files/4418968/GenneGothic-Reg_Nm.zip)
[GenneGothic-Bo-Hv.zip](https://github.com/be5invis/Sarasa-Gothic/files/4418974/GenneGothic-Bo-Hv.zip)
[GenneGothic-Li_ExLi.zip](https://github.com/be5invis/Sarasa-Gothic/files/4418994/GenneGothic-Li_ExLi.zip)
[GenneGothic-Medium.zip](https://github.com/be5invis/Sarasa-Gothic/files/4418997/GenneGothic-Medium.zip)

**Comment by CyanoHao** [comment]
@NightFurySL2001 need something like this one:
[classical-overlay-regular-1.004.otf.gz](https://github.com/be5invis/Sarasa-Gothic/files/4419146/classical-overlay-regular-1.004.otf.gz)

**Comment by NightFurySL2001** [comment]
@CyanoHao  can you do that? 🤣 I don't know what did Genne Gothic had changed since I'm *not* the author of font.

**Comment by NightFurySL2001** [comment]
@CyanoHao did that file pulled the characters that are changed? If yes I can try to use FontForge to pull out the same character set from the Genne Gothic set as I don't know what did Genne Gothic had changed and comparing it with either SC/TC/JP/KR version will take a long time to do.

**Comment by edward-martyr** [comment]
Would this one satisfy the needs: [genne-subset.zip](https://github.com/be5invis/Sarasa-Gothic/files/4848836/genne-subset.zip)

I subset all Genne Gothic Weights based on the modified glyphs list in [CMap替換表_Genne Gothic_1.004.ods](https://github.com/MoneMizuno/Genne-Gothic/blob/master/Other/Other/CMap%E6%9B%BF%E6%8F%9B%E8%A1%A8_Genne%20Gothic_1.004.ods). Here's the complete list:

```
U+2EBC,U+2F49,U+4E49,U+5173,U+524D,U+526A,U+52B2,U+540D,U+555F,U+55BB,U+5632,U+580B,U+590D,U+5D29,U+5DD3,U+5DD4,U+5EDF,U+5F38,U+5F52,U+5F84,U+6237,U+63C3,U+64F6,U+670B,U+670D,U+6715,U+671D,U+67A6,U+68DA,U+6CAA,U+6E05,U+6E54,U+6F6E,U+714E,U+7529,U+771E,U+771F,U+787C,U+7B99,U+7BAD,U+7C50,U+7C58,U+7C90,U+7E43,U+7FE6,U+822E,U+830E,U+83D4,U+8551,U+8DB4,U+8FBC,U+93AD,U+93AE,U+95E8,U+9752,U+985A,U+985B,U+9AAB,U+9AB3,U+9ACA,U+9B05,U+9B0B,U+9D69,U+9D6C,U+84AF,U+6F30,U+586B,U+614E,U+69D9,U+9DCF,U+503C,U+70BA,U+507D,U+6E88,U+5AAF,U+848D,U+80D0,U+81A7,U+43D3,U+63BD,U+78B0,U+67E5,U+6B1D,U+9109,U+56AE,U+97FF,U+6E89,U+66A8,U+5373,U+5EC4,U+5ED0,U+2FB3,U+5546,U+5E1D,U+610F,U+6697,U+6C38,U+7CAE,U+8109,U+8782,U+896F,U+8E09,U+9069,U+97F3,U+9F8D,U+660E,U+6708,U+6717,U+671F,U+773E,U+501C,U+56B3,U+60C6,U+6667,U+688F,U+7431,U+7A20,U+7A96,U+7DA2,U+8729,U+88EF,U+8AA5,U+8CD9,U+90DC,U+96D5,U+9760,U+9D60,U+9D70,U+5468,U+5F6B,U+6D69,U+8ABF,U+9020,U+9031,U+9177,U+9BDB,U+6559,U+840C,U+3001,U+3002,U+FF0C,U+FF0E,U+8B80,U+7006,U+6ADD,U+72A2,U+7258,U+7E8C,U+8D16,U+9EF7,U+89BF,U+7AC7,U+7C09,U+65E2,U+544A,U+7A3D,U+7DD2,U+4EA1,U+51CB,U+51E1,U+52D7,U+5984,U+5ADA,U+5E54,U+5FD8,U+5FD9,U+614C,U+6162,U+66F8,U+66FC,U+6700,U+69FE,U+7684,U+7693,U+76DF,U+76F2,U+7D04,U+7E35,U+828D,U+8352,U+855D,U+8B3E,U+914C,U+91E3,U+92E9,U+93DD,U+9592,U+9945,U+5177,U+4FF1
```

**Comment by edward-martyr** [comment]
<img width="457" alt="Screenshot 2020-06-30 at 10 22 20" src="https://user-images.githubusercontent.com/42882301/86075886-a4843580-babb-11ea-96cf-cc20d66e7146.png">

Comparison of glyphs mentioned by @NightFurySL2001 that would be corrected by this patch.

**Comment by NightFurySL2001** [comment]
Yea I think it's ok…? glyphs that had mapping changed in SHSans v2.0 (version used in this project) compared to v1.4 (version used by Genne Gothic) would need a remap with KR or JP to match the style in other characters but that would be hard to do.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by be5invis** [comment]
I've added overrides from Genne which should resolve this problem for many characters.
If there's any better overrides feel free to provide (as OTF) and I could update the source files.

**Comment by NightFurySL2001** [comment]
Ok, thanks for your help.

**Comment by edward-martyr** [comment]
> P/S: It looks like it only needs 5 weights to be eenough for override. Is that true?

Yeah Genne Gothic has two more weights than Sarasa Gothic.
