### ISSUE TITLE
Inconsistent glyph shape across same component of Classical Literature (CL) version

### ISSUE THREAD

**Issue by NightFurySL2001** [be5invis/Sarasa-Gothic#132]
Characters below are inconsistent across its components:

俞/兪 | 即 | 厲 | 叟 | 处 | 臽 | 勻/匀 | 㒸 | 區 | 勺 | 兼 | 尊 | 具/真
𣏂 | 周 | 忝 | 全 | 㓞 | 既 | 卂 | 告 | 直 | 前 | 并 | 率 | 兹

These glyphs are reviewed from Big5 standard of first order Chinese characters and compared to Recommended Inherited Glyphs document on here: https://github.com/ichitenfont/inheritedglyphs.

![image](https://user-images.githubusercontent.com/33471049/72662650-8f8f7a80-3a24-11ea-916e-2e3b7698901d.png)

**Comment by be5invis** [comment]
CL simply used KR version of SHS to create that.
OTF overrides are welcome (though -- it may be hard to produce, especially Sarasa's script needs every weight).
