### ISSUE TITLE
字体英文部分的字重能再分细点就好了

### ISSUE THREAD

**Issue by nobk** [be5invis/Sarasa-Gothic#135]
年纪大了，用来当编程字体的话，常规字重400看着太细，半粗体字重600太粗，能提供一套字重500的中黑吗，当然中文部分就不过多要求了，还是半粗的就好。

**Comment by KhaosChow** [comment]
唉，记得以前是有500Medium的字重的，不知从哪个版本后去掉了

**Comment by kennir** [comment]
同样的感觉，特别是在retina屏幕上，目前先用semibold顶着
