### ISSUE TITLE
Suggest Chinese users to download from the mirror hosted by Tsinghua TUNA

### ISSUE THREAD

**Issue by Lemmingh** [be5invis/Sarasa-Gothic#137]
Recently, **Tsinghua TUNA** added support for mirroring GitHub releases. (tuna/tunasync-scripts#32)

**Sarasa Gothic** is one of the projects that TUNA supports. (tuna/issues#695)

Since TUNA provides a really fast and reliable experience in Mainland China, could you please add something to `README`? For example:

```markdown
中国用户可从**清华大学开源软件镜像站**下载，有 2 种方式：

* 访问 <https://mirrors.tuna.tsinghua.edu.cn/>，点击“**获取下载链接**”按钮，选择“**字体**”选项卡，选取所需文件。
* 访问 <https://mirrors.tuna.tsinghua.edu.cn/github-release/be5invis/Sarasa-Gothic/>，选取所需文件。
```

Thank you.

**Comment by missdeer** [comment]
It's very slow for me - ISP Shanghai Telecom.

**Comment by duduluu** [comment]
呜喵，金枪鱼被吃掉了

**Comment by be5invis** [comment]
You can raise a PR to add this link into README...
