### ISSUE TITLE
TTC is broken?

### ISSUE THREAD

**Issue by Meru** [be5invis/Sarasa-Gothic#14]
Happens with all 4 TTCs from the latest release on win7 x64
![Image](https://i.imgur.com/DI4DEU3.png)

**Comment by be5invis** [comment]
Windows 7 cannot handle a TTC with 12 subfonts.
Use the TTF version instead.

**Comment by Meru** [comment]
I see. To answer my own question: yes, TCCs are broken. Moving on.

**Comment by be5invis** [comment]
@Meru 
No, the TTC is not broken. Windows 7-10 (TH2) is broken. It cannot support TTCs with many subfonts (which means that the sum of font name lengths would exceed 256 characters).
I've always used the TTCs on a Windows 10 machine and it worked perfectly.

**Comment by Meru** [comment]
@be5invis do you happen to know what is the max font number that _is_ supported?

**Comment by be5invis** [comment]
5-6 I think.

发自我的 iPhone

在 2018年2月19日，19:10，Meru <notifications@github.com<mailto:notifications@github.com>> 写道：


@be5invis<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbe5invis&data=02%7C01%7C%7C3438f6d8791e4bc26e2a08d577896311%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636546354311590434&sdata=%2Fyp5FQmvDZFrdwRdpULnps5%2B9RZmyTPr3reycKyHcJY%3D&reserved=0> do you happen to know what is the max font number that is supported?
