### ISSUE TITLE
Wrong rendering of "=" in lastest version (0.11) term font

### ISSUE THREAD

**Issue by szsdk** [be5invis/Sarasa-Gothic#140]
![image](https://user-images.githubusercontent.com/6657200/76372298-e9068c80-6377-11ea-811a-413f3e7cc9c5.png)

I think it may have something to do with this issue: https://github.com/be5invis/Sarasa-Gothic/issues/10.

**Comment by be5invis** [comment]
A `Sarasa Fixed` will be introduced in version 0.12 and will fix this issue. Closed.
