### ISSUE TITLE
v0.12.1 中无法使用 ligature 和 stylistic sets

### ISSUE THREAD

**Issue by ZhaoColo** [be5invis/Sarasa-Gothic#144]
v0.12.0 版本中连字使用正常，然而最新版本中似乎出了问题。

下面是 vs code 中使用的设置：

![图片](https://user-images.githubusercontent.com/62367110/77029296-446af700-69d6-11ea-8ead-d6f5ed65e02b.png)

使用的效果如下：

![图片](https://user-images.githubusercontent.com/62367110/77029856-e50de680-69d7-11ea-84d0-b111c956372c.png)

可以看到没有连字， `ss05` 设置也没有生效。

使用 Iosevka ：

![图片](https://user-images.githubusercontent.com/62367110/77029834-d1fb1680-69d7-11ea-8f55-b7d3b13e31b1.png)

**Comment by ZeekoZhu** [comment]
0.12.1 好像只在行首非空格的时候才显示连字效果

```
x => x + 1 // 0.12.1 与 0.12.0 均正常
 x => x + 1 // 0.12.1 不显示连字效果
```

下面是 JetBrains IDE 与 KWrite 中 0.12.1 的显示效果

![image](https://user-images.githubusercontent.com/13861843/77056131-fde4bf00-6a0c-11ea-92a1-6e3b2c16e826.png)

**Comment by ZhaoColo** [comment]
谢谢补充。不过在 VS Code 中使用 v0.12.1 的话，似乎即使是行首非空格情况下也没有连字。

另外一个奇怪的地方是在 VS Code 中使用 v0.12.0 版本字体时，如果关闭渲染空格一些连字也会消失。

| v0.12.0 使用 `ss05` 开启渲染空格 | v0.12.0 使用 `ss05` 关闭渲染空格 |
| :--: | :--: |
| ![image](https://user-images.githubusercontent.com/62367110/77071296-bd923a80-6a26-11ea-8b2d-4454c435f1b9.png) | ![image](https://user-images.githubusercontent.com/62367110/77071272-b408d280-6a26-11ea-8c85-df45b93eb0ab.png) |

看起来如果开启渲染空格并且连字前后的拉丁字母都用空格隔开的话就没有问题。但是字母 g 的变体始终无法显示。

如果使用 Iosevka 的话，无论什么情况下显示都很好。
