### ISSUE TITLE
“鸭”字在字号大小10的时候表现很差。

### ISSUE THREAD

**Issue by rcyggdra** [be5invis/Sarasa-Gothic#145]
大小：10
![image](https://user-images.githubusercontent.com/8652464/77151626-4e255500-6ad1-11ea-9883-d096ce834f65.png)

大小：初号
![image](https://user-images.githubusercontent.com/8652464/77151653-5b424400-6ad1-11ea-98e6-5db87af4ed84.png)

**Comment by be5invis** [comment]
Should be fixed in version 0.12.2. Closed.
