### ISSUE TITLE
「朗」字粗体在 15px ~ 20px 下 hinting 错误

### ISSUE THREAD

**Issue by Puxirepublic** [be5invis/Sarasa-Gothic#146]
「月」顶部被 hinting 扭曲掉了。之前版本并不存在该问题，可能是上一版修复的「鸭」#145 导致的后续。

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/77449759-9a151a00-6daf-11ea-9daa-38a232ea3c2a.png)
This is 16ppem, and everything looked fine. Please re-download and re-install the latest version.
