### ISSUE TITLE
Question about PUA

### ISSUE THREAD

**Issue by NightFurySL2001** [be5invis/Sarasa-Gothic#147]
Asking out of curiosity: it seems that a few characters have been added to the PUA in Sarasa Term. Are these characters used anywhere?
![image](https://user-images.githubusercontent.com/33471049/78256409-0ec42300-752b-11ea-9fef-cd2debe04dca.png)

**Comment by CyanoHao** [comment]
[Powerline](https://github.com/powerline/powerline)

**Comment by NightFurySL2001** [comment]
@CyanoHao  ok thanks!
