### ISSUE TITLE
Version 0.5.1 not fully compatible with WebStorm

### ISSUE THREAD

**Issue by Meeeeow** [be5invis/Sarasa-Gothic#15]
![image](https://user-images.githubusercontent.com/19658647/36708160-b2c4a8c4-1bac-11e8-9cd3-e2f8f317cdb1.png)

**Platform:** Windows 10
**Font version:** 0.5.1
**Font type:** TTC
**Application version:** WebStorm 2017.3.4

Monospaced font works on most application except WebStorm. Version 0.4.0 works find in WebStorm.

**Comment by be5invis** [comment]
Have you tried to uninstall before install? Override install may cause problems.

**Comment by Meeeeow** [comment]
@be5invis Thank you, now it works without issue.
Sorry for this, i don't know override install will copy multiple version of font to `C:\Windows\Fonts` and i did not realized this since it works after install old version.
