### ISSUE TITLE
Strange "Φ" in Gothic and UI. Version 0.12.3

### ISSUE THREAD

**Issue by edward-martyr** [be5invis/Sarasa-Gothic#150]
This is tested in the Mac Font app. Capital Greek letter Phi is way too small.
<img width="237" alt="Screenshot 2020-04-20 at 22 22 19" src="https://user-images.githubusercontent.com/42882301/79762476-6a791380-8355-11ea-8753-41d275e67ce5.png">

**Comment by edward-martyr** [comment]
The glitch appears in Light and Extralight styles.

**Comment by be5invis** [comment]
This should be already fixed in later releases. Closed.
