### ISSUE TITLE
Slab 版本不能用于 conhost.exe 中

### ISSUE THREAD

**Issue by Suyun514** [be5invis/Sarasa-Gothic#153]
![image](https://user-images.githubusercontent.com/52325399/80221830-6ceeac80-8678-11ea-8962-d565c9453467.png)
![image](https://user-images.githubusercontent.com/52325399/80221856-79730500-8678-11ea-9a0c-930d0e08e3d6.png)

**Comment by CyanoHao** [comment]
TTF 版有这个问题吗？

看起来像是 cmap format 4 太长被丢弃了 (https://github.com/caryll/otfcc/pull/65)。

**Comment by be5invis** [comment]
Fixed in Dev by upgrading the dependency.
