### ISSUE TITLE
In GDI, Hanguls in font with a stub cmap4 are missing.

### ISSUE THREAD

**Issue by CyanoHao** [be5invis/Sarasa-Gothic#157]
It occurs in TTC, Mono/Term/Fixed Slab SC/TC/HC, any subfamily.

`sarasa-regular.ttc` v0.12.5, Windows 10.0.19041, Korean:
![image](https://user-images.githubusercontent.com/14287996/80984481-7b9b4780-8e60-11ea-95d7-9a280be1ef24.png)

**Comment by CyanoHao** [comment]
Some test results:

`otfccdump sarasa-gothic-cl-regular.ttf | otfccbuild --stub-cmap4 -O3 -o sarasa-nocmap4.ttf` → Hanguls are missing. (`sarasa-gothic-cl-regular.ttf` is extracted from `sarasa-gothic-ttf-0.12.5.7z`.)

`otfccdump SourceHanSansK-Regular.otf | otfccbuild --stub-cmap4 -O3 -o shs-nocmap4.otf` → Good. (v2.001)

`otfccdump SourceHanSansK-Regular.otf | otfcc-c2q | otfccbuild --stub-cmap4 -O3 -o shs-nocmap4.ttf` → Good. (v2.001)

`otfccdump shs-nocmap4.ttf --pretty -o shs.json`, and then edit OS/2.ulCodePageRange1:
```
"ulCodePageRange1": {
    "latin1": true,
    "latin2": true,
    "cyrillic": true,
    "vietnamese": true,
    "jis": false,
    "gbk": false,
    "korean": true,
    "koreanJohab": false,
    "macRoman": true,
    "oem": true
},
```
and build with `otfccbuild shs.json --stub-cmap4 -O3 -o cp949.ttf`. → The icon is broken. (The font looks good in Windows Font Viewer.)
![image](https://user-images.githubusercontent.com/14287996/80988919-c5872c00-8e66-11ea-9347-1566307ada08.png)

**Comment by be5invis** [comment]
Fixed in Dev by upgrading the dependency.
