### ISSUE TITLE
Please provide region-specific subset OpenType/CFF (subset OTF)

### ISSUE THREAD

**Issue by jszhao** [be5invis/Sarasa-Gothic#158]
Now the OpenType/CFF Collection (OTC) is too large and provide too many fonts that may never be used.  Please provide region-specific subset OpenType/CFF (subset OTF). Thanks a lot.

**Comment by Lemmingh** [comment]
Seems you're talking about
https://github.com/be5invis/Sarasa-Gothic/issues/99#issuecomment-489307357
https://github.com/be5invis/Sarasa-Gothic/issues/123#issuecomment-549110588

---

Besides, Sarasa is in pure TrueType outlines; there is no CFF outline so far. And Sarasa fonts are Pan-CJK fonts.
