### ISSUE TITLE
字符✎使用Sarasa-Gothic字体无法显示

### ISSUE THREAD

**Issue by andot** [be5invis/Sarasa-Gothic#16]
我在Windows10上安装了Sarasa-Gothic系列字体，并在 WSL 上装了 PowerLine，将控制台字体设置为 Sarasa Term SC 后，其他一切都好，但是进入 Git 目录之后，符号“✎”显示为方块。如图：

![qq 20180315160934](https://user-images.githubusercontent.com/232161/37451155-a8b89784-286b-11e8-981d-b8c3b20abe27.png)

改为 DejaVu Sans Mono for Powerline 才能正常显示，如图：

![qq 20180315160830](https://user-images.githubusercontent.com/232161/37451198-d4fc3f3a-286b-11e8-920e-fd2b53bb314f.png)

 DejaVu Sans Mono 显然效果不如 Sarasa Term SC 好，但是如果 Sarasa Term SC 能够显示字符“✎”的话，就更完美了。

**Comment by be5invis** [comment]
这个是 Emoji，Sarasa 没有（也暂无计划）支持。

**Comment by andot** [comment]
这样啊，好吧。

**Comment by andot** [comment]
![qq 20180318122232](https://user-images.githubusercontent.com/232161/37562572-11bd0cbe-2aa7-11e8-8908-5897806643ee.png)
问题解决了，打开注册表编辑器，然后在`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink` 下，新建多值字符串，名字为 Sarasa Term SC，值为：

```
MICROSS.TTF,Microsoft Sans Serif,108,122
MICROSS.TTF,Microsoft Sans Serif
MINGLIU.TTC,PMingLiU
MSMINCHO.TTC,MS PMincho
BATANG.TTC,Batang
MSYH.TTC,Microsoft YaHei UI
MSJH.TTC,Microsoft JhengHei UI
YUGOTHM.TTC,Yu Gothic UI
MALGUN.TTF,Malgun Gothic
SEGUISYM.TTF,Segoe UI Symbol
```

其它几个 Sarasa 字体也可以这样配置。之后，重启计算机，就好了。
