### ISSUE TITLE
新版字体的英文部分是什么字体？

### ISSUE THREAD

**Issue by Suyun514** [be5invis/Sarasa-Gothic#162]
`README.md` 上仍然说是 `Noto Sans` 但是显然不是。可以看出大部分字体是 `San Francisco` 但是有细微的不同，少部分字符如 `5` 也看着像 `Roboto`。

![IMG_20200510_165052_757.jpg](https://i.loli.net/2020/05/10/9Zt4rUP3ThyFx6q.jpg)

**Comment by stone-zeng** [comment]
[Inter](https://github.com/rsms/inter)

**Comment by Lemmingh** [comment]
在 3 月 10 日，`README.md` 中就写着 Inter 了：

https://github.com/be5invis/Sarasa-Gothic/blob/8d92594589661ac92688f17e7d5f94a3a3b15147/README.md#L34-L36

在 1 月 18 日，`config.json` 中就写着 Inter 了：

https://github.com/be5invis/Sarasa-Gothic/blob/b105539779d60280cdc18081dcb9c3f0a88ce4eb/config.json#L4-L15

---

你看到的可能是某个网站的镜像，而不是 Belleve 写的 `README.md`。
