### ISSUE TITLE
Request: tar.xz format in releases

### ISSUE THREAD

**Issue by oxalica** [be5invis/Sarasa-Gothic#164]
Linux users need `p7zip` to decompress `.7z` archives in releases. But `p7zip` is **not maintained since 2016** and no bugfixes or even security fixes are being released. See [sourceforge](https://sourceforge.net/projects/p7zip/files/p7zip).
I suggest to provide more common compressed archive format like `.tar.xz` in releases.

I tried to repack the latest release [v0.12.6](https://github.com/be5invis/Sarasa-Gothic/releases/tag/v0.12.6) like this:
```shell
> tar -c ./sarasa-gothic-ttf | xz --lzma2=preset=9,dict=1536MiB >./sarasa-gothic-ttf.tar.xz
> tar -c ./sarasa-gothic-ttc | xz --lzma2=preset=9,dict=1536MiB >./sarasa-gothic-ttc.tar.xz
```
It costs about 2h10min to complete and produces archives in size 168MiB and 93MiB, which are both smaller than `7z` (213MiB and 107MiB).

Related: https://github.com/NixOS/nixpkgs/pull/86417

**Comment by CyanoHao** [comment]
Arch Linux’s `makepkg` prepares 7z archives with [libarchive](https://github.com/libarchive/libarchive).

You can manually invoke it:
```bash
mkdir sarasa-ttc && cd sarasa-ttc
bsdtar -xf ../sarasa-gothic-ttc-0.12.6.7z
```

**Comment by oxalica** [comment]
@CyanoHao Thanks, that works.

Well, I just think if xz is not worse than 7zip, more common tool is preferred.
Also on windows, I think 7zip can decompress tar.xz as well (but I'm not tested yet).

**Comment by oxalica** [comment]
@be5invis How do you think about replacing `7z` with `tar.xz`?
