### ISSUE TITLE
安装这个字体会导致 Cadence 无法被启动，请开发者修复！

### ISSUE THREAD

**Issue by nikbobo** [be5invis/Sarasa-Gothic#166]
我安装了这个字体中的两个字体：Sarasa Mono SC、Sarasa Mono Slab SC，然后突然发现我的 Cadence 无法启动，反复重新安装多次均如此，甚至换过 16.6 17.2 17.4 版本都是，要不就是 This application quit unexpectedly，要不就是无任何提示即闪退，检查了一周，最后用 API Monitor 巧合发现读取到这两个字体就有一个程序莫名结束，卸载这两个字体之后，Cadence 一切恢复正常，请开发者修复！

**Comment by be5invis** [comment]
If you are using TTC then you could try install the TTF version, which _should_ have better compatibility. If you are using TTF, there's not much that I can do -- some software may have very weird font parsers and crash when parsing some unusual but valid fonts.

**Comment by nikbobo** [comment]
我已经使用的就是 TTF 字体，刚刚尝试安装了 TTC 字体，也依然不行……此问题在 Cadence 17.2（最后留下的版本）上可以稳定复现。

**Comment by be5invis** [comment]
Considering Cadence is a CAD software, it may have its own font parser to generate outlines, etc. Since I do not have its source code I cannot do anything for you. Sorry.
I've tested Sarasa on DWrite and Harfbuzz/Freetype, and they worked well.
Closed as wontfix.
