### ISSUE TITLE
Cannot install on Windows 2016

### ISSUE THREAD

**Issue by hcoona** [be5invis/Sarasa-Gothic#17]
Reproduce steps:

1. Download ttc font with version v0.5.2 from release page
2. Extract it somewhere & install them all

Expected:
All of them successfully installed.

Actual:
Cannot install sarasa-bolditalic.ttc because of invalidation.

Additional:
1. The font sarasa-bolditalic.ttc can be preview
2. Windows version: Windows Server 2016 14393.2097

**Comment by be5invis** [comment]
TTF or TTC?
TTC version may have compatibility issues in earlier Windows. It's because of Windows, not Sarasa.

**Comment by hcoona** [comment]
As mentioned in the details, TTC version. Got it, thanks.
