### ISSUE TITLE
Sarasa UI SC 在浏览器中某些字号下英文字符明显高于中文字符

### ISSUE THREAD

**Issue by ghost** [be5invis/Sarasa-Gothic#172]
## 复现步骤
1. 安装 Firefox 77.0.1 (64 位) 和更纱黑体 v0.12.8（但是此问题以前的版本也有），系统 DPI 缩放为 100%
2. 浏览器中打开 about:preferences，将 Sarasa UI SC 设置为默认无衬线字体，字体大小设置为 16，如图所示。
![图片](https://user-images.githubusercontent.com/51219500/85914420-f59fe980-b86f-11ea-84bd-3150750c1465.png)
3. 打开 https://zh.wikipedia.org/wiki/2019%E5%86%A0%E7%8A%B6%E7%97%85%E6%AF%92%E7%97%85%E7%96%AB%E6%83%85 ，网页缩放为 100%，查看右侧信息框内文本，可以发现英文字符明显高于中文字符，如图所示。
![图片](https://user-images.githubusercontent.com/51219500/85914445-3566d100-b870-11ea-86c3-bef9558fbace.png)
4. 将网页缩放调整为 120% 此问题就会消失。

**Comment by clafiok** [comment]
注：根据浏览器开发人员工具确定出现问题的字号为13px。

**Comment by zzColin** [comment]
13px 的 hinting 确实有点……怎么说呢，中文找了几个字数了下，都是 12×11，纵向上少一个像素，整体看上去是胖扁的形态；旧版没这个问题，然而却在某些字号下呈现出瘦高的形态——也许这是自动 hinting 暂时解决不了的限制？我个人倒是喜欢旧版那样，不介意瘦高形态，但对胖扁形态很不爽，然而这毕竟是个人喜好的问题，众口难调……
13px 的英文则是过于瘦高，观感上都跟 14px 一样大了，显然跟中文部分相反应该减掉一个像素。这大概是 ttfautohint 的问题？

**Comment by zzColin** [comment]
This should be the same issue with #155

**Comment by bodayw** [comment]
Looks like this is fixed now?

**Comment by MY1L** [comment]
限定字号的一般就是hinting问题。要不改用没hint的……

**Comment by be5invis** [comment]
Should have been resolved in latest version. Closing.
