### ISSUE TITLE
一些软件在某些字号下，等宽字体的两个英文字母无法对齐一个汉字

### ISSUE THREAD

**Issue by ZyyMaker** [be5invis/Sarasa-Gothic#173]
在 Word 里面一切正常
![Snipaste_2020-07-03_20-46-01](https://user-images.githubusercontent.com/30658014/86471329-bf7ed000-bd6f-11ea-8cec-dd7363cc63b0.png)

但到了其他软件，如记事本和 IDEA 里就出现了问题
在测试的字号里，记事本 14-16px 出现问题
![Snipaste_2020-07-03_20-47-04](https://user-images.githubusercontent.com/30658014/86471476-0967b600-bd70-11ea-9995-26be9112d323.png)
![Snipaste_2020-07-03_20-48-09](https://user-images.githubusercontent.com/30658014/86471487-0ff62d80-bd70-11ea-8dcd-2a289f4bb29c.png)
IDEA 17-18px 出现问题
![Snipaste_2020-07-03_20-51-10](https://user-images.githubusercontent.com/30658014/86471551-269c8480-bd70-11ea-884d-a746960a80e2.png)
![Snipaste_2020-07-03_20-51-26](https://user-images.githubusercontent.com/30658014/86471567-2dc39280-bd70-11ea-9c02-228909202af2.png)
 希望能得到解决

另外，系统版本号为 20161.1000，设置中开了 125% 缩放

**Comment by be5invis** [comment]
Duplicate of #108, caused by metric rounding (i.e., your PPEM is an odd number).
Closed.
