### ISSUE TITLE
Japanese Hiragana "ぽ" and "ぼ" appear to have missing strokes at around 14px

### ISSUE THREAD

**Issue by bodayw** [be5invis/Sarasa-Gothic#174]
As shown below, the first stroke on the right appeared to be missing:

![image](https://user-images.githubusercontent.com/8195684/87005469-e3795180-c173-11ea-9454-2d979deb53b8.png)

This happens when font size is anywhere between 13.5px and 14.5px.

"ほ" doesn't have this problem.

**Comment by be5invis** [comment]
Should have been fixed in 0.12.10

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/87228075-b1bee100-c353-11ea-917f-996f1d71fae1.png)
