### ISSUE TITLE
Japanese katagana "モ" appear to have partially missing stroke at around 12px

### ISSUE THREAD

**Issue by bodayw** [be5invis/Sarasa-Gothic#175]
As shown below:

![image](https://user-images.githubusercontent.com/8195684/88231495-34d01900-cc29-11ea-960f-806869d7e2cf.png)

(while I was on this I just checked all Japanese kana in 10-16 px and all else seem fine to me. Hopefully this is the last one for me to report in a while)

**Comment by be5invis** [comment]
Should be fixed in 0.12.12
