### ISSUE TITLE
Windows商店里的字体是官方的吗？

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [be5invis/Sarasa-Gothic#176]
我是否能直接从这里下载安装？
https://www.microsoft.com/zh-cn/p/%e6%9b%b4%e7%ba%b1%e9%bb%91%e4%bd%93/9mw0m424ncz7#activetab=pivot:overviewtab

**Comment by be5invis** [comment]
It is not, but Sarasa is OFL, so anyone could redistribute it.
Closed.

**Comment by zhengxiaoyao0716** [comment]
I got it, thank you.
