### ISSUE TITLE
"餐"字在SC gothic 10号及以下的大小显得"残缺"

### ISSUE THREAD

**Issue by rcyggdra** [be5invis/Sarasa-Gothic#177]
SC v0.12.11:![image](https://user-images.githubusercontent.com/8652464/89089485-1956d200-d3d0-11ea-9d75-0d0a689b1ef0.png)

HC、J的10号对比：
![image](https://user-images.githubusercontent.com/8652464/89097335-b174ab80-d410-11ea-924a-713ef6bf633e.png)

**Comment by be5invis** [comment]
Should been fixed in 0.12.12
