### ISSUE TITLE
Lowest Node.js version to build the font

### ISSUE THREAD

**Issue by Toufukun** [be5invis/Sarasa-Gothic#179]
With the Node.js provided by Ubuntu 20.04 (without PPA), I could not compile the font.

The version is 10.19.0, which is higher than the required version (>= 8.5).

<img width="866" alt="nodejs version" src="https://user-images.githubusercontent.com/6957041/89755689-4ed57c80-daae-11ea-9ab1-1f18095ebbec.png">

However, I'm able to compile with the latest LTS version (12.18.3).

**Comment by be5invis** [comment]
Ah it's in the `package.json` but not README.
Fixed.

**Comment by Toufukun** [comment]
Sorry, I didn't check `package.json`.
