### ISSUE TITLE
Sarasa UI SC Font names are not the same in Linux & Windows

### ISSUE THREAD

**Issue by IanGoo** [be5invis/Sarasa-Gothic#180]
UI SC在Linux和Windows两个系统里的字体名似乎不一样，以前没有这个问题。在Linux里叫“Sarasa UI SC”而在Windows里叫“更纱黑体 UI SC”，这导致建立了一个LibreOffice文档后理应使用相同字体的文档在两个系统里会有一个提示字体缺失。Term SC就没有类似的问题，两个系统里都叫“Sarasa Term SC”。

安装的是TTF字体。Windows 10 2004，Linux发行版为Manjaro，桌面环境Gnome。

**Comment by be5invis** [comment]
Well, it has localized font names, which is considered by design.
I think you should raise a bug to LibreOffice to always store non-localized font name in the files, but allow using localized name in the UI...
