### ISSUE TITLE
能否将Readme翻译为为中文/Can You translate Readme to Chinese

### ISSUE THREAD

**Issue by MuggleWang** [be5invis/Sarasa-Gothic#181]
首先非常感谢你们优秀的工作

Thanks for your excellent work!

但是对Readme 中的各个Style解释看不明白，不知道应该装哪个字体。下载下来有好多好多种字体，很疑惑。

Confused about the names of each fonts. There are so many types of fonts, and I'm not sure which to install.

**Comment by MuggleWang** [comment]
比如，“sarasa-mono-slab-sc-regular.ttf”中的“slab”是什么意思呢？

如果能用图来表示不同字体间的区别就太好了。或者可以给出我应该选择哪种字体的建议吗？

For example, what does "slab" in "sarasa-mono-slab-sc-regular.ttf" mean?

It would be great if you could use pictures to show the difference between different fonts. Or can you suggest which font I should choose?

**Comment by be5invis** [comment]
Slab means Slab Serif.
I do not have pipelines to generate images for now. Maybe later I may add them

**Comment by MuggleWang** [comment]
Thanks for your reply!

**Comment by Ynjxsjmh** [comment]
> Slab means Slab Serif.

Could this be added into README **What are the names** section? There are many flavors use this notation.

Also does the flavors without Slab mean Sans Serif? For example, there are `sarasa-mono-sc-regular.ttf` and `sarasa-mono-slab-sc-regular.ttf`.
