### ISSUE TITLE
Sarasa CL「為」U28858字形錯誤

### ISSUE THREAD

**Issue by baopaau** [be5invis/Sarasa-Gothic#184]
「為」U28858
「爲」U29234
兩者在Sarasa CL中均顯示爲「爲」，不能區分
其他地域性字形則不存在此問題

**Comment by CyanoHao** [comment]
[I.Ming](https://github.com/ichitenfont/I.Ming) 亦采用这种处理方式。

《傳承字形推薦形體表》给出的理由：
> 我們強烈呼籲字型製作者以字理爲本，製作傳承字形的字型時，不要盲從「字源分離原則」這種違反傳承字形原則的過時技術副產品。否則，若製作者只把「値」、「靑」、「爲」等傳承字形，放在5024、9751、7232這些正體（繁體）中文「事實標準」裏較少用的碼位；至於正體（繁體）中文「事實標準」裏常用的碼位503C、9752、70BA，則放置着違反傳承字形規定的「值」、「青」、「為」等字形，只會令用戶容易踩中陷阱，誤用非傳承字形。這種做法顯然違反選擇傳承字形用戶之意願，絕不可取。
