### ISSUE TITLE
updated from 0.12.14 to 0.13.3. fonts sizes are really bad

### ISSUE THREAD

**Issue by SUCM** [be5invis/Sarasa-Gothic#185]
tried TC/SC/J variants at  9, 10, 11, 12, 16 sizes, all look extremely broken on Win 10

below 3 lines of texts don't even line up to the same width with 0.13.3 fonts. they only line up with 0.13.3 mono fonts. you can do simple tests using Word or Excel/Spreadsheet to see how bad this is

```
0:01:11.19
0:01:08.36
0:01:05.47
```
0:01:11.19
0:01:08.36
0:01:05.47

**Comment by CyanoHao** [comment]
Sarasa Gothic has tabular numerals:

![image](https://user-images.githubusercontent.com/14287996/92450392-f8af4280-f1ed-11ea-868e-0ddefa33f7c2.png)

To use tabular numerals in Word:

![image](https://user-images.githubusercontent.com/14287996/92449548-d2d56e00-f1ec-11ea-8d45-b6d5b5e54b73.png)

But I didn't find such an option in Excel. Does it support `tnum`? @be5invis

**Comment by SUCM** [comment]
the main problem is that 0.13.3 look a lot different from 0.12.x and text display in regular text editor or application UI are pretty broken. Word/Excel were for ease of reproducing the problem

1. don't think most pure text editor or application UI supports tabular
2. there are other texts not lining up in 0.13.3, but lined up fine in 0.12.x

**Comment by SUCM** [comment]
maybe issue is somewhere else. I tried installed 0.12.14 to overwrite 0.13.3, but the same messed up display stays even after rebuild- font cache and reboot

**Comment by be5invis** [comment]
This is considered a feature of Inter, the LGC part of Sarasa Gothic, which have proportional figures by default. I plan to enable tabular digits in next release by default.
Closing.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/92696773-35b72a00-f2ff-11ea-853f-c4a3c9fe077e.png)

**Comment by SUCM** [comment]
this is how 0.13.3 look like for date and time in media player's playlist. media player allows selecting the font, but not the format (tabular, strike-through...etc). those texts used to line up perfectly fine with the older versions of Sarasa-Gothic, but not anymore after I installed 0.13.3. date and time also require wider playlist columns which suggest font/texts of newer Sarasa-Gothic is actually wider for the same font size

![numbers](https://user-images.githubusercontent.com/7042609/92697305-acbde400-f33a-11ea-8c6c-7eb3c952c83c.png)
