### ISSUE TITLE
bottom portion of 繁 in 0.13.3 等距更紗黑體 TC looked smashed

### ISSUE THREAD

**Issue by SUCM** [be5invis/Sarasa-Gothic#186]
seems to be smashed for size 14 and below
not as bad in SC and JP, but still look pretty awkward

size 10, 12, 14...etc have different width between 0.13.3 and 0.12.14. I had a couple Excel spreadsheets where I allocated the exact column width for texts and numbers with 0.12.14. I had to increase all column widths after updated to 0.13.3

**Comment by SUCM** [comment]
相同文字的正體TC、簡體SC和日文J顯示比較圖
![compare](https://user-images.githubusercontent.com/7042609/92685142-986fec00-f326-11ea-8c99-88e0ac064954.png)

**Comment by be5invis** [comment]
Should have been fixed in latest version. Closing.
