### ISSUE TITLE
0.13.3版本號碼錯誤？

### ISSUE THREAD

**Issue by SUCM** [be5invis/Sarasa-Gothic#187]
安裝0.13.3後，在Win10下Sarasa Gothic *顯示0.13.2，但是其他Term、Slab、Mono等等的都顯示為0.13.3。下面是比較圖
![compare](https://user-images.githubusercontent.com/7042609/92684056-0bc42e80-f324-11ea-8646-abf2ba4bac43.png)

**Comment by be5invis** [comment]
Some name strings are written as 0.13.2 which may be caused by caches when building v0.13.3.
I will fix that in next release.
