### ISSUE TITLE
Superscript 4 is misaligned

### ISSUE THREAD

**Issue by yuhr** [be5invis/Sarasa-Gothic#193]
<img width="525" alt="Screenshot 2020-10-17 at 2 27 58" src="https://user-images.githubusercontent.com/18474125/96289640-60904e80-1020-11eb-9547-b917fd2956f0.png">

I haven't tested all styles but above image is using Sarasa Mono Slab J.

**Comment by be5invis** [comment]
Fixed in 0.14.4.
