### ISSUE TITLE
宽度怎么能调整

### ISSUE THREAD

**Issue by jerviscui** [be5invis/Sarasa-Gothic#194]
请问字体宽度可以调整成 Source Code Pro 这样的吗？
感觉字母挨太近了，代码阅读不方便。

**Comment by liangch** [comment]
vscode里可以调整Editor: Letter Spacing。

**Comment by jerviscui** [comment]
@liangch 
好的， 谢谢。
大佬知道 VS 能调整 Letter Spacing 吗？
