### ISSUE TITLE
“系”字及部分鸟字底的字表现不好

### ISSUE THREAD

**Issue by rcyggdra** [be5invis/Sarasa-Gothic#195]
“系”字在字号12及以下字形有所差异，
一部分的鸟字底的字也是表现不好：鹰、鸯、鸾、鹫、鹥等字
11号字样：
![image](https://user-images.githubusercontent.com/8652464/97317307-a0b7c280-18a5-11eb-8137-645d687817b2.png)

**Comment by MY1L** [comment]
限定字号的问题一般就是hinting问题。要不改用没hint……

**Comment by be5invis** [comment]
Should have been fixed in latest version. Closing.
