### ISSUE TITLE
Center punctuation mark for Sarasa CL

### ISSUE THREAD

**Issue by Kotori142857** [be5invis/Sarasa-Gothic#196]
### Sarasa Gothic CL Nowadays
![Sarasa](https://user-images.githubusercontent.com/43498546/97530632-81c44800-19ed-11eb-841c-db2fdd7f21fb.png)
### [Genne Gothic](https://github.com/MoneMizuno/Genne-Gothic)
![Genne](https://user-images.githubusercontent.com/43498546/97530667-956fae80-19ed-11eb-8313-dd79add875f1.png)
### [Glow Sans TC v0.91](https://github.com/welai/glow-sans/releases/download/v0.91/GlowSansTC-Normal-v0.91.zip)
![Glow](https://user-images.githubusercontent.com/43498546/97530685-a0c2da00-19ed-11eb-943b-8194d7afb16d.png)

**Comment by edward-martyr** [comment]
竖排时句读右下才是 Classical Orthography 吧？
