### ISSUE TITLE
<<= and >>= ligatures seem missing from all variant sets

### ISSUE THREAD

**Issue by 747** [be5invis/Sarasa-Gothic#197]
![image](https://user-images.githubusercontent.com/3427854/97540515-1ab38d00-1a07-11eb-9c09-c9b00afc9b1a.png)

Confirmed with TTC 0.14.5, all locales, on VSCode and LibreOffice.

**Comment by be5invis** [comment]
This is by design, the default `calt` have `<<=` and `>>=` assigned to shift-assign instead of Haskell-ish arrows. To enable the alternative you could use `dlig` and turn **off** `calt`.
Closing.
