### ISSUE TITLE
想用更纱黑体嵌入pdf文档，结果嵌入以后的字形无法正常显示，这个是什么原因造成的？

### ISSUE THREAD

**Issue by Seekladoom** [be5invis/Sarasa-Gothic#199]
如图，鄙人在Freeplane这个思维导图软件中用更纱黑体导出PDF，结果导出以后显示的字体却是"方正琥珀"，有时候还会随机崩成其他方正字体，这是怎么一回事？
![图1](https://user-images.githubusercontent.com/35969469/98288714-3956ec80-1fe2-11eb-8e2d-cb327d3bd14b.jpg)
![图2](https://user-images.githubusercontent.com/35969469/98288734-3fe56400-1fe2-11eb-88c0-5e864e1140bc.jpg)

**Comment by CyanoHao** [comment]
应该是 Freeplane 对字体名的处理有问题。

测试了一下
* 简体中文 Windows（系统语言和非 Unicode 程序语言都设为简体中文）微软雅黑、等线、更纱黑体 SC 字体，以及日语 Windows 游哥特、游明朝，这些字体的非 Regular、Bold 字重都有这个问题。
* 以上字体的字体名变成英语（微软雅黑、游哥特对应的 UI 版；以及英语 Windows 下）就正常了。
* Windows 系统语言和非 Unicode 程序语言不匹配时，某些字体在 Freeplane 里从列表中消失了。例如，系统语言为英语，非 Unicode 程序语言为简体中文，这种情况下 Freeplane 既没有 “微软雅黑” 也没有 “Microsoft YaHei”。

**Comment by Seekladoom** [comment]
感谢提醒，试着把"更纱黑体 SC Semibold"改成"Sarasa Gothic PDF SC Semibold"以后总算能在Freeplane中把字体正常嵌入PDF了。
![Sarasa Gothic PDF SC Semibold](https://user-images.githubusercontent.com/35969469/98805209-30d33b80-2452-11eb-83a7-412f56528303.png)

另外再问一个问题，老哥如果方便的话也看看吧。。。_(:з」∠)_
为何方正兰亭中黑_GBK在Freeplane中直接使用没有问题，如果要对更纱黑体不改中文名也做到和兰亭黑一样的效果，应该怎么改才能让更纱黑体有和方正兰亭中黑_GBK一样好的兼容性？
【方正兰亭中黑_GBK FontExpert截图】
![方正兰亭中黑_GBK FontExpert截图](https://user-images.githubusercontent.com/35969469/98805424-81e32f80-2452-11eb-8560-5b8116394fbf.png)
【更纱黑体 SC Semibold FontExpert截图】
![更纱黑体 SC Semibold FontExpert截图](https://user-images.githubusercontent.com/35969469/98805471-90314b80-2452-11eb-8557-e4cee26db312.png)

**Comment by lychichem** [comment]
估计在字体的一个什么name表里写上一串多种语言的name能解决（比如微软雅黑写了20几个语言的name），我们不用那么多，写个中英日韩就差不多了
