### ISSUE TITLE
请问"cl"版本是旧字形吗

### ISSUE THREAD

**Issue by hingbong** [be5invis/Sarasa-Gothic#2]
同样是"cl"版本，inziu是旧字形的sarasa不是，比如“感”字

**Comment by be5invis** [comment]
Sarasa supports LOCL feature that, if you tag your text into zh-TW, it would switch into Taiwan glyphs.
Hmmm, I'd like to remove that.

**Comment by hingbong** [comment]
Thanks for removing this feature.

**Comment by be5invis** [comment]
Fixed in v0.3.
