### ISSUE TITLE
传统上中文没有西文的横向倾斜形式，那么italic的汉字部分是否可以改成纵向倾斜体？

### ISSUE THREAD

**Issue by MY1L** [be5invis/Sarasa-Gothic#207]
即横斜竖不斜，且右高于左。这种斜体汉字字形不仅事实存在于传统的仿宋字等，不严谨地说，有部分“斜体汉字”还被统一码编码了：[𛆁𛈬 | 女书](https://github.com/nushu-script/Nyushu)（我画的范例）

我看到Sarasa-*italic里的倾斜中文不是思源有的，也不是腾讯那种斜体，看上去是机械横向倾斜而来，所以询问是否可能机械纵向倾斜？至少传统CL写法可以试试。

**Comment by be5invis** [comment]
No fonts have been done in that way. Closing.

**Comment by MY1L** [comment]
我觉得某些场合还是用得上的，所以整了一个粗糙的[示意用字体/HanItalic](https://github.com/MY1L/HanItalic/releases)，请看这样的如何？
![明日方舟](https://user-images.githubusercontent.com/58043328/102693127-3abb3c00-4253-11eb-93cd-fff410f55579.png)
