### ISSUE TITLE
思源黑体2.002的部分更新没有反映在更纱黑体上

### ISSUE THREAD

**Issue by lychichem** [be5invis/Sarasa-Gothic#208]
从我用fontforge查看字体的情况来看，至少思源黑体2.002更新里加的4个unicode扩展G区汉字没加进更纱黑体，有点遗憾。但很奇怪的是我看到前辈的source\shs文件夹下的思源黑体又是更新过的，不知道是不是构建的时候忽略了啥。

**Comment by be5invis** [comment]
Should be a building issue. Next version will fix it.

**Comment by lychichem** [comment]
还有个问题想请教前辈，这个字体的UPM设定是1000，但是我在fontforge网站看到了这句：
![image](https://user-images.githubusercontent.com/9316590/100460895-ed8bf480-3102-11eb-880e-6b2bb0f9c738.png)
因为opentype字体扩展名也可能是ttf所以想问下前辈这个设定……起因是虽然不知道为啥但是感觉用fontforge把UPM改到2048之后用更纱黑体做系统字体时软件界面的加载速度会快几秒？（当然也有可能是改UPM的时候hint掉了啥的）如果本字体确实是truetype字体的话可能UPM设成2048兼容性会好点？

**Comment by qazesz1** [comment]
> 还有个问题想请教前辈，这个字体的UPM设定是1000，但是我在fontforge网站看到了这句：
> ![image](https://user-images.githubusercontent.com/9316590/100460895-ed8bf480-3102-11eb-880e-6b2bb0f9c738.png)
> 因为opentype字体扩展名也可能是ttf所以想问下前辈这个设定……起因是虽然不知道为啥但是感觉用fontforge把UPM改到2048之后用更纱黑体做系统字体时软件界面的加载速度会快几秒？（当然也有可能是改UPM的时候hint掉了啥的）如果本字体确实是truetype字体的话可能UPM设成2048兼容性会好点？

Sarasa加载速度的问题是因为对所有尺寸都进行平滑处理，可以改gasp表解决
https://docs.microsoft.com/en-us/typography/opentype/spec/gasp

雅黑
`"gasp":[{"rangeMaxPPEM":8,"dogray":true,"gridfit":false,"symmetric_smoothing":true,"symmetric_gridfit":true},{"rangeMaxPPEM":21,"dogray":true,"gridfit":true,"symmetric_smoothing":false,"symmetric_gridfit":true},{"rangeMaxPPEM":65535,"dogray":true,"gridfit":true,"symmetric_smoothing":true,"symmetric_gridfit":false}]`

sarasa
`"gasp":[{"rangeMaxPPEM":65535,"dogray":true,"gridfit":true,"symmetric_smoothing":true,"symmetric_gridfit":true}]`

**Comment by qazesz1** [comment]
好吧，改gasp只是提高了字体查看器渲染大号的速度，单一字号还是慢。不过改了以后高dpi屏幕上就没有hint，快的多了
