### ISSUE TITLE
Width of pozhehao (破折号)

### ISSUE THREAD

**Issue by Stone-Zeng** [be5invis/Sarasa-Gothic#21]
The width of pozhehao (`U+2E3A` or two `U+2014`) is the same as one normal Chinese character in Sarasa Mono. But in [clreq](https://w3c.github.io/clreq/#table_of_non-bracket_indication_punctuation_marks), it should "takes space of two characters, in the shape of a single line without a break".

This is the same for `U+2E3B` (three-em dash).

![image](https://user-images.githubusercontent.com/18233088/37951865-85fba8b2-31d0-11e8-9f5a-4390e27c7932.png)

Is this a feature of Sarasa-Gothic?

Version: 0.5.0

**Comment by be5invis** [comment]
It is a feature of Sarasa Mono to keep consistency with Iosevka

**Comment by Stone-Zeng** [comment]
But it looks really strange in a Chinese article. And ellipsis also takes two spaces.

**Comment by be5invis** [comment]
Sarasa Mono is for CODING, not ARTICLE.

**Comment by Stone-Zeng** [comment]
Could there be some features for selecting the width in the future?

**Comment by be5invis** [comment]
Closed via v0.5.3

**Comment by ZSkycat** [comment]
[`U+002D` -](https://zh.wikipedia.org/wiki/%E9%80%A3%E5%AD%97%E6%9A%A8%E6%B8%9B%E8%99%9F)
[`U+2014` —](https://zh.wikipedia.org/wiki/%E8%BF%9E%E6%8E%A5%E5%8F%B7)

`U+2014` 渲染成半角宽度 和 `U+002D` 完全一样，实在太容易被误导了，导致没正确处理好半角全角一致性的问题。

- 等距不只是适用于代码显示，还可以用在其他需要等距的场景
- 代码中不止只有英文字符，也会有区分 - 和 — 的需要

不知道这个是由于 Iosevka 导致的还是特地这么设置的，但是无论如何这么处理 `U+2014` 不适合使用 CJK字符 的世界，把常用符号给混淆了。

**Comment by be5invis** [comment]
Have you tried MonoT version?

________________________________
发件人: ZSkycat <notifications@github.com>
发送时间: Sunday, March 17, 2019 6:50:27 PM
收件人: be5invis/Sarasa-Gothic
抄送: Belleve Invis; State change
主题: Re: [be5invis/Sarasa-Gothic] Width of pozhehao (破折号) (#21)


U+002D -<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzh.wikipedia.org%2Fwiki%2F%25E9%2580%25A3%25E5%25AD%2597%25E6%259A%25A8%25E6%25B8%259B%25E8%2599%259F&data=02%7C01%7C%7C8bc10b965bdc41b05c6e08d6aac65e94%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636884166303670705&sdata=di2qwwncJcOohyiJ8dU6iO3HAImk99raNlCbtDzoL3w%3D&reserved=0>
U+2014 ―<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzh.wikipedia.org%2Fwiki%2F%25E8%25BF%259E%25E6%258E%25A5%25E5%258F%25B7&data=02%7C01%7C%7C8bc10b965bdc41b05c6e08d6aac65e94%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636884166303680712&sdata=dqLw%2B%2F3o35l%2F6n0c0cvVl9Pitc2YX%2F7zJGl4qyRsBdA%3D&reserved=0>

U+2014 渲染成半角宽度 和 U+002D 完全一样，实在太容易被误导了，导致没正确处理好半角全角一致性的问题。

  *   等距不只是适用于代码显示，还可以用在其他需要等距的场景
  *   代码中不止只有英文字符，也会有区分 - 和 ― 的需要

不知道这个是由于 Iosevka 导致的还是特地这么设置的，但是无论如何这么处理 U+2014 不适合使用 CJK字符 的世界，把常用符号给混淆了。

―

**Comment by ZSkycat** [comment]
在 vscode 中发现奇怪的渲染问题
`U+2014` 若左边存在 `A-Za-z` 的字符时，会渲染成全角宽度，并且无论这中间有多少空格和半角符号。

![image](https://user-images.githubusercontent.com/20368649/54489491-c027f480-48e7-11e9-88ae-3caf7e23ebb3.png)

测试文本
```
`U+2014`
—
   —
A—
a   —
Z   .123456789—
Z   啊啊—
```

**Comment by be5invis** [comment]
Perhaps a LOCL feature. I’d like to remove that.

________________________________
发件人: ZSkycat <notifications@github.com>
发送时间: Sunday, March 17, 2019 7:10:28 PM
收件人: be5invis/Sarasa-Gothic
抄送: Belleve Invis; State change
主题: Re: [be5invis/Sarasa-Gothic] Width of pozhehao (破折号) (#21)


在 vscode 中发现奇怪的渲染问题
U+2014 若左边存在 A-Za-z 的字符时，会渲染成全角宽度，并且无论这中间有多少空格和半角符号。

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F20368649%2F54489491-c027f480-48e7-11e9-88ae-3caf7e23ebb3.png&data=02%7C01%7C%7C8fe8e935a8ee4a17e86608d6aac92ad9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636884178314943917&sdata=oxet7hIwfSfqruC%2BbU66tPMRUwVWuKX%2B1Ks8wjRkCcs%3D&reserved=0>

测试文本

`U+2014`

―

   ―

A―

a   ―

Z   .123456789―

Z   啊啊―



―

**Comment by ZSkycat** [comment]
@be5invis `MonoT version` 版本是什么，是在 Sarasa 字体里面的吗

在 Chrome 中给测试文本的 dom 添加 `font-family: 'Sarasa Term SC';`，并没有出现一样的效果，或许是 `vscode` 自己的问题？
传统的 Notepad++ 使用这个字体是不会出现这种情况的。

**Comment by be5invis** [comment]
@ZSkycat 
![image](https://user-images.githubusercontent.com/240091/54489616-19dcee80-48e9-11e9-849e-585b65eab8cb.png)
There is a specialized MonoT version that has em-dashes stylized as full-width.
I'd like to remove LOCL in monospace versions to prevent any kind of rendering mistakes.

**Comment by ZSkycat** [comment]
@be5invis 我明白了，monoT 不包括在 ttc 字体里

使用 monoT 两个字符会出现一点差异，是这个意思吗
![image](https://user-images.githubusercontent.com/20368649/54490472-eef69880-48f0-11e9-8991-5f693d6c2429.png)

**Comment by be5invis** [comment]
@ZSkycat It is in TTC. After you install that, you will find a font family named `Sarasa MonoT`, which contains a variant that em-dashes are full-width.

**Comment by ZSkycat** [comment]
😅 重新安装了最新版（抱歉，忘了自己是很久以前装的字体了）

发现了新选择，完美工作！
![image](https://user-images.githubusercontent.com/20368649/54490645-801a3f00-48f2-11e9-988f-7370222dfa51.png)
