### ISSUE TITLE
Gothic字形数字间距太大

### ISSUE THREAD

**Issue by qazesz1** [be5invis/Sarasa-Gothic#210]
使用Sarasa-Gothic替换Windows 10系统雅黑字体，整体上体验得到很大提升，但是发现由于数字宽度或者间距较大，造成某些位置显示残缺。如下图
![sa](https://user-images.githubusercontent.com/30799958/101280793-12205480-3806-11eb-8ae5-fe26254b2c7a.jpg)
![sa0](https://user-images.githubusercontent.com/30799958/101280795-13518180-3806-11eb-9a3f-36e1eee2f105.jpg)

使用苹方、San Francisco Pro Display字体替换没有发现这种情况，效果如下
![ps-display0](https://user-images.githubusercontent.com/30799958/101280850-7b07cc80-3806-11eb-9975-acfc7d5b0fa9.jpg)
![ps-display](https://user-images.githubusercontent.com/30799958/101280851-7cd19000-3806-11eb-99f4-50225f83cfb6.jpg)

**Comment by lychichem** [comment]
不能直接替换的，雅黑的UPM是2048，而更纱是1000，这样直接替换的话肯定会产生字形缩放问题的。至少也要把更纱黑体的UPM也调整成2048才行（不过都做了建议做全套，把所有字体信息做的和雅黑一样。当然，这就不是作者应该干的事而是提出问题的您应该做的事了）

**Comment by qazesz1** [comment]
> 不能直接替换的，雅黑的UPM是2048，而更纱是1000，这样直接替换的话肯定会产生字形缩放问题的。至少也要把更纱黑体的UPM也调整成2048才行（不过都做了建议做全套，把所有字体信息做的和雅黑一样。当然，这就不是作者应该干的事而是提出问题的您应该做的事了）

只替换sarasa的cmap表，和字体的一系列属性同时替换，两种我都做过，感官上没有差异。只替换cmap表反而还解决了win10锁屏日期中文加粗的bug，不知是何原理，如同时替换成雅黑的字体属性，这个bug也会保留下来。

数字间距的问题，我发现inter原版就有，希望集成到sarasa里面可以改进一下

**Comment by lychichem** [comment]
> > 不能直接替换的，雅黑的UPM是2048，而更纱是1000，这样直接替换的话肯定会产生字形缩放问题的。至少也要把更纱黑体的UPM也调整成2048才行（不过都做了建议做全套，把所有字体信息做的和雅黑一样。当然，这就不是作者应该干的事而是提出问题的您应该做的事了）
> 
> 只替换sarasa的name表，和字体的一系列属性同时替换，两种我都做过，感官上没有差异。只替换name表反而还解决了win10锁屏日期中文加粗的bug，不知是何原理，如同时替换成雅黑的字体属性，这个bug也会保留下来。
> 
> 数字间距的问题，我发现inter原版就有，希望集成到sarasa里面可以改进一下

不知道你系统缩放比例多少，总之我这里改了全套（UPM、ttf name表、字体名称、字族、OS/2表）之后100%缩放毫无问题。用otrebuild弄的。
![image](https://user-images.githubusercontent.com/9316590/102149491-8794c080-3ea9-11eb-96da-27c3322e329a.png)
![image](https://user-images.githubusercontent.com/9316590/102149540-ad21ca00-3ea9-11eb-849a-6b2e0cd2889b.png)

**Comment by 1024th** [comment]
> > 不能直接替换的，雅黑的UPM是2048，而更纱是1000，这样直接替换的话肯定会产生字形缩放问题的。至少也要把更纱黑体的UPM也调整成2048才行（不过都做了建议做全套，把所有字体信息做的和雅黑一样。当然，这就不是作者应该干的事而是提出问题的您应该做的事了）
> 
> 只替换sarasa的name表，和字体的一系列属性同时替换，两种我都做过，感官上没有差异。只替换name表反而还解决了win10锁屏日期中文加粗的bug，不知是何原理，如同时替换成雅黑的字体属性，这个bug也会保留下来。
> 
> 数字间距的问题，我发现inter原版就有，希望集成到sarasa里面可以改进一下

我也被数字间距的问题困扰许久。之前以为是 Inter 的问题，今天才发现 Inter 原版的数字间距是正常的，并没有更纱黑体中这么大。作者是不是做了改动？建议按照原版的间距制作字体。

**Comment by qazesz1** [comment]
> > 不能直接替换的，雅黑的UPM是2048，而更纱是1000，这样直接替换的话肯定会产生字形缩放问题的。至少也要把更纱黑体的UPM也调整成2048才行（不过都做了建议做全套，把所有字体信息做的和雅黑一样。当然，这就不是作者应该干的事而是提出问题的您应该做的事了）
> 
> 只替换sarasa的name表，和字体的一系列属性同时替换，两种我都做过，感官上没有差异。只替换name表反而还解决了win10锁屏日期中文加粗的bug，不知是何原理，如同时替换成雅黑的字体属性，这个bug也会保留下来。
> 
> 数字间距的问题，我发现inter原版就有，希望集成到sarasa里面可以改进一下

锁屏中文字体加粗的原因找到了，雅黑light OS/2表usWeightClass是290，标准的light字形应该是300，修改后即不再加粗。受影响的位置还有登录、注销、关机屏幕；设置应用右侧总标题
