### ISSUE TITLE
等距更纱黑体在特定字号下会出现中文中括号【】左右高低不平的现象

### ISSUE THREAD

**Issue by ilcpm** [be5invis/Sarasa-Gothic#211]
在过去的版本中，这个问题一直存在，昨天更新了最新版本之后，发现问题消失

但是在VSC中缩放代码的时候发现，该问题在一定的字号下会出现，而其他字号又正常

具体字体为：等距更纱黑体 Slab SC和等距更纱黑体 SC，其他字体未测试

![image](https://user-images.githubusercontent.com/36830343/101715674-da9bfb80-3ad6-11eb-9ff2-e04d1bd54f17.png)

这里左边的中括号最顶端比右边高，似乎要大一些

![image](https://user-images.githubusercontent.com/36830343/101715801-0b7c3080-3ad7-11eb-9657-d3da130c59f9.png)

 减小一级，两边一样大，高度相同

![image](https://user-images.githubusercontent.com/36830343/101715861-2d75b300-3ad7-11eb-8b32-8daceb9cfc3e.png)

 减小若干级之后，问题再次出现，左边比右边高

![image](https://user-images.githubusercontent.com/36830343/101716043-89d8d280-3ad7-11eb-86ff-81eee09c2ce9.png)

再减小一级，高度相同

![image](https://user-images.githubusercontent.com/36830343/101716175-bf7dbb80-3ad7-11eb-9eb2-5c6d7e3671e4.png)

如此，反复横跳，这里最明显

![image](https://user-images.githubusercontent.com/36830343/101716482-4c287980-3ad8-11eb-84f1-706205c70694.png)

Word中，粗略测试仅发现在“小二”字号在Word的缩放为100%时出现这个问题，若调整Word自身的页面缩放，相同字号下问题也会消失（页面比例放大缩小过程中，左右括号的相对高度一直在摆动），带Slab的衬线字体和不带的无衬线字体均有这个问题

---

忙着赶DDL，就不过多测试了

**Comment by ilcpm** [comment]
字体采用的ttf格式，安装完新版本的字体后尚未重启（不排除误报的可能性……）

**Comment by ilcpm** [comment]
手动更新一下……不会只有我一个人有这个问题吧

**Comment by tanukihee** [comment]
hinting问题，请在在issue列表里搜索hinting获取相关说明，并使用无hinting版本

**Comment by ilcpm** [comment]
> hinting问题，请在在issue列表里搜索hinting获取相关说明，并使用无hinting版本

更换新的无hinting字体之后问题解决，谢谢
