### ISSUE TITLE
How to make new fonts' filename not end with _0?

### ISSUE THREAD

**Issue by entr0pia** [be5invis/Sarasa-Gothic#213]
I install new fonts' file to upgrade the font from the old version. I click 'YES' while Windows asks me to replace the old files, but some of them are retained and new files are renamed to ending with '_0', '_1'... Why is this so? How to make new fonts' filename not end with _0?
![image](https://user-images.githubusercontent.com/30486766/102683970-9ebc1100-420f-11eb-8f56-86759a3418a0.png)

**Comment by be5invis** [comment]
Uninstall the existing fonts, restart PC, then delete the files (with name starting with `sarasa-`), and reinstall.
