### ISSUE TITLE
部分五笔字根无法显示

### ISSUE THREAD

**Issue by zongzixiaoer** [be5invis/Sarasa-Gothic#215]

![](https://tvax4.sinaimg.cn/large/005NLHW7ly1glwnwrcv9zj30c104wt8m.jpg)

**Comment by CyanoHao** [comment]
这几个字符是与 GBK 相关的遗留问题，建议在文字处理相关的领域始终使用面向 Unicode 的工具。

| GBK 编码 | 思源黑体及衍生字体所不支持的 PUA 映射 | Unicode | 字符 |
| --- | --- | --- | --- |
| FE 66 | U+E82B | U+9FB6 | 龶 |
| FE 71 | U+E836 | U+2EAE | ⺮ |
| FE 6E | U+E833 | U+2EAA | ⺪ |

“⺮” “⺪” 的映射早已在上世纪末发布的 GB 18030-2000 得到修正，多年以后的思源黑体自然从一开始就没想过要支持 PUA 映射。

“龶” 及其他少量字符的映射要等到 GB 18030 的下一次更新才会修正，Adobe 的博客文章 [To GB 18030, Or Not To GB 18030…](https://blogs.adobe.com/CCJKType/2015/03/to-gb18030.html) 阐述了现阶段不支持这些字符的 PUA 映射的理由。

**Comment by be5invis** [comment]
Closing as out of scope.

**Comment by zongzixiaoer** [comment]
感谢回复
