### ISSUE TITLE
绘图软件中，缩放含更纱黑体的图形特别卡，其他字体都没有问题

### ISSUE THREAD

**Issue by hsiungwang** [be5invis/Sarasa-Gothic#218]
使用CAD，EPLAN作工程绘图，非常需要这样的一款合适的等宽字体，而等距更纱黑体非常不错的字体。在将图形中所有文字改为“等距更纱黑体SLAB SC”后，缩放图形的时候就特别卡。体现在缩放操作上。更纱系列的中文字体都有相同的问题，其他字体都没有问题。感觉是字体渲染有问题？缩放特别卡特别卡，本来很流畅的缩放整成了慢动作。

**Comment by lychichem** [comment]
https://github.com/be5invis/Sarasa-Gothic/issues/208#issuecomment-751335970
可能和这个有关系。按这里的回复所说，因为做了全字号渲染优化，所以缩放速度会受影响

**Comment by be5invis** [comment]
Sarasa _intensively_ uses TT hints to maximize clarity — so a badly implemented rasterizer may become slow when scaling them. Perhaps an unhinted edition in the future...

**Comment by hsiungwang** [comment]
unhinted edition? I am very much looking forward to such a version. If it is released, it will be a blessing to engineering draftsmen.

**Comment by be5invis** [comment]
Unhinted edition has released. Closing.

**Comment by asmwarrior** [comment]
> Sarasa _intensively_ uses TT hints to maximize clarity — so a badly implemented rasterizer may become slow when scaling them. Perhaps an unhinted edition in the future...

Hi, [be5invis](https://github.com/be5invis), can you explain what does the "badly implemented rasterizer" mean?

I noticed that the Sarasa-Gothic font(the monospace version) make the editor very slow(for example, I try to scroll the editor) in the [Code::Blocks - Code::Blocks](http://www.codeblocks.org/) IDE. (I'm one of the Code::Blocks developer), but I don't know much about the font rendering. Code::Blocks use a [Scintilla](https://www.scintilla.org/) editor control and the rendering engine is the [wxWidgets: Cross-Platform GUI Library](https://www.wxwidgets.org/)library.

While, if I use the unhinted version of the Sarasa-Gothic font, the render in Code::Blocks works really fast.

Can you give some direction about how to fix this issue? Thanks.
