### ISSUE TITLE
Windows 商店的更纱黑体版本陈旧

### ISSUE THREAD

**Issue by ZeppLu** [be5invis/Sarasa-Gothic#220]
https://www.microsoft.com/store/productId/9MW0M424NCZ7 许久没更新过了，版本还停留在 0.12，希望能维护一下。其他人的使用情况我不清楚，但就个人而言，这种时不时有更新的字体装在系统目录下的话，更新起来太费劲了，相比之下商店的版本使用起来就省心很多。

**Comment by tanukihee** [comment]
See #176

**Comment by win98se** [comment]
@taoyouh @ZhaobangChina

**Comment by taoyouh** [comment]
> @taoyouh @ZhaobangChina

Updated
