### ISSUE TITLE
是不是太分裂了，解压之后480个文件

### ISSUE THREAD

**Issue by Just4Learning** [be5invis/Sarasa-Gothic#222]
下载了sarasa-gothic-ttf-0.17.0.7z，解压之后480个文件。那么问题来了，我按照哪些呢？不会是所有都安装吧？？各种不同的命名的文件之间的区别是什么？？？

**Comment by CrotchBurnt** [comment]
看着嫌多就下TTC的

**Comment by Downstream1998** [comment]
请阅读项目的 README

另外，你可以选择下载 ttc 归档

**Comment by PNBRQK** [comment]
Win7 不支持TTC，只能用TTF，这是没办法的事。
可以选择只装其中一部分。
Linux就支持TTC了
