### ISSUE TITLE
matlab无法使用等距更纱字体

### ISSUE THREAD

**Issue by hustarbor** [be5invis/Sarasa-Gothic#23]
我也不知道为啥，等距更纱字体在其他地方都用的好好地，唯独MATLAB2017b不可以，系统是win10 1709 16299.309 。
![snipaste_2018-03-31_19-21-35](https://user-images.githubusercontent.com/34189831/38162721-1e01849c-3519-11e8-80bf-02ece6c5b1ca.png)
![snipaste_2018-03-31_19-21-12](https://user-images.githubusercontent.com/34189831/38162722-218b8806-3519-11e8-9d43-aeae9eca77bd.png)

**Comment by be5invis** [comment]
Have you tried the TTF version?

**Comment by hustarbor** [comment]
TTF 版本我试了一下，还是那个样子。而且我发现不同的字形还不一样
![snipaste_2018-04-01_15-49-43](https://user-images.githubusercontent.com/34189831/38171062-529552a0-35c4-11e8-86c0-1ee635849c0d.png)

**Comment by hustarbor** [comment]
现在已经正常了。
我在删除ttf版本的时候显示正在使用极其难删，重启也没门（系统默认字体是微软雅黑）。最后靠着火绒安全的文件粉碎功能删掉了。
重启后，又安装了TTC版本的，然后就好了

**Comment by kkren** [comment]
同样遇到了这个乱码，直接重启就解决了
