### ISSUE TITLE
本字体对Variable字体是否有计划？

### ISSUE THREAD

**Issue by lychichem** [be5invis/Sarasa-Gothic#234]
按照https://github.com/adobe-fonts/source-han-sans/releases/tag/2.003R 的描述，Adobe方面已经将思源黑体全给整成Variable了，尽管有一点性能问题（Indesign上使用full Pan-CJK），不知道大佬准备怎么看这个风向

**Comment by be5invis** [comment]
No plan for VF (since Iosevka's parametric system is too strong for OtVar).
