### ISSUE TITLE
字体在notepad.EXE中的显示问题

### ISSUE THREAD

**Issue by LCZSQ** [be5invis/Sarasa-Gothic#235]
在记事本中”!=“会显示为”≠“，真的是别扭死了。

**Comment by CrotchBurnt** [comment]
你可以先看README再使用的

**Comment by stone-zeng** [comment]
请使用 Sarasa Fixed

**Comment by LCZSQ** [comment]
抱歉，我下载的是sarasa-gothic-ttf-0.30.0.7z，使用的是sarasa-mono-sc-regular.ttf，压缩包内既没有README，也没有带”Fixed“的文件，本项目下的Readme.md也阅读过了，并没有说记事本使用sarasa字体有什么特殊要求。

**Comment by LCZSQ** [comment]
可在ultraedit中”!=“仍显示为”!=“

**Comment by be5invis** [comment]
Notepad enables CALT ligature, and using _Sarasa Fixed SC_ could fix this.
For other editors, please find options to control ligatures.
Closing as by design.
