### ISSUE TITLE
the arrow ligatures(dash/greath-than-symbol) is not so accurate

### ISSUE THREAD

**Issue by xiongdahu** [be5invis/Sarasa-Gothic#24]
H'm,the vertical height between - and > has some problem when use in JetBrain's IDE

![2018-04-05_002611](https://user-images.githubusercontent.com/24514012/38320846-4a135388-3868-11e8-9ac5-17e9eeeb854b.png)

**Comment by xiongdahu** [comment]
can I build a version without ligatures?

**Comment by be5invis** [comment]
There's a `Sarasa Term`, not including ligation.
Also this issue is caused by TTFAutohint :/
