### ISSUE TITLE
英文字太窄了

### ISSUE THREAD

**Issue by wonderkismet** [be5invis/Sarasa-Gothic#240]
有没有英文宽度合适的类型呢？？

**Comment by redchenjs** [comment]
习惯就好

**Comment by be5invis** [comment]
For mono, this is a design feature that all LGC chars are exactly 1/2em wide.
Closing.

**Comment by Prcuvu** [comment]
> 有没有英文宽度合适的类型呢？？

请定义“英文宽度合适”，比如发个截图或者手绘图辅助说明怎样的宽度是符合你喜好的。
