### ISSUE TITLE
Hinting quality issues of Chinese characters in recent versions

### ISSUE THREAD

**Issue by bodayw** [be5invis/Sarasa-Gothic#243]
It looks like there was a major hinting parameter change in recent releases (possibly during the last few months - not sure since last time I update my installation was months ago).

On a few occasions I have noticed characters with obvious missing strokes in certain font size, rendered them unrecognizable, notably:

慰 at 9 points
劇 at 9 points

I don't think I've seen these issues before, so possibly a regression.

**Comment by be5invis** [comment]
Fixed in upstream. The next release should have it fixed.
Closed.
