### ISSUE TITLE
有什么办法自己调 行间距和 字间距么 ？

### ISSUE THREAD

**Issue by wonderkismet** [be5invis/Sarasa-Gothic#244]
想英文有extended效果，

中文间距也响应扩大。

行距调小。

该如何设置自己build出这样的呢？
谢谢大大。

**Comment by Puxirepublic** [comment]
这个是字表的工作。

用 [ttx](https://github.com/fonttools/fonttools) 导出要改的字体字表，`ttx -t OS/2 字体.ttf` 这样。间距和行高总共在两个表里，一个是全局表，一个是 Windows 专属的 OS/2 表，两个表里搜 width 和 height 之类的关键词——具体名称在文档里或网上搜一下，改好后再导回进字体 `ttx -b -m 字体.ttf 修改过的字表.ttx`。
