### ISSUE TITLE
更纱黑体对Emoji Keycap Sequence处理不正确

### ISSUE THREAD

**Issue by lychichem** [be5invis/Sarasa-Gothic#248]
![image](https://user-images.githubusercontent.com/9316590/123190588-66550280-d4d2-11eb-8b33-a37bf0c136c8.png)

如图，chrome标题栏用的是segoe UI，可以正确显示，浏览器设置标准字体和无衬线体为更纱黑体SC之后至少在google搜索框这里无法正确显示1️⃣。相关资料见https://emojipedia.org/emoji-keycap-sequence/

**Comment by be5invis** [comment]
Sarasa is NOT an Emoji font. So this issue is out of scope.
Resolve as out of scope.
