### ISSUE TITLE
中文'不'字符高度显示较矮

### ISSUE THREAD

**Issue by yangzichun** [be5invis/Sarasa-Gothic#25]
看起来比较像和小写英文一个高度了。
![tim 20180409142020](https://user-images.githubusercontent.com/22728919/38482424-d53d9ae4-3c01-11e8-8737-82a350ce2dce.png)

**Comment by be5invis** [comment]
Belongs to IDH.
Would be tried to fix in next version.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yangzichun <notifications@github.com>
发送时间: Monday, April 9, 2018 2:25:24 PM
收件人: be5invis/Sarasa-Gothic
抄送: Subscribed
主题: [be5invis/Sarasa-Gothic] 中文'不'字符高度显示较矮 (#25)


看起来比较像和小写英文一个高度了。
[tim 20180409142020]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22728919%2F38482424-d53d9ae4-3c01-11e8-8737-82a350ce2dce.png&data=02%7C01%7C%7C0d1e0a4111b9495e9b8608d59de2baed%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636588519479466514&sdata=qiX%2FMayeF6p0lTmOoCRa5i0Czrrim7Uq%2FwXnY%2F3pamw%3D&reserved=0>

―

**Comment by be5invis** [comment]
Fixed in 0.5.3.
