### ISSUE TITLE
为何单个ttf的体积如此之大？

### ISSUE THREAD

**Issue by SekiBetu** [be5invis/Sarasa-Gothic#255]
sarasa-mono-slab-sc-regular.ttf 达到了25m，超越了99%的别的字体

**Comment by Heptazhou** [comment]
# 为何单个太阳的体积如此之大？

<br />

Sol 达到了1.4e18km³，超越了99%的别的太阳系天体

**Comment by be5invis** [comment]
It supports a lot of characters so it is large.
Closing.

**Comment by SekiBetu** [comment]
> # 为何单个太阳的体积如此之大？
> 
> Sol 达到了1.4e18km³，超越了99%的别的太阳系天体

太大了不适合网络传输，开发网页的话估计用不了这字体了😕

**Comment by stone-zeng** [comment]
CJK 字体本身字符数量大，文件大小往往也都比较夸张。网页使用可以考虑子集化以及用 woff/woff2 格式压缩一遍。

**Comment by Heptazhou** [comment]
woff2 只有 5M 多

网页用 ttf 然后嫌大 这就离谱😅
