### ISSUE TITLE
「Ⅱ」 displayed as blank for 等距更紗黑體 TC size 12 in Sarasa-Gothic 0.34.1

### ISSUE THREAD

**Issue by SUCM** [be5invis/Sarasa-Gothic#260]
OS is Win 10 x64. not sure if it matters

**Comment by SUCM** [comment]
also tried a few larger font sizes, but all displayed as blank character

**Comment by be5invis** [comment]
Roman numbers are not supported in Sarasa I think.

**Comment by SUCM** [comment]
Source-Han-S* fonts and 更紗黑體 TC all displayed the character properly, so I didn't expect 等距更紗黑體 TC to not support it

**Comment by be5invis** [comment]
Well, Iosevka doesn't have it so it is not supported :(. It is considered European so not coming from SHS.

**Comment by SUCM** [comment]
well, that's unfortunate. this breaks for coding. is it possible to inherit these characters from Source Han Sans?
