### ISSUE TITLE
更纱黑体在 KDE 的 Konsole / Yakuake 中未被识别为等宽字体

### ISSUE THREAD

**Issue by SpecterShell** [be5invis/Sarasa-Gothic#261]
在未勾选“显示所有字体”（仅显示等宽字体）时，字体列表内没有更纱黑体。
![图片](https://user-images.githubusercontent.com/56779163/135701001-7e0ab8a9-9528-424d-bffa-405d6f250309.png)
![图片](https://user-images.githubusercontent.com/56779163/135701018-482a2dd0-9909-4f48-bd03-f1947cfb05d2.png)

**Comment by be5invis** [comment]
It is impossible to make Sarasa Gothic as FontConfig Monospace since, well, ideographs are indeed wider than other letters.
