### ISSUE TITLE
版本号不一致与翻车的破折号

### ISSUE THREAD

**Issue by Yave-Yu** [be5invis/Sarasa-Gothic#269]
我在 Release 处下载的 `sarasa-gothic-ttf-0.35.0.7z`，但我看了下里面的 `sarasa-gothic-sc`，版本号竟还是 0.34.7？另外无论是旧版还是新版，破折号没法正常使用，第二个字符总会变成五条粗杠，如图所示：
![破折号崩了](https://user-images.githubusercontent.com/54294476/142713250-bdc25322-435c-4f71-ab52-16fdbf22c967.png)

**Comment by pffang** [comment]
我用了相同版本,我发现版本号问题是因为旧字体没删除干净.
如果你用Windows 10, C:\Windows\Fonts和C:\Users\UserName\AppData\Local\Microsoft\Windows\Fonts下面都要检查一下,全删了重启之后重新安装字体.
