### ISSUE TITLE
firefox serif字体应该怎么设置？

### ISSUE THREAD

**Issue by offferu** [be5invis/Sarasa-Gothic#270]
4k屏，效果像手机一样
但请教下serif字体应该设置成什么？多谢！

<img src="https://i.ibb.co/k6td1XD/serif.png">

<img src="https://i.postimg.cc/WsZF2cD0/image.png">

**Comment by Measureless** [comment]
思源宋体呗

**Comment by offferu** [comment]
> 思源宋体呗

完整的字体名是什么？

**Comment by Measureless** [comment]
> > 思源宋体呗
> 
> 完整的字体名是什么？

https://github.com/adobe-fonts/source-han-serif

**Comment by offferu** [comment]
> > > 思源宋体呗
> > 
> > 
> > 完整的字体名是什么？
> 
> https://github.com/adobe-fonts/source-han-serif

多谢！已装上
