### ISSUE TITLE
Excel编辑时显示有问题

### ISSUE THREAD

**Issue by NightSharp** [be5invis/Sarasa-Gothic#271]
在Excel表格编辑框中设定
***默认***
字体为Mono Slab SC

输入内容时中文挤在一块，和英文宽度一致，无法正常查看
![屏幕截图 2021-12-08 155056](https://user-images.githubusercontent.com/9748063/145169561-d57d529a-3b53-4005-a6a4-4a4bcd46926e.png)
输入完回车后正常
![屏幕截图 2021-12-08 155111](https://user-images.githubusercontent.com/9748063/145169591-c833907a-1727-407a-8a03-3b08911c3389.png)

**Comment by NightSharp** [comment]
这个能够解决不~

**Comment by lanzhiquan** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/11311878/163578140-24b16824-3d5d-4db1-a86d-f4d2728da020.png">
这个问题有点奇怪，编辑栏选中的情况才会有这个问题。

**Comment by be5invis** [comment]
May be related with TTC support. Have you tried the TTF version?

**Comment by NightSharp** [comment]
> May be related with TTC support. Have you tried the TTF version?

It seems that TTF version is right.
But it's too occupied

**Comment by be5invis** [comment]
@NightSharp You can select the subfamilies you need and install these only.
I may change the way the TTC is created in the future to avoid similar issues -- with the cost of increased file size though.
