### ISSUE TITLE
Font ligatures can not be displayed correctly in Kitty

### ISSUE THREAD

**Issue by amnore** [be5invis/Sarasa-Gothic#272]
I encountered the same problem as in kovidgoyal/kitty#3928, in which the font ligatures can not be displayed correctly in Kitty. However, from be5invis/Iosevka#1007, it seems that the underlying problem is fixed, and when I changed terminal font to Iosevka, ligature did work.

So I guess there is a problem in the building process of Sarasa Gothic? Sorry I am not able to debug it myself because I have little knowledge in fonts.

I am using version 0.35.2 of Sarasa Gothic, v11.2.0 of Iosevka, and v0.23.1 of Kitty on Arch.

**Comment by be5invis** [comment]
Sarasa does not support Kitty's ligatures because, well, it doesn't have glyph names at all. Adding name data is almost impossible in the current workflow.

**Comment by be5invis** [comment]
One option is to use Kitty’s [Symbol Map](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map) to map all CJK characters to Sarasa and leave everything using Iosevka.

**Comment by amnore** [comment]
Well, after trying Iosevka I found that it seems to work well with my default Chinese font. The characters are still aligned. I think I'm happy leaving my config this way then.
