### ISSUE TITLE
character variants can't bet set with CSS from 0.30.0 anymore

### ISSUE THREAD

**Issue by tao-cumplido** [be5invis/Sarasa-Gothic#274]
I tried to upgrade from 0.21.0 but noticed that specifying character variants via `font-feature-settings` doesn't work anymore for the bundled Iosevka fonts. The problem doesn't occur with Iosevka standalone fonts. The first broken version seems to be 0.30.0.

**Comment by be5invis** [comment]
This is by design. Otherwise glyph count will overflow (A font can only has 64K or less glyphs).
Resolve as by design.
