### ISSUE TITLE
更纱黑体有衬线体吗？

### ISSUE THREAD

**Issue by xiaorong61** [be5invis/Sarasa-Gothic#275]
我打算把更纱黑体设为浏览器字体，而浏览器字体设置有四种（默认、非衬线、衬线、等宽），不知道衬线那个如何设置。

**Comment by stone-zeng** [comment]
Sarasa UI

**Comment by xiaorong61** [comment]
> Sarasa Gothic/UI 都是

我对衬线的理解是宋体那种的，而非衬线是微软雅黑那种的。

Sarasa Gothic/UI 是非衬线(sans-serif)吧

**Comment by elsesky** [comment]
一个图说明。



***@***.***
 
发件人： xiaorong61
发送时间： 2022-01-21 15:17
收件人： be5invis/Sarasa-Gothic
抄送： Subscribed
主题： Re: [be5invis/Sarasa-Gothic] 更纱黑体有衬线体吗？ (Issue #275)
Sarasa Gothic/UI 都是
我对衬线的理解是宋体那种的，而非衬线是微软雅黑那种的。
Sarasa Gothic/UI 是非衬线(sans-serif)吧
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stone-zeng** [comment]
是我傻了🤦‍♂️……衬线体并没有

**Comment by Neubulae** [comment]
更纱宋体是吧（（（

**Comment by ocian** [comment]
Slab 的英文是有衬线的字体，中文是咩有衬线的字体，可以把 Slab 的中文字体更换成 Source han serif 吗（这个要求看起来工作量巨大，被忽视是不是很合理）

**Comment by ocian** [comment]
![image](https://user-images.githubusercontent.com/18749280/152738951-9a001d66-7982-4223-80b8-4520089dd120.png)
