### ISSUE TITLE
`*` for coding

### ISSUE THREAD

**Issue by shenghui0779** [be5invis/Sarasa-Gothic#278]
- Jetbrains Mono
![image](https://user-images.githubusercontent.com/67535398/154182262-beacfcc0-e78f-4eb7-997c-501c45159547.png)

- Sarasa Mono
![image](https://user-images.githubusercontent.com/67535398/154182056-f22be9a2-dea9-447a-b6b0-f8470b92ec9e.png)

**Comment by shenghui0779** [comment]
That's great ! Thanks !

**Comment by nightire** [comment]
> That's great ! Thanks !

有点细节需要更新，我发现在 vscode 里用 等距更纱黑体 SC 会导致 terminal 里的汉字乱码，不是肯定会乱码但会有机会出现。因此我把字体设置改成：

```
"editor.fontFamily": "'Iosevka SS14', 'Sarasa Term SC'"
```

这样就没问题了，后面的也可以换成 Sarasa Fixed SC，区别就是 Term 支持 ligatures 而 Fixed 不支持，这就看个人偏好了。
