### ISSUE TITLE
Lose the top half of bracket in svg tag.

### ISSUE THREAD

**Issue by MisLink** [be5invis/Sarasa-Gothic#28]
I use a vscode extension named [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) to colorize bracket. 
Recently it add a feature that can show bracket in gutter, but it looks lose the top half.
![image](https://user-images.githubusercontent.com/8280169/38802000-e458feb4-419d-11e8-8504-c50738a67db6.png)
parentheses and curly brackets have same issue.

[Here](https://github.com/CoenraadS/BracketPair/blob/dfd85a9a3e6c0b4d6ba4b271f7998370996974db/src/gutterIconManager.ts#L41) is code in the extension that render bracket in gutter.
It use a svg tag like:
```html
<svg xmlns="http://www.w3.org/2000/svg" height="10" width="10">
    <text x="50%" y="50%" fill="green" font-family="Sarasa Mono SC" font-size="10" text-anchor="middle" dominant-baseline="middle">{</text>
</svg>
```

**Comment by be5invis** [comment]
I think you should open a bug to them since they may mis-calculated the line height.

**Comment by MisLink** [comment]
You are right. I try to increase height then all show up.
