### ISSUE TITLE
解压以后有10g 400多个文件，这些都要安装吗？

### ISSUE THREAD

**Issue by SadSock** [be5invis/Sarasa-Gothic#280]
硬盘容量扛不住了

**Comment by qq910438219** [comment]
找个自己喜欢的字体风格,  其他的都可以删掉

**Comment by lietxia** [comment]
只安装TTC的就好了

**Comment by entr0pia** [comment]
看语种, 按 ```sc, hc, j, k, cl``` 选择, ```slab``` 字型也可以不要

**Comment by offferu** [comment]
> 只安装TTC的就好了

Windows是不是要下载ttf的？

**Comment by lietxia** [comment]
> > 只安装TTC的就好了
> 
> Windows是不是要下载ttf的？
安装 .ttc 的就行了
