### ISSUE TITLE
汉字是横过来的，这是什么情况？

### ISSUE THREAD

**Issue by SadSock** [be5invis/Sarasa-Gothic#281]
<img width="683" alt="截屏2022-03-11 下午7 28 50" src="https://user-images.githubusercontent.com/7643216/157858726-7339b3d5-cee5-46bb-9bda-e1394591cb4c.png">

**Comment by lxgw** [comment]
可能设置了带前缀 `@` 的字体了

**Comment by SadSock** [comment]
果然是这样
