### ISSUE TITLE
网页没有正确使用浏览器和系统设置的Sarasa SC字形而Fallback成了CL

### ISSUE THREAD

**Issue by sky96111** [be5invis/Sarasa-Gothic#283]
除了使用TTF版删除其他字形，有其他设置优先级的方法吗？
这个问题大概是和字体无关，只是网上有关CJK字形的资料太少了，如果不合适请Close这个issue
谢谢了
[![LtbB1U.png](https://s1.ax1x.com/2022/04/17/LtbB1U.png)](https://imgtu.com/i/LtbB1U)
[![LtbDcF.png](https://s1.ax1x.com/2022/04/17/LtbDcF.png)](https://imgtu.com/i/LtbDcF)

**Comment by CyanoHao** [comment]
是否只设置了简体中文的字体？检查一下 `about:config` 里面的 `font.name.sans-serif.x-western`（用户设置的西文无衬线体）。

![image](https://user-images.githubusercontent.com/14287996/163693452-8aab7712-6fe9-4488-a1db-61ff4a3700d8.png)

GitHub 网页声明了语言为英语 `<html lang="en">`，CSS 没有指定 CJK 字体。Firefox 就会按照 `font.name.sans-serif.x-western`，`font.name-list.sans-serif.x-western`，系统默认 sans-serif 的顺序进行 fallback。

把西文字体也设置成 ”Sarasa UI SC“，或者手动调整 `font.name-list.sans-serif.x-western` 中的 fallback 顺序，就可以得到正确的字形。

<hr>

根据实际的 fallback 顺序，我推测是 Linux 系统。如果是这样，可以通过 fontconfig 干预系统全局的 sans-serif 设置。

例如设为 Inter + Sarasa Gothic SC，修改 `~/.fonts.conf`：
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="pattern">
  <test name="family" qual="any">
   <string>sans-serif</string>
  </test>
  <edit name="family" mode="prepend" binding="strong">
   <string>Inter</string>
   <string>Sarasa Gothic SC</string>
  </edit>
 </match>
</fontconfig>
```

**Comment by sky96111** [comment]
谢谢，有效
