### ISSUE TITLE
U+2026 Horizontal Ellipsis should be vertically centered within the text height.

### ISSUE THREAD

**Issue by Hackgets** [be5invis/Sarasa-Gothic#285]
See [W3C Requirements for Japanese Text Layout](https://www.w3.org/TR/jlreq/#basics_of_japanese_composition)

In open source projects, it is unavoidable that Japanese language support is lacking. This is because there are few Japanese contributors, and I am ashamed of that.

**Comment by be5invis** [comment]
It is centered in Sarasa Gothic J. For Mono since it is mostly used for coding, I left it lowered to be harmonized with Latins.
Resolve as by design.
