### ISSUE TITLE
Horizontal ellipsis (U+2026) rendered as full-width

### ISSUE THREAD

**Issue by tiosgz** [be5invis/Sarasa-Gothic#289]
In particular, i use Sarasa Term CL. This is how it looks in a terminal and in a web browser:

![in a terminal](https://user-images.githubusercontent.com/53824308/170552461-5caae80e-77cb-44dc-9c6b-0effa64450a0.png)
![in a web browser](https://user-images.githubusercontent.com/53824308/170552647-4dcd5fd8-6f25-4107-8bd5-36036421ec89.png)

Am i missing something?

(This is with the Arch Linux `ttf-sarasa-gothic` package.)

**Comment by be5invis** [comment]
Fixed

**Comment by tiosgz** [comment]
Thank you ❤
