### ISSUE TITLE
sarasa-bolditalic.ttc 非有效字体文件.

### ISSUE THREAD

**Issue by extrame911** [be5invis/Sarasa-Gothic#29]
Win10 LTSB 14393

使用字体版本:sarasa-gothic-ttc-0.5.1.7z/sarasa-gothic-ttc-0.5.2.7z

产生问题: 提示sarasa-bolditalic.ttc为非有效字体文件. Windows中无对应的粗斜体. 标准/粗体/斜体正常.

![default](https://user-images.githubusercontent.com/7876532/38853452-db35396c-424f-11e8-9cf8-520cd5e2c52f.png)

**Comment by be5invis** [comment]
Try install the TTF version

**Comment by extrame911** [comment]
TTF 版本无此问题

**Comment by be5invis** [comment]
Older Windows does not support the TTC since it has too many sub-fonts.
Closed.
