### ISSUE TITLE
`《》`(u+300A, u+300B)display with wrong direction in ttf version 

### ISSUE THREAD

**Issue by yyjdelete** [be5invis/Sarasa-Gothic#291]
test with `sarasa-gothic-ttf-0.36.4`, for some unknown reason, it works well in ttc version, and not happen in font preview in win10.
`《书名号》`

sarasa-mono-sc-regular
![image](https://user-images.githubusercontent.com/1819074/171348527-407fc85a-e8ec-444b-9c31-bfd494bd5bb8.png)
sarasa-mono-slab-sc-regular
![image](https://user-images.githubusercontent.com/1819074/171348656-964b3ffc-cd5c-431d-bd7a-c99485e131ea.png)

And it works well when you try to select the line.
![image](https://user-images.githubusercontent.com/1819074/171350808-9756dce1-e493-4a80-a86c-a6f5864202d8.png)

**Comment by dantezhu** [comment]
yes, and same problem as:
```
【】「」
```

will be render like this:

![image](https://user-images.githubusercontent.com/1105212/171648038-508af703-eb98-4583-86fa-fe66c7a10f97.png)

**Comment by taroxd** [comment]
The same problems occurs when I use  sarasa-gothic-ttf-0.36.4 with Sublime Text 4. It is rendered correctly in Microsoft Word.

**Comment by Leoongithub** [comment]
Same problem in latest version (0.36.5). The last version without this bug is 0.36.2.

**Comment by taroxd** [comment]
Is this issue resolved?
