### ISSUE TITLE
Sarasa-Gothic not able to detect on kitty terminal

### ISSUE THREAD

**Issue by ps-143** [be5invis/Sarasa-Gothic#292]
When trying to use the font with the kitty terminal, not able to detect the font with `kitty +list-fonts --psnames`.

All the other fonts are listed.

OS: Fedora 36

Tried the solution mentioned in #192, but it didn't resolve the issue.

Thanks for any help and really appreciate the font.

**Comment by CyanoHao** [comment]
These glyphs break fontconfig's spacing again:
- U+302E, U+302F: 250 (Hanguel tone marks)
- vertical substitution glyphs of U+302E, U+302F: 920
- (unused) localized substitution glyphs of U+30FB: 340 (Katakana middle dot)
- U+31B4, U+31B5, U+31B6, U+31B7, U+31BB: 600 (Bopomofo final letters)
- U+1F12F, U+1F16A, U+1F16B, U+1F16C: variadic (alphanumeric symbols)

Seems to be a regression of https://github.com/be5invis/Sarasa-Gothic/commit/c3feee48ca6cdbddac4e81068fc62916ffe77c4f, which introduced the “Far East miscellaneous symbols” kind.

**Comment by ps-143** [comment]
> These glyphs break fontconfig's spacing again:
> 
> * U+302E, U+302F: 250 (Hanguel tone marks)
> * vertical substitution glyphs of U+302E, U+302F: 920
> * (unused) localized substitution glyph of U+30FB: 340 (Katakana middle dot)
> * U+31B4, U+31B5, U+31B6, U+31B7, U+31BB: 600 (Bopomofo final letters)
> * U+1F12F, U+1F16A, U+1F16B, U+1F16C: variadic (alphanumeric symbols)
> 
> Seems to be a regression of [c3feee4](https://github.com/be5invis/Sarasa-Gothic/commit/c3feee48ca6cdbddac4e81068fc62916ffe77c4f), which introduced the “Far East miscellaneous symbols” kind.

Do you know any fix for this?
