### ISSUE TITLE
小写的字母 "l" 与数字“1” 太像了

### ISSUE THREAD

**Issue by newsdos** [be5invis/Sarasa-Gothic#295]
我用的是sarasa-mono-sc，小写的字母 "l" 与数字“1” 太像了

**Comment by CarterLi** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/6134068/186347631-efa5417b-bcd2-4276-973b-60f0ad10ddd4.png">
这个怎么会像呢？

**Comment by xysztm** [comment]
他应该是指小写的“L”和数字“1”
不过mono-sc应该也能分清楚，数字“1”没有“底线”
但是我猜他用的其实是mono-slab-sc，这里的就很像了，如图：
![屏幕截图 2022-09-12 173255](https://user-images.githubusercontent.com/34204848/189621527-53c7bfa7-2022-4fe5-88e5-f9bed8307336.png)

**Comment by Vlastbia** [comment]
![image](https://github.com/be5invis/Sarasa-Gothic/assets/3411969/ef69f293-6161-4cdc-a4a8-f4a71ade44de)
