### ISSUE TITLE
竖排文本标点符号

### ISSUE THREAD

**Issue by Kompl3xpr** [be5invis/Sarasa-Gothic#296]
当横排中文文本转为竖排时，①逗号、句号、顿号等应该位于右上方；②省略号、破折号、冒号、分号等应该居中；③各类括号和直角引号需要转置。但是使用 CSS 样式在网页显示竖排文本时，Sarasa Gothic CL 并不满足①③，至于其他字体尚未确认。

![Screenshot 2022-08-04 213134](https://user-images.githubusercontent.com/109941110/182859573-1eab289f-65f5-4eb1-b4b3-1d2871f9ddc2.png)

**Comment by Murasame233** [comment]
> 

请问你还在么

**Comment by be5invis** [comment]
I think those have been fixed in recent versions.
