### ISSUE TITLE
full-width punctuations are not displayed under Direct2D (occasionally) on Windows 7

### ISSUE THREAD

**Issue by PNBRQK** [be5invis/Sarasa-Gothic#298]
Scintilla-based text editors (e.g. SciTE) offer options for rendering text on Windows. The two main options are Direct2D and traditional GDI. When adopting D2D on Win7, there are chances the full-width punctuations (e.g. ，。；) show as blanks. Switch to GDI and everything is displayed fine.

this problem does not always occur; it only manifests itself for particular font versions, 0.37.0 is one of them.
![D2D](https://user-images.githubusercontent.com/9943990/188333646-34e1174d-a863-4e36-a085-131e9862f9ac.png)
![GDI](https://user-images.githubusercontent.com/9943990/188333649-4c15b8b5-3bc3-466a-8261-1bf63d6cd9e8.png)

BTW: This is the TTF edition, for Win7 does not support TTC at all

**Comment by PNBRQK** [comment]
push up

**Comment by PNBRQK** [comment]
the problem remains in v0.38.0.

**Comment by PNBRQK** [comment]
The solution is going back to v0.32.14 for Win7.
Closing.

**Comment by kevinlau2015** [comment]
the problem is remain in "v0.32.14 sarasa-ui-sc-light.ttf" for win7 x64

**Comment by PNBRQK** [comment]
> the problem is remain in "v0.32.14 sarasa-ui-sc-light.ttf" for win7 x64

  Yeah maybe, but the maintainer didn't seem to care about this issue in its three-month open period.
