### ISSUE TITLE
制表符和文字的宽度不一样

### ISSUE THREAD

**Issue by kylin30** [be5invis/Sarasa-Gothic#30]
![qq 20180424193641](https://user-images.githubusercontent.com/2984908/39184662-d50a433c-47f6-11e8-9659-6d02ab968dcd.png)

**Comment by be5invis** [comment]
Box drawing glyphs are designed to be half-width since Sarasa is **not** designed to be compatible with legacy CJK monospace fonts.
Also
"这是五个汉字" — No, it's six.
