### ISSUE TITLE
Character "~" in Fixed and Term is empty in 0.37.2.

### ISSUE THREAD

**Issue by Parollel** [be5invis/Sarasa-Gothic#301]
This is how Mono font looks like in my alacritty.
[Screenshot](https://pasteboard.co/xdoTJQ9PSLN7.png)
This is how Fixed and Term font looks like in my alacritty.
[Screenshot](https://pasteboard.co/IyUdQU4PUQYL.png)

**Comment by be5invis** [comment]
Fixed in 0.37.3.
