### ISSUE TITLE
question: font rendering speed different between sarasa-gothic-ttf-0.8.2 and the latest 0.37.4

### ISSUE THREAD

**Issue by asmwarrior** [be5invis/Sarasa-Gothic#305]
Hi, I just test several versions of the sarasa-gothic-ttf font release under Code::Blocks IDE under Win7 64bit, which renders the font in normal GDI mode.

The `sarasa-gothic-ttf-0.8.2` version(released in year 2019), such as: sarasa-mono-sc-regular.ttf, the editor renders very fast
The latest release `sarasa-gothic-ttf-0.37.4` with hinting version, the editor renders very slow, I can see the whole page get updated when I scroll the page. Though the un-hinted version renders fast, but the font shows badly because some lines of the font may be too trick.
I choose another version such as: `sarasa-gothic-ttf-0.16.5`(released around year 2021), it also renders very slow.

My question is: 
What is the different between those release? I don't see much change logs of each release, but only a git tag about the version number.

The size of the font is also different, for example, the `0.8.2` version of `sarasa-mono-sc-regular` is about 34M, while the latest `0.37.4` release this same file is about 23M, so why the `ttf` size is smaller, but the render time get longer?

Thanks.

**Comment by asmwarrior** [comment]
Another quesition is:

in the 0.8.2 release, there are two files named `sarasa-monoT-sc-regular.ttf` and `sarasa-mono-sc-regular.ttf`. While in the latest release, there is only one file named `sarasa-mono-sc-regular.ttf`. So, what is the difference between `mono` and `monoT`, thanks.

**Comment by asmwarrior** [comment]
I think this is not stale, the issue just not get comment for about several days.

**Comment by asmwarrior** [comment]
I think this is not stale, the issue just not get comment for about several days.

**Comment by be5invis** [comment]
I think one difference is that the newer versions use a more complex embedded instructions to reduce the size. As a result, it may take more time for glyphs' first rendering.

Resolve as by design.

**Comment by asmwarrior** [comment]
> I think one difference is that the newer versions use a more complex embedded instructions to reduce the size. As a result, it may take more time for glyphs' first rendering.
> 
> Resolve as by design.

Hi, [be5invis](https://github.com/be5invis), thanks for the explanation.
