### ISSUE TITLE
Which Iosevka is used?

### ISSUE THREAD

**Issue by hyrious** [be5invis/Sarasa-Gothic#307]
The default appearance of characters in Iosevka and Sarasa Gothic is a bit different. I want to know what's the corresponding config that [`iosevka-n`](https://github.com/be5invis/Sarasa-Gothic/tree/main/sources/iosevka-n) uses (like 'ss01' etc.).

Iosevka:

<img width="164" alt="image" src="https://user-images.githubusercontent.com/8097890/198912365-779d2ea2-25a2-4789-acfb-6d987b56c898.png">

Sarasa Gothic (等距更纱黑体 SC):

<img width="169" alt="image" src="https://user-images.githubusercontent.com/8097890/198912413-71111430-9d4f-4617-89d6-4209d26dcbdb.png">

**Comment by kataklasm** [comment]
Hi!
Looks like the featured Sarasa Gothic example uses the Italic slope for this highlight, while the plain Iosevka one uses Oblique sloping. Italic adds some script-like stuff to the characters, while Oblique just tilts for the most part I think.

**Comment by Xihan-Aaron** [comment]
You can actually generate your own customized Iosevka, whatever Latin letters and styles as long as Iosevka let you config, and include them when building Sarasa-Gothic.
