### ISSUE TITLE
Different between the file with the "unhinted" suffix and without in releases?

### ISSUE THREAD

**Issue by BahuangShanren** [be5invis/Sarasa-Gothic#308]
What's the difference between [sarasa-gothic-ttf-0.37.4.7z](https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.37.4/sarasa-gothic-ttf-0.37.4.7z) and [sarasa-gothic-ttf-unhinted-0.37.4.7z](https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.37.4/sarasa-gothic-ttf-unhinted-0.37.4.7z)  in releases?

There is no issue and wiki about it in this repo. And I didn't find the answer by Google, but saw that most people use release with the suffix "unhandled". I tried to find out the difference between them by myself, but failed.

**Comment by CrotchBurnt** [comment]
一个有hinting信息，一个没有

**Comment by BahuangShanren** [comment]
> 一个有hinting信息，一个没有

之前不明白 [hint](https://zh.wikipedia.org/wiki/%E5%AD%97%E4%BD%93%E5%BE%AE%E8%B0%83) 究竟是什么，现在知道了
