### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ChengCat** [be5invis/Sarasa-Gothic#31]
Are the font files of Sarasa Gothic licensed under SIL Open Font License 1.1 or BSD3?

Could you include a LICENSE file in the release .7z file?

**Comment by be5invis** [comment]
It is like Iosevka.
Font data are SIL.
Building scripts are BSD.

**Comment by ChengCat** [comment]
Thanks for the clarification. I am not a lawyer, but I think a LICENSE file included in the release .7z file would be better.

**Comment by yejingchen** [comment]
I also suggest to include a LICENSE file in released archives, as the file in master might not reflect the actual license at the time of releasing in case of a license change (though not likely to happen...).
Including it also simplifies linux packaging by omitting a unversioned file.

**Comment by CyanoHao** [comment]
@yejingchen 
Consider `https://raw.githubusercontent.com/be5invis/Sarasa-Gothic/v${pkgver}/LICENSE` for license url.

**Comment by yejingchen** [comment]
@CyanoHao 
This works like a charm. Thanks for the advice!
