### ISSUE TITLE
在win11的记事本里显示效果很差

### ISSUE THREAD

**Issue by Leoongithub** [be5invis/Sarasa-Gothic#310]
![image](https://user-images.githubusercontent.com/10937162/210919495-f1505c34-df26-4f39-9ee6-eeff6c36cec3.png)
左：SublimeText
右：Windows 11 NotePad
字体：sarasa-gothic-ttf-0.37.4 Sarasa Mono SC Regular

**Comment by lxgw** [comment]
这是 Windows 11 新版记事本的原因，可能不支持 DirectWrite，只支持基本的 ClearType，与 Windows XP~8.1 的 ClearType 效果类似。

（看截图，用的可能是没有 Hinting 的版本）

**Comment by Leoongithub** [comment]
@lxgw 用的字体是带hint的，没有hint的版本显示效果更差。不过既然是记事本的问题那就没办法了。

**Comment by kokutoukiritsugu** [comment]
一些qt做的程序里也有这个问题

很多模拟器比如 pcsx2-qt pcsx3 duckstation ryujinx yuzu 等等...

这个 telegram 也是这样 qt 做的

![Snipaste_2023-02-24_13-22-20](https://user-images.githubusercontent.com/5471433/221098953-c1e5d50f-dee4-4eed-b520-4312274b7f2b.png)
