### ISSUE TITLE
在某些应用中，小写字母i、j的头上没有点

### ISSUE THREAD

**Issue by ZhuangQu** [be5invis/Sarasa-Gothic#311]
![image](https://user-images.githubusercontent.com/89310792/211861870-34fa61c2-a2a6-41cb-9bd3-3e44c69aac85.png)
上图是搜狗拼音输入法的情况。这个问题同样发生于Word中。
我的系统是win 11，安装的字体是[sarasa-gothic-ttf-0.38.0.7z](https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.38.0/sarasa-gothic-ttf-0.38.0.7z)的mono-sc。

**Comment by git-yqk** [comment]
我是在使用EditPlus时发现这个问题的，我尝试打开“禁用统一码输出”后恢复正常，你可以尝试一下这个操作

**Comment by ZhuangQu** [comment]
> 我是在使用EditPlus时发现这个问题的，我尝试打开“禁用统一码输出”后恢复正常，你可以尝试一下这个操作

请问这个选项在何处QAQ

**Comment by git-yqk** [comment]
> > 我是在使用EditPlus时发现这个问题的，我尝试打开“禁用统一码输出”后恢复正常，你可以尝试一下这个操作
> 
> 请问这个选项在何处，是Windows11系统设置吗？

不，它仅针对EditPlus！如果需要解决其他程序中出现的问题，可以寻找类似“禁用统一码”的选项

**Comment by be5invis** [comment]
I cannot repro in Word. Not sure about that IME -- maybe it doesn't do shaping properly?

**Comment by ZhuangQu** [comment]
![image](https://user-images.githubusercontent.com/89310792/212738709-06a36034-e254-4093-b287-9b4323e68d4a.png)
This is the case in WORD.

**Comment by mclovin-2k** [comment]
![image](https://user-images.githubusercontent.com/5440567/213604178-b8840628-d6db-4794-9963-b4d7fa58bc3d.png)
This is the case in Notepad++.

**Comment by be5invis** [comment]
Should have been fixed in 0.39. Resolve as fixed.
