### ISSUE TITLE
Try to make a super ttc or variable font

### ISSUE THREAD

**Issue by mike-unk** [be5invis/Sarasa-Gothic#314]
Now we use 5 ttcs to install the font. "Source Han Sans" uses 1 super ttc or a variable font.
The Fonts "Inter" and "Source Han Sans" both have variable fonts. If "Iosevka" has a variable font, you can make a "Sarasa Gothic Variable".
现在我们用5个ttc来安装字体，而“思源黑体”只使用1个ttc或者1个可变字体文件。
“Inter”和“思源黑体”都已经有可变字体，如果“Iosevka”有可变字体，那么更纱黑体就可以有可变字体。

**Comment by be5invis** [comment]
I cannot make a VF for Iosevka because OT's mechanism is too weak to express boolean, so no VF in forseeable future.
Making super TTCs is valid (though it might have compatibility problems, and the font will be HUGE).

**Comment by Mr-Drinking** [comment]
> Now we use 5 ttcs to install the font. "Source Han Sans" uses 1 super ttc or a variable font. The Fonts "Inter" and "Source Han Sans" both have variable fonts. If "Iosevka" has a variable font, you can make a "Sarasa Gothic Variable". 现在我们用5个ttc来安装字体，而“思源黑体”只使用1个ttc或者1个可变字体文件。 “Inter”和“思源黑体”都已经有可变字体，如果“Iosevka”有可变字体，那么更纱黑体就可以有可变字体。

可以试试我做的[这个可变版本](https://github.com/Mr-Drinking/Sarasa-Ui-PropDigits)，SC 以外的其他地区也已经在 hinting 了。
