### ISSUE TITLE
Sarasa Mono SC在macOS的Terminal.app中，某些字符宽度有问题。

### ISSUE THREAD

**Issue by laishulu** [be5invis/Sarasa-Gothic#317]
MacOS的Terminal.app中，
Sarasa Mono SC字体的`U+2714` 和 `U+2718` 这两个字符被分配了一个英文字符宽度，
但字形实际上占了两个字符的宽度。

<img width="639" alt="Snipaste_2023-02-26_00-56-37" src="https://user-images.githubusercontent.com/1224321/221369600-23df4d75-340b-46bd-a8de-a374bca72b1b.png">

**Comment by laishulu** [comment]
在别的终端（比如kitty）里，显示效果更为混乱。
<img width="754" alt="Snipaste_2023-02-26_01-32-31" src="https://user-images.githubusercontent.com/1224321/221388114-5fea7c95-f1a3-4dd1-ac07-98cae01307cd.png">

**Comment by be5invis** [comment]
Use Sarasa Term.

**Comment by laishulu** [comment]
为什么Mono不行呢？
从README上看，这块没有区别啊：
Em dashes (——) are full width —— Mono
Em dashes (——) are half width —— Term

**Comment by be5invis** [comment]
Well Mono have many other symbols being wide. Term follows the metrics what Terminals want.

**Comment by Huaweidev** [comment]
遇到过横线与文字重叠的问题，如下图：
<img width="158" height="70" alt="Image" src="https://github.com/user-attachments/assets/ea1142e5-96f0-46b9-8e8b-c9ddd465e7d8" />
分析：
同属 Sarasa 家族，Term 和 Mono 两个变体对 U+2014 的处理不同：Term 把它压成半角 1 格，Mono 保留全角 2 格。U+2013 两者都是 1 格。Term 变体把 U+2014 压成半角，重叠没了。即 Term 字体对终端更友好。
