### ISSUE TITLE
Microsoft Store Version

### ISSUE THREAD

**Issue by lovedebug** [be5invis/Sarasa-Gothic#318]
Microsoft Store also have a font with same name, is it developed by the owner?
https://apps.microsoft.com/store/detail/%E6%9B%B4%E7%BA%B1%E9%BB%91%E4%BD%93/9MW0M424NCZ7?hl=en-us&gl=us

I am not sure about it.

**Comment by be5invis** [comment]
It is published by someone else (I do not maintain ANY packages distributed by package managers/stores). But since this font is licensed under OFL, anyone could do that freely.
Resolve as by design.
