### ISSUE TITLE
Merge full-width punctuation glyph from `Zhudou Sans` / 合并「煮豆黑体」中的全宽标点符号字形

### ISSUE THREAD

**Issue by yzy-1** [be5invis/Sarasa-Gothic#320]
There is a strange problem in the Noto Sans CJK / Source Han Sans fonts that the project is based on: When a web page has `font-feature-settings: "kern"` enabled in the CSS property, all full-width punctuations will be forced to clip the left and right margins, the result will be similar to half-width punctuations, which is very ugly.

Below is an example which shows some of the incorrectly rendered punctuation. Punctuation in this image like `，`(U+FF0C) and `．` (U+FF0E) are all full-width.

![example.png](https://img-kysic-1258722770.file.myqcloud.com/c4053b512bfe86ca27c704ce81362439/d99b920d3c45a.png)

[Zhudou Sans](https://github.com/Buernia/Zhudou-Sans) is a project which optimized for this problem by specializing the behavior of the kern attribute to punctuated extrusion:

![zhudou-kern.svg](https://github.com/Buernia/Zhudou-Sans/raw/main/images/chws.svg)

If you specify the Sans Serif mapping as `[Zhudou Sans, Sarasa UI SC]` in the system Fontconfig settings, this problem in the web browser can be solved. But another problem in some old applications arises: when using the font "Sans Serif" in some old GTK applications or some window managers, it will only reads first font (Zhudou Sans) from the Sans Serif list in Fontconfig file without using any fallback fonts. Since Zhudou Sans contains only punctuations, almost all glyphs in the software are displayed as boxes.

In view of the above, I hope this project will merge the full-width punctuation glyphs  from "Zhudou Sans".

---

在该项目基于的 Noto Sans CJK / Source Han Sans 字体中存在一个奇怪的问题：当一个网页在 CSS 属性中启用 `font-feature-settings: "kern"` 后，所有全宽标点均会强制裁剪左右两侧的空白部分，显示出来类似半宽标点的效果，十分难看．

下方是一个示例，示例中出现的所有标点符号，`，`（ U+FF0C）和 `．`（U+FF0E），均为全宽：

![example.png](https://img-kysic-1258722770.file.myqcloud.com/c4053b512bfe86ca27c704ce81362439/d99b920d3c45a.png)

[煮豆黑体](https://github.com/Buernia/Zhudou-Sans) 项目针对此问题进行了优化，将 kern 属性的行为特化为标点挤压：

![zhudou-kern.svg](https://github.com/Buernia/Zhudou-Sans/raw/main/images/chws.svg)

而如果直接在系统 Fontconfig 设置中直接指定 Sans Serif 映射为 `[Zhudou Sans, Sarasa UI SC]`，则可以在浏览器中解决此问题．但是在另外一些应用程序中又会引出另一个问题：在一些老旧的 GTK 程序或一些 Window Manager 中使用字体 Sans Serif 时，该程序只会读取 Sans Serif 列表中的一个字体（Zhudou Sans），而不采用任何 fallback 字体．又由于 Zhudou Sans 仅包含标点符号，导致软件中几乎所有字形均显示为方框，无法正常使用．

综上所述，希望该项目合并来自「煮豆黑体」的全宽标点符号字形．

**Comment by be5invis** [comment]
This one is interesting. Let me investigate.

**Comment by be5invis** [comment]
I checked Sarasa and confirmed that `kern` won't apply to full-width punctuations. As for importing glyphs from *Zhudou Sans* -- well, I dislike its curly commas’ shape, so importing it might not be an optimal solution. As for punctuation compression, I do not think fonts should care about that too much, at least for now (there are some OT features in discussion, like a feature removing extra spaces).

Resolve as Not Repro
