### ISSUE TITLE
`⊕` too big

### ISSUE THREAD

**Issue by fonqL** [be5invis/Sarasa-Gothic#322]
`⊕`(U+2295)
下载的是gothic-ttf-unhinted 0.40.0版本
更纱黑体 SC效果：
![image](https://user-images.githubusercontent.com/75968297/229518901-a8ec8d88-882f-49bf-83ae-545c0222bc9e.png)

可以看到甚至比行高还大
而等距更纱黑体又太小了

![image](https://user-images.githubusercontent.com/75968297/229519305-febcf410-b7fa-43e2-aba0-1c31446b3b96.png)

似乎Gothic和UI都是太大，其它都是太小。

**Comment by WangQuan-cn** [comment]
in MS word, you can use alt+8853(keyboard number area) to input this 
same issue in 0.40.7 super ttc
![image](https://github.com/be5invis/Sarasa-Gothic/assets/29138871/460e307b-516f-42dd-8fb1-941090eb11fd)
it seems 更纱黑体SC took 1.5 width than 等距更纱黑体SC
while the former is too large, the latter is too small 😢
