### ISSUE TITLE
Compatibility issue on `calt` table with extraterm.

### ISSUE THREAD

**Issue by Explorare** [be5invis/Sarasa-Gothic#328]
[\[Windows\] Malfunction of ligatures support (calt) cause GUI crash. · Issue #402 · sedwards2009/extraterm](https://github.com/sedwards2009/extraterm/issues/402)

## tl;dr 
I'm using [Sarasa Term J](https://github.com/be5invis/Sarasa-Gothic) in extraterm and the program will crash once the ligatures feature is enabled. But for [cascadia-code](https://github.com/microsoft/cascadia-code) the ligature feature works fine. The extraterm seems having issue to load the `calt` table in [Sarasa Term J](https://github.com/be5invis/Sarasa-Gothic). I'm wondering if there is any difference in the way `calt` feature is implanted, which makes Cascadia Code works but Sarasa Term J not. 

Sorry for bothering you but any in-depth info would be helpful.

**Comment by be5invis** [comment]
Maybe it doesn't support some of the lookup types (like [type 8 -- reverse single chaining substitution](https://learn.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-8-reverse-chaining-contextual-single-substitution-subtable))?

**Comment by Explorare** [comment]
I tried TTF version and it works as intend with both ligature off and on. As you said, the `GSUB` support might be the root cause. The trace log also throughout an error about `GSUB`, as the author of extraterm said. Thank you for your help.

**Comment by reinhardwoolf** [comment]
﻿On Thu, May 4, 2023 at 14:35 Belleve ***@***.***> wrote:
Maybe it doesn't support some of the lookup types (like type 8 -- reverse single chaining substitution)?
