### ISSUE TITLE
Request to migrate classical glyphs from GenneGothic to SourceHanToClassic (i.e. AdvocateAncientSans)

### ISSUE THREAD

**Issue by ryanlo713** [be5invis/Sarasa-Gothic#329]
Description:

I kindly request the project to consider migrating the classical glyphs from [GenneGothic](https://github.com/MoneMizuno/Genne-Gothic/releases) to [SourceHanToClassic](https://github.com/GuiWonder/SourceHanToClassic/releases), specifically using the typeface AdvocateAncientSans.

The GenneGothic project has not been updated for quite some time, and it would be beneficial for this project to adopt AdvocateAncientSans as the replacement for the shs-classical-override.

Your attention to this request is greatly appreciated.

Additional Information:

* GenneGothic repository: [Link to GenneGothic](https://github.com/MoneMizuno/Genne-Gothic/)
* AdvocateAncientSans repository: [Link to AdvocateAncientSans](https://github.com/GuiWonder/SourceHanToClassic/)

Thank you for considering this request. Please let me know if you require any further information.

**Comment by be5invis** [comment]
Do they provided subsetted version (only containing glyphs that "differs" from a certain SHS variant)?

**Comment by be5invis** [comment]
@GuiWonder I hope that such a version could be maintained in your Releases...

**Comment by GuiWonder** [comment]
OK. The subsetted version will be included in my Releases.
