### ISSUE TITLE
Could please explain the difference Sarasa-Gothic/mono/monoT/term/UI in the readme file?

### ISSUE THREAD

**Issue by iamCristYe** [be5invis/Sarasa-Gothic#33]
Thanks

**Comment by be5invis** [comment]
- LGC set being Nono Sans
  - Quotes (`“”`) are full width —— Gothic
  - Quotes (`“”`) are narrow —— UI
- LGC set being Iosevka
  - Have ligature, Quotes (`“”`) are full width —— MonoT
  - Have ligature, Quotes (`“”`) are narrow —— Mono
  - No ligature, Quotes (`“”`) are narrow —— Term

**Comment by acgtyrant** [comment]
@be5invis Hi, I think this explaniation is still not clear. I dot not know what does "LGC" means, and the most important version name should be placed to the beginning. I think you can change it to below, there may be some mirror errors:

### What is the difference between each version?

`Term`: Monospace, no ligature
`Mono`: Monospace, have ligature, Em dashes (`—`) are half width
`Mono T`: Monospace, have ligature, Em dashes (`—`) are full width
`UI`: Proportional, narrow quote (`""`) marks
`Gothic`: Proportional, full-width quote (`""`) marks

`SC`: Simplified Chinese
`TC`: Traditional Chinese
`J`: Japanese
`C`: Classical

**Comment by lxohi** [comment]
@be5invis 
Is it _Nono Sans_ mean _Noto Sans_?

Actually I was tried to google what is LGC is but failed. And I used to think _LGC set being Nono Sans_ maybe means the English characters are not from Iosevka anymore.
IMHO, a more detailed description may be better.

**Comment by be5invis** [comment]
@lxohi 
- Latin/Greek/Cyrillic character set being Noto Sans
  - Quotes (`“”`) are full width —— Gothic
  - Quotes (`“”`) are narrow —— UI
- Latin/Greek/Cyrillic character set being Iosevka
  - Have ligature, Em dashes (`——`) are full width —— MonoT
  - Have ligature, Em dashes (`——`) are half width —— Mono
  - No ligature, Em dashes (`——`) are half width —— Term

IS IT CLEAR NOW?

**Comment by lxohi** [comment]
Yes. Thanks!

So it is means if I want to use Iosevka I need to select the latter ones :)

**Comment by fireattack** [comment]
I'm confused, does `term` have ligatures or not nowadays? 

The above all said it doesn't, but readme says

```
Em dashes (——) are half width —— Term
No ligature, Em dashes (——) are half width —— Fixed
```

Did it change somewhere between 2019 and now?
