### ISSUE TITLE
全型連字號顯示一半的長度

### ISSUE THREAD

**Issue by MrLuke1110** [be5invis/Sarasa-Gothic#331]
Windows 10 22H2
sarasa-gothic-ttf-unhinted-0.41.0
全型連字號顯示一半的長度，協助確認…

![image](https://github.com/be5invis/Sarasa-Gothic/assets/66194793/057c9f8c-482d-4f86-a32b-b20eb937016b)

**Comment by be5invis** [comment]
What's the code point? I tested EM-DASH and it is correct.

**Comment by MrLuke1110** [comment]
Is this okay?  
![image](https://github.com/be5invis/Sarasa-Gothic/assets/66194793/946f039c-6b44-481a-bf59-248ec062027c)
