### ISSUE TITLE
0.40.4 及之后的版本在Windows上存在严重的兼容性问题。

### ISSUE THREAD

**Issue by alpzmj9** [be5invis/Sarasa-Gothic#336]
具体表现为在EDGE浏览器中无法显示，在Word中使用导出PDF会严重乱码等。
目前我的系统环境为Windows 11 专业版 Insider Preview Dev 23493.1000，已确定该问题在Windows10，Windows11目前最新正式版均可复现。
本机安装的字体为Super TTC，但根据下游[YaHei-Build](https://github.com/codehz/YaHei-Build)的issue反馈，疑似非Super TTC版本也有同样的问题。

**Comment by Pinghigh** [comment]
> 具体表现为在EDGE浏览器中无法显示，在Word中使用导出PDF会严重乱码等。 目前我的系统环境为Windows 11 专业版 Insider Preview Dev 23493.1000，已确定该问题在Windows10，Windows11目前最新正式版均可复现。 本机安装的字体为Super TTC，但根据下游[YaHei-Build](https://github.com/codehz/YaHei-Build)的issue反馈，疑似非Super TTC版本也有同样的问题。

你指的是强制替换雅黑之后导致乱码吗？微软给字体不知道加了什么限制，强制替换雅黑之后会出现各种诡异问题。

**Comment by alpzmj9** [comment]
强制替换雅黑后会出现部分软件直接不识别微软雅黑的问题，乱码问题出现在正常安装的字体上。
而且两种问题均只会出现在v0.40.4之后的版本上，我并不确定不确定是Windows兼容性问题，还是这个版本字体本身某处更改出了bug。

**Comment by alpzmj9** [comment]
> > 具体表现为在EDGE浏览器中无法显示，在Word中使用导出PDF会严重乱码等。 目前我的系统环境为Windows 11 专业版 Insider Preview Dev 23493.1000，已确定该问题在Windows10，Windows11目前最新正式版均可复现。 本机安装的字体为Super TTC，但根据下游[YaHei-Build](https://github.com/codehz/YaHei-Build)的issue反馈，疑似非Super TTC版本也有同样的问题。
> 
> 你指的是强制替换雅黑之后导致乱码吗？微软给字体不知道加了什么限制，强制替换雅黑之后会出现各种诡异问题。

强制替换后的确也会出现问题，表现为部分软件直接不识别微软雅黑。
但是使用MS Office打印PDF乱码（预览时正常），以及EDGE无法正常显示的问题，出现在正常安装的字体上。
同时这些问题均只会出现在v0.40.4之后的版本，我并不确定该问题出于Windows兼容性，还是该版本修改中存在bug。

**Comment by Pinghigh** [comment]
> > > 具体表现为在EDGE浏览器中无法显示，在Word中使用导出PDF会严重乱码等。 目前我的系统环境为Windows 11 专业版 Insider Preview Dev 23493.1000，已确定该问题在Windows10，Windows11目前最新正式版均可复现。 本机安装的字体为Super TTC，但根据下游[YaHei-Build](https://github.com/codehz/YaHei-Build)的issue反馈，疑似非Super TTC版本也有同样的问题。
> > 
> > 
> > 你指的是强制替换雅黑之后导致乱码吗？微软给字体不知道加了什么限制，强制替换雅黑之后会出现各种诡异问题。
> 
> 强制替换后的确也会出现问题，表现为部分软件直接不识别微软雅黑。 但是使用MS Office打印PDF乱码（预览时正常），以及EDGE无法正常显示的问题，出现在正常安装的字体上。 同时这些问题均只会出现在v0.40.4之后的版本，我并不确定该问题出于Windows兼容性，还是该版本修改中存在bug。

感觉是 Microsoft Print to PDF 的问题，我用这个打印出来的粗体斜体是有乱码的，但是从 word 直接导出 PDF 是正常的

**Comment by fmnijk** [comment]
我看一下光是縮圖就有問題了 0.41.9和0.40.4都有問題
一個是只有sarasa-regular.ttc有問題 另一個是只有sarasa-regular.ttc沒問題
問題可能出在hint資訊上? 這個我不是很懂
<img width="802" alt="demo_picture_001" src="https://github.com/be5invis/Sarasa-Gothic/assets/52465927/1c1c2b68-3df4-44aa-aee0-528fc0aac5b8">
<img width="802" alt="demo_picture_002" src="https://github.com/be5invis/Sarasa-Gothic/assets/52465927/1f995f3a-38c3-4b22-9fae-cf3423664b02">

**Comment by be5invis** [comment]
You can try install the TTF version instead (though, well, it will take a lot more space).
Also, before you install the fonts, **REMOVE THE OLD VERSION COMPLETELY**.
