### ISSUE TITLE
能否像思源黑体那样，中文名不带 SC 和 TC？

### ISSUE THREAD

**Issue by Yave-Yu** [be5invis/Sarasa-Gothic#337]
本身中文名就能通过简繁来区分 SC 和 TC，就没必要再加 SC 和 TC 吧？画蛇添足的感觉。

**Comment by Demonese** [comment]
思源黑体 不仅有带 SC 和 TC 的版本，还有带 CN、HK、TW 等的版本，按语言，国家或地区区分是正确的做法

**Comment by Yave-Yu** [comment]
> 

从 GitHub 下载的思源黑体，其字体名就不带 SC、TC、JP、KR 字样，而是各语言的写法，方便调用 (像 Aegisub 这种不支持多字重，只能对应 Regular、Bold 的环境，想要其它字重就只能填字体名，XXXXXX Medium 这样的，没 SC、TC 这些后缀能省点事)。

**Comment by be5invis** [comment]
I prefer keepipng suffixes for more clarity. When describing the font name *in voice*, SC and TC names will be identical if they do not have the suffix.
Resolve as by design.
