### ISSUE TITLE
小型大写字母（Small Caps）特性不全

### ISSUE THREAD

**Issue by Wenti-D** [be5invis/Sarasa-Gothic#338]
开启 Small Caps 字体特性后，更纱黑体的 A~F、J、K、P、Q、U 字母未能变为小型大写形式，应当是缺少对应字符。
![image](https://github.com/be5invis/Sarasa-Gothic/assets/73067578/0e188810-4247-4ee5-857a-a638c1363850)

**Comment by be5invis** [comment]
This feature comes from Inter. Please report a bug in Inter's repository.
Resolve as external.
