### ISSUE TITLE
TTC font blankspace width issue in RStudio

### ISSUE THREAD

**Issue by TTTPOB** [be5invis/Sarasa-Gothic#34]
### System details

    RStudio Edition : Desktop
    RStudio Version : Latest(1.1.447) 
[Project link](https://github.com/rstudio/rstudio)

    OS Version      : Windows 10 1803(17134.5)
    R Version       : Latest Stable(3.5.0)
    Custom Font:  Sarasa Mono SC(TTC)

### Steps to reproduce the problem
    Use this font and input some spaces and you will see.(more spaces, more drift)
### Describe the problem in detail
    like this screenshot
![Screenshot](https://s1.ax1x.com/2018/05/06/CU1MrQ.png)

### Describe the behavior you expected
The cursor is expected to present right after the "l"

###P.S.
As this might be an RStudio bug, i've reported to the project also. 
And this issue looks  like other symbol width issue so I'll try the ttf version.

**Comment by be5invis** [comment]
Looks like an indentation gutter...
You could try other fonts and see whether it is a Sarasa-specific problem

**Comment by HaroldYu** [comment]
Yes I've tried other fonts and the TTF version of Sarasa Mono SC, it turns out that the problem will only appear when using the TTC version of Sarasa fonts.

**Comment by be5invis** [comment]
Sarasa's TTC combines many subfonts and RStudio is reported to "hate" it.
It is a software issue since all the TTCs pass OTS, which means that they are conformal to the OTSpec.

**Comment by HaroldYu** [comment]
ok, thanks... I think I may need to report this to RStudio developers.

**Comment by HaroldYu** [comment]
No I was wrong... the problem still exists with the TTF version but only occur in the editor area(instead of both editor and console like TTCs). So I changed my font to consolas for I can find no solution with font not changed... But I really like your font for it's so elegant.

**Comment by be5invis** [comment]
This is really strange. The dashed lines you see does not even have the same color as the text.
I think it should be a feature of RStudio, rather than a font bug.

**Comment by be5invis** [comment]
This feature is called "Indent Guide" and it could be hidden:

![image](https://user-images.githubusercontent.com/240091/39673505-61153724-5170-11e8-9cd0-3352b86d6663.png)

**Comment by HaroldYu** [comment]
If you the dashed line you mean is this
![image](https://user-images.githubusercontent.com/19909103/39673528-d84dacf4-5170-11e8-9dda-f1437b858bb1.png)
This is a feature but it seems have nothing to do with this bug.
It is "Show whitespace characters" that should be turned off.
And, a big thanks(I've wasted a whole afternoon to look for an alternative to Sarasa Mono...)

**Comment by be5invis** [comment]
Have you tried to turn ”Show indent guide“ off?
