### ISSUE TITLE
责字在 更纱黑体 UI SC 粗体模式下，如果字号小于12，会出现显示不全的问题

### ISSUE THREAD

**Issue by elsesky** [be5invis/Sarasa-Gothic#341]
RT.
![image](https://github.com/be5invis/Sarasa-Gothic/assets/10382513/c4223d4b-4183-493a-803b-ee2853a3eb6a)

**Comment by 107295472** [comment]
这个是英文用的字体吧

**Comment by elsesky** [comment]
> 

但是这个不是带SC字样吗？理论上不应该是支持简体中文？

**Comment by 107295472** [comment]
他不是等宽的，看着好细

**Comment by elsesky** [comment]
> 他不是等宽的，看着好细

确实不是等宽的，但这和我提交的issue有关系？

**Comment by CrotchBurnt** [comment]
hinted就是这样，你可以试一下unhinted版本

**Comment by be5invis** [comment]
You can try using the unhinted vairant which blurs (instead of abbrivating) strokes when the space is limited.
Resolve as by design.
