### ISSUE TITLE
What variant is the iosevka-n series?

### ISSUE THREAD

**Issue by hongshawo** [be5invis/Sarasa-Gothic#342]
How can I build the iosevka-n series of ttfs from source?

**Comment by be5invis** [comment]
Just like normal, but with CV/SS disabled (otherwise there will be too many glyphs in the final font).

**Comment by hongshawo** [comment]
Thank you so much!

**Comment by Zenvie** [comment]
> Just like normal, but with CV/SS disabled (otherwise there will be too many glyphs in the final font).

@be5invis I apologize for the interruption. I noticed that the font file downloaded from the [Releases](https://github.com/be5invis/Iosevka/releases/download/v28.0.4/PkgTTF-IosevkaFixed-28.0.4.zip) of the Iosevka repository (PkgTTF-IosevkaFixed-28.0.4/IosevkaFixed-Bold.ttf 6.93 MB) is much larger than the font file compiled from the source code of this repository (sources/IosevkaNFixed/IosevkaNFixed-Bold.ttf 740 KB). What options should I enable or disable when compiling the Iosevka font?
