### ISSUE TITLE
GUI org-mode table misalignment（GUI org-mode 表格不对齐）

### ISSUE THREAD

**Issue by Thysrael** [be5invis/Sarasa-Gothic#346]
I am getting unaligned tables after entering org-mode in the emacs gui interface as shown below:
![image](https://github.com/be5invis/Sarasa-Gothic/assets/72613958/0edbf09b-b53e-481e-a897-6e7f91f1d59e)

My font settings are as follows:
![image](https://github.com/be5invis/Sarasa-Gothic/assets/72613958/f3244413-7977-4142-b446-f389c8cbc9bc)

My os is a manjaro system with the emacs version shown below, I didn't use a distro like spacemacs or doomemacs, but built it myself:
``` shell
~ > emacs --version     
GNU Emacs 29.1
Copyright (C) 2023 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
My topic is [timu-rouge](https://gitlab.com/aimebertrand/timu-rouge-theme).

My current emacs config file is [here](https://github.com/Thysrael/.emacs.d)

I don't know much about font-related configuration and development, so I'm not sure if the information I've provided is complete, but I'll be checking back on this issue every day to see if there's anything else I can provide. Thank you very much for your time and help.

I downloaded the fonts by downloading the ttf files from the release and installing them.

Finally, thank you very much for developing this font, I really like it.

-----

我在 emacs gui 界面进入 org-mode 后出现了表格未对齐的现象，效果如下图：
![image](https://github.com/be5invis/Sarasa-Gothic/assets/72613958/0edbf09b-b53e-481e-a897-6e7f91f1d59e)

我的字体设置如下：
![image](https://github.com/be5invis/Sarasa-Gothic/assets/72613958/f3244413-7977-4142-b446-f389c8cbc9bc)

我的系统是 manjaro 系统，emacs 版本如下所示，我没有采用像 spacemacs 或者 doomemacs 这样的发行版，而是自己搭建的:
``` shell
~ > emacs --version     
GNU Emacs 29.1
Copyright (C) 2023 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
我的主题是 [timu-rouge](https://gitlab.com/aimebertrand/timu-rouge-theme)。

我目前的 emacs 配置文件在[这里](https://github.com/Thysrael/.emacs.d)

我不太了解字体相关的配置和开发，所以我不确定我提供的信息完不完全，不过我会每天回看这个 issue，如果还需要我提供什么信息，我都会提供的。非常感谢您的浏览和帮助。

我下载字体的方式是下载 release 里面的 ttf 文件并安装。

最后，非常感谢您开发这样字体，我真的非常喜欢。

**Comment by git-yqk** [comment]
中英字体对齐或许应该使用带有mono标志的字体
![image](https://github.com/be5invis/Sarasa-Gothic/assets/58689093/eeab1327-31d4-4c41-a201-bec985b98b61)
![image](https://github.com/be5invis/Sarasa-Gothic/assets/58689093/1175301c-f195-4fdb-88d7-9122e92165b3)

**Comment by Thysrael** [comment]
> 中英字体对齐或许应该使用带有mono标志的字体 ![image](https://user-images.githubusercontent.com/58689093/281616990-eeab1327-31d4-4c41-a201-bec985b98b61.png) ![image](https://user-images.githubusercontent.com/58689093/281617082-1175301c-f195-4fdb-88d7-9122e92165b3.png)

非常感谢您的帮助，但是即使设置成这样

![image](https://github.com/be5invis/Sarasa-Gothic/assets/72613958/d915ffd4-40d0-4460-9852-17f7d2df6a05)

依然是没有办法对齐的

![image](https://github.com/be5invis/Sarasa-Gothic/assets/72613958/4699249e-5fe4-4d96-883c-e18614cf4341)

**Comment by drcxd** [comment]
这个问题应该是中文字体和英文字体宽度不匹配造成的。简单来说，就是两个英文字符和宽度应该和一个中文字符的宽度相同；否则就会出现这种问题。我在Windows上使用Emacs，默认的字体是黑体，是和英文字体宽体匹配的，一旦使用微软雅黑，或是 Sarasa Gothic，也会出现这个问题。

**Comment by Thysrael** [comment]
> 这个问题应该是中文字体和英文字体宽度不匹配造成的。简单来说，就是两个英文字符的宽度应该和一个中文字符的宽度相同；否则就会出现这种问题。我在Windows上使用Emacs，默认的字体是黑体，是和英文字体宽体匹配的，一旦使用微软雅黑，或是 Sarasa Gothic，也会出现这个问题。

最终解决了问题
