### ISSUE TITLE
修改更纱黑体并提供公开下载有版权问题么？

### ISSUE THREAD

**Issue by neotpravlennoye** [be5invis/Sarasa-Gothic#349]
作者你好，
我做了一套脚本处理黑纱黑体，把它伪装成微软雅黑和宋体，方便在windows环境直接硬替换，因为github的自动化ci很方便所以托管在github，
我想询问的是这样有没有版权问题，
如果有问题我会把仓库设置为私有，这样只有自己能用
如果没问题我就保持公开，方便同样有类似需求的人。
https://github.com/neotpravlennoye/sarasa2yahei

**Comment by CyanoHao** [comment]
版权方面没有问题，但商标权相关的问题建议咨询法律方面的专业人士。

> Microsoft YaHei is either a registered trademark or a trademark of Microsoft Corporation in the United States and/or other countries.
