### ISSUE TITLE
CJK font width seems wrong

### ISSUE THREAD

**Issue by jilen** [be5invis/Sarasa-Gothic#35]
Very strange the same font works perfectly on another computer, have no idea what is wrong
![screenshot from 2018-05-07 21-27-08](https://user-images.githubusercontent.com/546573/39704584-5f8ed1ac-523e-11e8-86af-5fce53ac041f.png)

**Comment by alick** [comment]
Check your font size (and scaling factor, HiDPI or not). Make sure it is 12 or its multiples. That's the magic font size. See also https://bugzilla.redhat.com/show_bug.cgi?id=1529984#c38

**Comment by jilen** [comment]
@alick Thanks very much, you save my day !!!
