### ISSUE TITLE
更纱黑体 SC 的 em dash (U+2014) 连用长度不足以连续

### ISSUE THREAD

**Issue by sommio** [be5invis/Sarasa-Gothic#351]
不少中文正文字体的 em dash (U+2014) 长度在连用时 `——` 都足以看起来连续，更纱黑体 SC 是否也可如此？

![hhhxeEP3lpMKVLG4.png](https://s2.loli.net/2023/11/11/ApzHvu7FYTVNl4G.png)

**Comment by yoonhakcher** [comment]
本人认为中文编程字体将破折号不连续显示并无不妥。在编程或是其他必要的情形之下破折号视觉上不连续的特性应该得以保留。

**Comment by hunderlinehh** [comment]
> 本人认为中文编程字体将破折号不连续显示并无不妥。破折号视觉上不连续的特性应该在必要的时候得以保留。

Mono 和 Gothic 不一样。

像 Mono 这种等宽的版本才能叫「编程字体」。Gothic 只是普通的显示字体，不是特别为「编程」打造的，所以按规范来说破折号是不分段的。

**Comment by mike-unk** [comment]
和思源黑体一致就很好，思源黑体对破折号的处理是出了名的好（使用连字特性替换成U+2E3A TWO EM DASH）
![Source Han Sans SC](https://github.com/be5invis/Sarasa-Gothic/assets/53944618/c4883403-0fad-4436-a5a2-8484a32a9839)
![Sarasa Gothic SC](https://github.com/be5invis/Sarasa-Gothic/assets/53944618/8aabba6e-2984-4077-9e46-4f29e5c3a1fe)

**Comment by be5invis** [comment]
Using a long glyph is... problematic anyway.
Maybe we could do something more CALT-like...
