### ISSUE TITLE
请求：按语种分类下载

### ISSUE THREAD

**Issue by XHXIAIEIN** [be5invis/Sarasa-Gothic#361]
## 问题描述

目前，每个字体文件都会附带所有语种、环境的字型，安装之后会迅速占满字体列表，手动删除还非常麻烦。因为每个字重文件会包含所有的语种。

然而，大部分用户并不需要用到那么多字体，对于第一次下载的用户来说，面对这么多语种，环境子集，会很感到疑惑。

甚至许多人只需要用到 "等距黑纱黑体 SC" 或 "Sarasa Term SC" 将其作为 IDE 字体。

## 提议

参考 [[Source Han Sans](https://github.com/adobe-fonts/source-han-sans/tree/release#readme)] 和 [Source Han Serif](https://github.com/adobe-fonts/source-han-serif/tree/release#readme) 的 README.md，单独提供对应分类的字体文件下载（通过链接到文件地址的形式）。

提供 `cl, sc, tc, hc, j, k` 单独的字体集，提供对应语种的 `gothic, ui, mono, mono-slab, term, term-slab, fixed, fixed-slab` 单独下载。

**Comment by DOSforever** [comment]
同意。一个文件包几百兆不说，全部解压后竟然有十几个吉之巨！当然也可以从压缩包中分别挑选所需的字体文件解压出来，但一个个手动选择实在是太麻烦。同一语言的文件放在一个压缩包中范围可以小很多。

另外有个问题不明白，既然任何一个语言的字体文件都可以显示其它语言的字体，那么为什么要分这么多语言？比如不带任何语言的字体都可以显示简体中文、繁体中文、日文、韩文，那么为什么还要分这么多语言的字体文件？

**Comment by stone-zeng** [comment]
> 另外有个问题不明白，既然任何一个语言的字体文件都可以显示其它语言的字体，那么为什么要分这么多语言？比如不带任何语言的字体都可以显示简体中文、繁体中文、日文、韩文，那么为什么还要分这么多语言的字体文件？

不同语言有默认字形的区分，例如同样是「返」字（U+8FD4）就有五种字形：

<img width="947" alt="Screenshot 2024-01-22 at 19 57 42" src="https://github.com/be5invis/Sarasa-Gothic/assets/18233088/095db452-1ab9-4874-84ba-31fb3fdb2538">

来源：[SourceHanSansReadMe.pdf](https://github.com/adobe-fonts/source-han-sans/blob/release/SourceHanSansReadMe.pdf)

**Comment by DOSforever** [comment]
> > 另外有个问题不明白，既然任何一个语言的字体文件都可以显示其它语言的字体，那么为什么要分这么多语言？比如不带任何语言的字体都可以显示简体中文、繁体中文、日文、韩文，那么为什么还要分这么多语言的字体文件？
> 
> 不同语言 / 地区有默认字形的区分，例如同样是「返」字（U+8FD4）就有五种字形：
> 
> <img alt="Screenshot 2024-01-22 at 19 57 42" width="947" src="https://private-user-images.githubusercontent.com/18233088/298577666-095db452-1ab9-4874-84ba-31fb3fdb2538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjczMzYsIm5iZiI6MTcwNTkyNzAzNiwicGF0aCI6Ii8xODIzMzA4OC8yOTg1Nzc2NjYtMDk1ZGI0NTItMWFiOS00ODc0LTg0YmEtMzFmYjNmZGIyNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEyMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMWUzNmU1YjNkYjljOTdjYWU1MGQwNWVjYmViYjY3YTY0NzgwMzQxYTIxNjFjM2VhNGQ4NTQxYWQxYTY4OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKSfSzYCuL4j5ye24wGZdZH5s8HIbIhOLTvvrjPr-Pg">
> 来源：[SourceHanSansReadMe.pdf](https://github.com/adobe-fonts/source-han-sans/blob/release/SourceHanSansReadMe.pdf)

感谢解答

**Comment by stone-zeng** [comment]
> 不过你给出的来源链接，我点击后出现的不是 pdf 文档，而是一个网页，提示 ： Error rendering embedded code
> 
> Invalid PDF
> 
> 或
> 
> Unable to render code block

这个是 GitHub 渲染的 PDF 文件，而众所周知 GitHub 会遇到网络问题的……另外右上角也有下载按钮。

**Comment by be5invis** [comment]
Now it creates packages with single family + region.

**Comment by XHXIAIEIN** [comment]
是否可以提供单个地区所有类型的包？
例如我想一次性下载 SC 的 Gothic, Ui, Mono, MonoSlab, Term, TermSlab, Fixed, FixedSlab 字体

**Comment by DOSforever** [comment]
> 是否可以提供单个地区所有类型的包，SuperTTC ？ 例如我想一次性下载 SC 的 Gothic, Ui, Mono, MonoSlab, Term, TermSlab, Fixed, FixedSlab 字体， (现在都140个包了，好像也不差这 6 or 12 个？hhh)

我也倾向于按语种分类打包，但按照现在这样的细分，又是 7z 又是 zip ，然后又是不同分类，每次版本的推出又是那么多压缩包，每次这样给 github 的服务器带来不小的压力。现在这样细分，我是按照我所需的生成下载列表文件，然后用支持批量下载的工具一次性下载，如 aria2c 或 FDM
比如我只下载 CL 和 SC 字体

```
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaGothicCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaUiCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaMonoCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaMonoSlabCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaTermCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaTermSlabCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaFixedCL-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaFixedSlabCL-TTF-1.0.9.7z

https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaGothicSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaUiSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaMonoSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaMonoSlabSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaTermSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaTermSlabSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaFixedSC-TTF-1.0.9.7z
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.9/SarasaFixedSlabSC-TTF-1.0.9.7z
```


镜像站点下载链接的 URL：

```
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaGothicCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaUiCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaMonoCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaMonoSlabCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaTermCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaTermSlabCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaFixedCL-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaFixedSlabCL-TTF-1.0.9.7z
 
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaGothicSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaUiSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaMonoSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaMonoSlabSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaTermSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaTermSlabSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaFixedSC-TTF-1.0.9.7z
 https://mirror.nju.edu.cn/github-release/be5invis/Sarasa-Gothic/Sarasa Gothic, Version 1.0.9/SarasaFixedSlabSC-TTF-1.0.9.7z
```

以后若是版本更新，一般路径不会更改，只要批量修改下 URL 中的版本号即可。
