### ISSUE TITLE
能否说明下下载文件名中各名称的含义？

### ISSUE THREAD

**Issue by DOSforever** [be5invis/Sarasa-Gothic#364]
Unhinted , TTC , SuperTTC 是什么意思？谢谢！

**Comment by XHXIAIEIN** [comment]
**TTC**: 你可以理解成它里面塞了很多个 `TTF` 的字体文件，相当于一个压缩包。可以包含多个 TrueType 字体的文件格式。好处就是，让文件更小。

**SuperTTC**: 就是 TTC 的升级版，有更高效的打包方式，可以往里面塞更多的可变字体。进一步节省空间。

**Unhinted**: 没有微调字形的版本，也就是使用 Iosevka 和 Source Han Sans 原版的字形。文件大小比其他版本更小，但可能在某些字的结构上，显示没那么清晰。特别是小字号。如果不是很在意文件大小，而且也不在意字体的显示清晰，一般不选。

**Comment by DOSforever** [comment]
> **TTC**: 你可以理解成它里面塞了很多个 `TTF` 的字体文件，相当于一个压缩包。可以包含多个 TrueType 字体的文件格式。好处就是，让文件更小。
> 
> **SuperTTC**: 就是 TTC 的升级版，有更高效的打包方式，可以往里面塞更多的可变字体。进一步节省空间。
> 
> **Unhinted**: 没有微调字形的版本，也就是使用 Iosevka 和 Source Han Sans 原版的字形。文件大小比其他版本更小，但可能在某些字的结构上，显示没那么清晰。特别是小字号。如果不是很在意文件大小，而且也不在意字体的显示清晰，一般不选。

感谢解答。再问下， 就该字体而言，是否 TTC 的字库只适用于 Windows 10 及以上版，不能在 Windows 8.1/8/7/XP 及以下版上使用？我以前曾经在 Windows 7 上安装 0.32 版的 TTC 字库，结果报错。不知这是字体版本的原因还是更纱黑体的 TTC 字库就是不支持 Windows 8.1/8/7/XP 及以下版？

**Comment by shinyora** [comment]
多谢您精心制作的字体，请教个问题:  
 1. 由于TTC字库大，系统资源开销不少。
 2. 但是，我只需Sarasa Mono J-regular.ttf 和Sarasa Mono SC-regular.ttf, 
 3. 请问用啥工具，譬如FontForge, 如何把这两个ttf文件，整合为一个ttc文件，windows上能安装
 致谢！

**Comment by be5invis** [comment]
@DOSforever Install the TTF packages (the reason is, well, the sum of all family names together in one TTC is too long).
