### ISSUE TITLE
如何把Sarasa-Mono-J-regular.ttf 和Sarasa-Mono-SC-regular.ttf合成一个ttc？

### ISSUE THREAD

**Issue by shinyora** [be5invis/Sarasa-Gothic#365]
多谢您精心制作的字体，请教个问题:

1，由于TTC字库大，系统资源开销不少。
2，但是，我只需Sarasa Mono J-regular.ttf 和Sarasa Mono SC-regular.ttf,
3，请问用啥工具，譬如FontForge, 如何把这两个ttf文件，整合为一个ttc文件，windows 10上能安装

致谢！

**Comment by be5invis** [comment]
You can use `otf2otc`. They do a simple bundling (though, no compression).

**Comment by shinyora** [comment]
[be5invis]様、即時返事、ありがとうございます。
１，otf2otcについて、確認したところで、
　　adobeのtoolであり、環境揃えるには努力が必要です。
２，ユーザの立場では、release時、ついでに
　　SaraMonoJ-regular.ttf　と　SaraMonoSC-regular.ttf　
　　を結合、圧縮して.ttcにかためるではないでしょうか？
申し訳ございませんが、よろしくお願いいたします。
