### ISSUE TITLE
现在下载分类过于细致，有点矫枉过正了。

### ISSUE THREAD

**Issue by DOSforever** [be5invis/Sarasa-Gothic#366]
假如我要下载同样是简体中文字体，我得一个个查看，一个个分别单独下载，实在是太麻烦，一不小心还漏了几个。
建议按照语种来分类打包字体，因为一般都是下载同一语种的字体，不太可能这个语种用这几个字体，那个语种用那些个字体。
大致可分为无任何特定语言，简体中文、繁体中文、日文、韩文，每个语种再分为 Hinted 和无 Hinted ，TTC 和 SuperTTC ，这样 5\*2\*2 ，大致分为20个字体压缩包差不多了，现在一百多个文件包要看死人了。TTC 和 SuperTTC 可能是单独4个文件，那么在 TTF 中分为 Hinted 和无 Hinted ，那么只有 5\*2=10 个 TTF 文件包+4个单独 TTC 文件包，14个文件包比较合适。

**Comment by be5invis** [comment]
If I merge them by language, there will be another issue asking me to break the archives into more granular pieces.
I can make a table though...

**Comment by DOSforever** [comment]
是的，过于粗旷不好，过于细致也不好，都有可能带来不便，找到一个合适的平衡点最好。做成一个表格式的分类最清楚了，或者可以按目录分类，大体上分 Hinted 和无 Hinted ，然后一个语种一个子目录，每个语种子目录下再分若干子目录或直接一个字体一个压缩包文件。这样既可以单独下载某一个字体，又可以同一类字体在一个目录里选，省得都放在一个下载列表中看花了眼。

**Comment by wangyan-life** [comment]
Amazing, yesterday I hadn't seen the table in the release and my head was spinning, today it's there! Awesome！

**Comment by DOSforever** [comment]
> If I merge them by language, there will be another issue asking me to break the archives into more granular pieces. I can make a table though...

Great! 太好了！虽然现在文件比较多，但通过 aria2c 批量下载也能一次性把所需语言的字体下载完，以后版本更新的时候只需把保存的 URI 批量修改下即可。
再配合 7z 命令行解压，可以把压缩包中所需的 TTF 字体文件分类解压到不同目录。
现在发现其实对 Coarse-grained 打包的压缩包也可以用 7z 命令行处理所需的 TTF 文件，只不过要一个个变换相应的文件名比较麻烦，有独立的压缩包选择范围就缩小了许多。

**Comment by DOSforever** [comment]
> Amazing, yesterday I hadn't seen the table in the release and my head was spinning, today it's there! Awesome！

哈哈！你的头像也 Amazing，愿你和你们都和你们头像一样可爱，哈哈哈哈！
