### ISSUE TITLE
为何某些环境下唯独 Mono CL 字体显示不正常？

### ISSUE THREAD

**Issue by DOSforever** [be5invis/Sarasa-Gothic#367]
Windows 7，Sarasa 字体版本 1.0.5 , Cmder 中的 bash 或 CMD 环境。
如果使用 Mono CL 显示中文字符就会出现不正常，如图，如果要显示“**中文汉字**”这四个字，但显示出的字符如下：
![monocl显示不正常](https://github.com/be5invis/Sarasa-Gothic/assets/8691390/903ba496-41b4-4f9d-af69-debe81af254c)
而且奇怪的是唯独只有 Mono CL 不正常，其它 Mono CL 系列和其它 Sarasa 字体都正常。
在其它应用软件中如各类文本编辑器使用 Mono CL 也正常。
这是什么原因？

**Comment by liumingedwin** [comment]
这可能最好去cmder看问题

**Comment by DOSforever** [comment]
> 这可能最好去cmder看问题
看来确实是 Cmder 的问题，升级更新到 1.3.24 版后显示正常了。

**Comment by DOSforever** [comment]
> 这可能最好去cmder看问题

看来确实是 Cmder 的问题，升级更新到 1.3.24 版后显示正常了。
