### ISSUE TITLE
下载1.06版Windows Defender 报毒,但是下载1.05版本就不报毒

### ISSUE THREAD

**Issue by panglongqi** [be5invis/Sarasa-Gothic#369]
下载 v1.06版本,Windows defender 报 Trojan:Script/Wacatac.B!ml，但是v1.05版本就不报。
不知什么情况。
我也向Microsoft反馈了
![screenshot-1710127461106](https://github.com/be5invis/Sarasa-Gothic/assets/5959230/abf9f228-b518-497d-a726-7d14ac764480)

**Comment by be5invis** [comment]
I tested it on https://www.virustotal.com/ and they said it is clear.
https://www.virustotal.com/gui/file/d45b36ffe5c9c302d5386e063c5c282eadc592c4ee2ce136e9528489cb14b14e?nocache=1

**Comment by be5invis** [comment]
Removing the release for now.
I may try use zip files instead. Though it will increase the file size...

**Comment by be5invis** [comment]
I recreated the release, which should be OK now.

**Comment by pghvlaans** [comment]
Quick maintenance-related question: is the switch to zip permanent, or for version 1.0.6 only?

**Comment by be5invis** [comment]
@pghvlaans Should be permanent. And yes file size will be large, so I uploaded fine-grained packages so you will not need to download several GBs.

**Comment by pghvlaans** [comment]
Understood. SlackBuilds uses the TTC file, so it shouldn't make too much of a difference either way; I just need to make sure the script is right going forward. Thank you!

**Comment by DOSforever** [comment]
> @pghvlaans Should be permanent. And yes file size will be large, so I uploaded fine-grained packages so you will not need to download several GBs.

我强烈反对这样做。毕竟这样的误报是暂时的，这方面应该是让杀毒软件改进而不是我们向误报妥协，相信以后杀毒软件会得以纠正这个误报。而且主要问题是压缩成 ZIP 文件体积要大很多，如果是相差不大那也就算了。本来所有字体、所有语言都压缩为一个大包，现为了方便用户下载拆分为比较详细的一个个小包，已经是增大好几倍的体积了，现在改为 ZIP 压缩包再次又增大了几倍的体积，这样每次版本推出都要比原来大几十倍的体积。这不仅增加 github 服务器的压力，也给我们下载用户造成不少的空间占用，结果我们也可以将下载压缩包再自行打包为 7z 或 RAR 等其它压缩率较高的文件，但这也是多一步麻烦。不要因为一个小小的暂时性误报而给自己和服务器、用户带来长久的麻烦。

**Comment by be5invis** [comment]
@DOSforever I can try whether it is still problematic in v1.0.7, if not I can revert to 7z files. I could provide extra ZIP packages for TTCs.
