### ISSUE TITLE
命令提示符中一些符号的显示问题

### ISSUE THREAD

**Issue by L0TEUS** [be5invis/Sarasa-Gothic#37]
例如数学交集并集符号∩∪和倒三角符号▽，在命令提示符中输入以后占用两个字符的宽度，此时在后面继续输入一个字母，然后将命令提示符窗口最小化，再恢复查看，可以看到后面的那个字母向前缩了一个字符的宽度，但是符号的光标依旧是两个字符的宽度。

**Comment by be5invis** [comment]
This is more like a CONHOST issue
You can try Sarasa Term instead.

发自我的 iPhone

在 2018年5月23日，20:14，L0TEUS <notifications@github.com<mailto:notifications@github.com>> 写道：


例如数学交集并集符号∩∪和倒三角符号▽，在命令提示符中输入以后占用两个字符的宽度，此时在后面继续输入一个字母，然后将命令提示符窗口最小化，再恢复查看，可以看到后面的那个字母向前缩了一个字符的宽度，但是符号的光标依旧是两个字符的宽度。
