### ISSUE TITLE
[BUG]在Releases里面，1.0.6介绍内的下载链接指向的是1.0.5

### ISSUE THREAD

**Issue by abbaccadd0** [be5invis/Sarasa-Gothic#370]
字面意思
在Releases里面，1.0.6介绍内的下载链接指向的是1.0.5
这应该不是有意为之的，因此作为一个Bug提交

**Comment by panglongqi** [comment]
Assets 里面的是v1.06

**Comment by be5invis** [comment]
Fixed

**Comment by SekiBetu** [comment]
1.0.6现在不见了，是啥情况，只有个tag没有文件了

**Comment by be5invis** [comment]
@SekiBetu @panglongqi I am changing the archive format to ZIP. Though I HAVE to split the TTF archive files into multiple ones (one archive for one family).
