### ISSUE TITLE
In Releases, the Unhinted version (in markdown) lead to 404 URLs

### ISSUE THREAD

**Issue by zcqian** [be5invis/Sarasa-Gothic#375]
for example the following URL
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.7/Sarasa-TTC-1.0.7-Unhinted.7z
does not exist

The correct URL is
https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.7/Sarasa-TTC-Unhinted-1.0.7.7z

**Comment by be5invis** [comment]
Fixed
