### ISSUE TITLE
Releases Details Format Error

### ISSUE THREAD

**Issue by XHXIAIEIN** [be5invis/Sarasa-Gothic#376]
<img width="680" alt="Snipaste_2024-03-19_00-01-34" src="https://github.com/be5invis/Sarasa-Gothic/assets/45864744/572bc33d-7edf-4916-8326-5c3feaf8bf0e">

**Comment by be5invis** [comment]
It is truncation error by GitHub. Opening the release page would see it in full.
Resolve as non-fixable.
