### ISSUE TITLE
1.0.7 Gothic 和 Ui 的数字和英文是什么

### ISSUE THREAD

**Issue by letsky192** [be5invis/Sarasa-Gothic#378]
Ui 用这个英文和数字效果感觉很好。但用作正文，1.0.7 这个数字似乎间隔太大了，看起来像插了空格。
另外请问下怎么看合成的来源是什么。

![2024-03-19_225826](https://github.com/be5invis/Sarasa-Gothic/assets/73059745/c2208ec1-7c5b-4025-98da-282347c0505a)

**Comment by be5invis** [comment]
Inter with `tnum`.

**Comment by letsky192** [comment]
[Inter font family - Features](https://rsms.me/inter/#features)
