### ISSUE TITLE
Slab-serif version of the fonts?

### ISSUE THREAD

**Issue by CXuesong** [be5invis/Sarasa-Gothic#38]
Your fonts are awesome! Especially, I've used the slab-serif font series (e.g. `Inziu IosevkaCC Slab SC`) for a long time. After seeing the [deprecation notice](https://be5invis.github.io/Iosevka/inziu.html) on the download page of `Inziu Iosevka`. I decided to move on and download the latest release of `Sarasa Gothic`, However, all the fonts seem to be sans-serif. Is this by design? Is it possible for me to do something to bring the slab-serif fonts back, or may I just switch back to `Inziu Iosevka`?

And, well, what does the "deprecation" of a font mean, compared with the common deprecation of an API/application? I thought of the font being no longer maintained, but it shouldn't break as time goes by. Is it correct?

**Comment by CyanoHao** [comment]
@CXuesong 
I have built a slab version. Would you like to try it?
[Sarasa Gothic Slab v0.5.4](https://github.com/CyanoHao/Sarasa-Gothic-Slab/releases/tag/v0.5.4-slab)
![Preview:config.json](https://user-images.githubusercontent.com/14287996/42491628-2fb21476-8448-11e8-9ce1-3fd35f162222.png)

**Comment by CXuesong** [comment]
Wow. It works like a charm. Thank you CyanoHao!
