### ISSUE TITLE
Sarasa UI TC 在 Windows 11 桌面顯示亂碼 (1.0.6 仍正常，從 1.0.7 起異常)

### ISSUE THREAD

**Issue by cwchien** [be5invis/Sarasa-Gothic#382]
您好：
感謝您製作更紗黑體相關字型，讓廣大使用者們能有一個看著舒適的操作介面。

我在 Windows 11 上總是使用 [noMeiryoUI](https://github.com/Tatsu-syo/noMeiryoUI/releases) 將操作介面字型改為 Sarasa UI TC，設定如下：
![4](https://github.com/be5invis/Sarasa-Gothic/assets/382134/60ef75ef-ec20-4361-87e7-fde19072528c)

從 1.0.7 版開始會變成亂碼 (一開始以為是更換字型時快取殘留所致，完成刪除字型->重開機->安裝字型也一樣)
![1](https://github.com/be5invis/Sarasa-Gothic/assets/382134/c297bf43-eb40-421a-8462-cb3324653c91)

但 Light 字重是正常的
![2](https://github.com/be5invis/Sarasa-Gothic/assets/382134/0af2b5fd-b4ce-440a-8465-b94d161790c7)

如果換回 1.0.6 版，則 Regular 字重可正常顯示
![3](https://github.com/be5invis/Sarasa-Gothic/assets/382134/279693b2-18b7-4f0b-81df-d2e8a576a499)

作業系統是 Windows 11 23H2，麻煩您再看看可能是什麼問題，謝謝

**Comment by letsky192** [comment]
v1.0.7 SC Ui，硬替换，显示正常。
![2024-03-24_112514](https://github.com/be5invis/Sarasa-Gothic/assets/73059745/adf43da3-c588-48c9-92cd-bf96bf296827)

**Comment by cwchien** [comment]
感謝 @letsky192 回應

我改用 Sarasa UI SC 1.0.7 並設定介面字型如下
![1](https://github.com/be5invis/Sarasa-Gothic/assets/382134/182b27c8-de9f-4fe6-a68c-27f9aca03e64)

確實可以正常顯示中文
![2](https://github.com/be5invis/Sarasa-Gothic/assets/382134/95965653-593e-4769-b273-170ab3c3a797)

不曉得 TC 編譯的過程是否有什麼問題？

**Comment by cwchien** [comment]
改用 Sarasa Gothic TC 1.0.8 可正常顯示

**Comment by cwchien** [comment]
改用 Sarasa Gothic TC 1.0.8 可正常顯示
