### ISSUE TITLE
没有中英文合并的字体吗?(Is there no font that combines Chinese and English?)

### ISSUE THREAD

**Issue by 107295472** [be5invis/Sarasa-Gothic#386]
想写代码用一种等宽字体，中英文合并的(I want to write code using a fixed-width font, combining Chinese and English.)

**Comment by Crystal-RainSlide** [comment]
你试过了吗？

**Comment by DOSforever** [comment]
啥意思？没看明白，不是任何一种字体都是可以显示等宽的中英文字符的吗？
只不过字形不一样 [https://github.com/be5invis/Sarasa-Gothic/issues/361#issuecomment-1903855343](https://github.com/be5invis/Sarasa-Gothic/issues/361#issuecomment-1903855343)

**Comment by 107295472** [comment]
现在用2个，SarasaUiSC-Regular和SarasaTermSC-Regular
