### ISSUE TITLE
现在的版本是不是对小字号优化得不好？

### ISSUE THREAD

**Issue by DOSforever** [be5invis/Sarasa-Gothic#387]
我现在用 1.x 版发觉在文本编辑器或命令行中用 12 号左右大小的字号没有以前用 0.31 版清晰，特别是中文字符，总觉得字体比较毛糙，如果是用在视频播放中的字幕则字体显示很清晰、圆润，反正就是看上去比较舒服，可能是字幕显示比文本编辑器中字号要大许多的因素。是不是现在新版的对小号字体没以前优化得好的原因？
使用环境 Windows 7

**Comment by rintrint** [comment]
我還在用0.40.3版本，感覺沒必要追求最新的，不然就要挨個試，找新版裡面問題比較少的

**Comment by Sodacooky** [comment]
1.0开始在btop之类的带盲文控制符(大概？)和htop里都会异常，但是我用的Slab SC的源头Invoseka Slab就没有这样的问题。
所以还是用0.40吧
