### ISSUE TITLE
[question] Do we support stylistic sets and character variants?

### ISSUE THREAD

**Issue by Alecton4** [be5invis/Sarasa-Gothic#388]
I tried enabling some of the [stylistic sets](https://github.com/be5invis/Iosevka/blob/main/doc/stylistic-sets.md) and [character variants](https://github.com/be5invis/Iosevka/blob/main/doc/character-variants.md) in VSCode, but none of them worked :(

**Comment by be5invis** [comment]
No. Otherwise there will be too many glyphs.
