### ISSUE TITLE
It is difficult for me to distinguish between "l2" and "12".

### ISSUE THREAD

**Issue by 161043261** [be5invis/Sarasa-Gothic#389]
It is difficult for me to distinguish between "l2" and "12". I sincerely hope that you can improve the design of l letter in the font, specifically you can refer to the practice of JetBrains Mono.

**Comment by hunderlinehh** [comment]
![image](https://github.com/be5invis/Sarasa-Gothic/assets/106456682/7ab9fbb3-8a4a-4461-afed-4e528d3c273f)
I'm using Sarasa Gothic UI SC, and I can easily distinguish "I2" and "12"

**Comment by 161043261** [comment]
<img width="148" alt="image" src="https://github.com/be5invis/Sarasa-Gothic/assets/153521102/f789542d-11f5-4f9b-ba7d-2a0eeb55242d">
I think they are similar tho.
I'm using Sarasa Fixed SC.

**Comment by atauzki** [comment]
Seems to rebuild yourself, Iosevka can set font features, but Sarasa not.
![image](https://github.com/be5invis/Sarasa-Gothic/assets/19769843/309779e4-5142-4967-ae00-472a93671753)

by this vscode settings:
```
"editor.fontLigatures": "'calt' off, 'cv37' 10"
```
font feature detail: https://typeof.net/Iosevka/customizer

**Comment by 161043261** [comment]
> Seems need to rebuild the font yourself, Iosevka can set font features, but Sarasa not. ![image](https://private-user-images.githubusercontent.com/19769843/329781411-309779e4-5142-4967-ae00-472a93671753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTQ3MDgsIm5iZiI6MTcxNTUxNDQwOCwicGF0aCI6Ii8xOTc2OTg0My8zMjk3ODE0MTEtMzA5Nzc5ZTQtNTE0Mi00OTY3LWFlMDAtNDcyYTkzNjcxNzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDExNDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDE4M2FiZGU3ZTlhOTJiMzM4MDUyOWZjZjIyNWIwNGJjNzc4ZTg5Zjc2NmExMDBhNTIxMTllNTE5NmQwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YJRV2nj5KIJacnk8UouayhH7Ctvd1QYwATVZ8GII1q4)
> 
> by this vscode settings:
> 
> ```
> "editor.fontLigatures": "'calt' off, 'cv37' 10"
> ```
> 
> font feature detail: https://typeof.net/Iosevka/customizer

Sincerely THANKS A LOT 👍
