### ISSUE TITLE
Questions about mono font

### ISSUE THREAD

**Issue by ZeppLu** [be5invis/Sarasa-Gothic#39]
I want to use it in powershell, and I see these options:
- Sarasa Term CL/J/SC/TC
- 等距更纱黑体 CL/J/SC/TC
- 等距更纱黑体 T CL/J/SC/TC

So I have two questions:
- what's the differences between them
- how can I use them in windows terminal like cmd/powershell (if I just select and apply, it would fallback to 新宋体)

OS version: Windows 10 1709 家庭中文版

**Comment by be5invis** [comment]
https://github.com/be5invis/Sarasa-Gothic/blob/master/README.md#what-are-the-names
⬆️ Please read.

For console you can install them and select one of them directly in the Console’s properties.

**Comment by ZeppLu** [comment]
As I said, if I just select and apply, it would fallback to 新宋体

The following GIF may offer a better explaination:

![d](https://user-images.githubusercontent.com/17007549/40738665-bcffb4f6-6476-11e8-851a-563db31e177a.gif)

I firstly select MS Gothic, which works well. But after Sarasa Term CL is selected, font fallbacks to 新宋体.

**Comment by be5invis** [comment]
You have to select Sarasa Mono SC. CL is a Traditional Chinese font which cannot be used for Simplified Chinese Console.

**Comment by ZeppLu** [comment]
Well, I just prefer old-style Chinese characters... It works, thanks
