### ISSUE TITLE
Problems with font display in version 1.0.11

### ISSUE THREAD

**Issue by 1nj0k** [be5invis/Sarasa-Gothic#392]
I use Arch Linux.

In version 1.0.11, I use kate with Sarasa Mono SC, the display has bugs.
![Screenshot_20240511_112315](https://github.com/be5invis/Sarasa-Gothic/assets/13143916/41955a56-9f9d-465c-8694-c1048620f0b6)

However, I downgrade to version 1.0.10, the display is OK.
![Screenshot_20240511_113248](https://github.com/be5invis/Sarasa-Gothic/assets/13143916/e98aa85c-30c5-4ca7-a5ba-a2e919872702)

There might be some bugs in version 1.0.11?

**Comment by go0d1uck** [comment]
same problems on chrome.

**Comment by Cycatz** [comment]
Same problem on emacs

**Comment by syimyuzya** [comment]
Same problem (Linux)

Glyphs appear broken in many (if not all) applications, including several essential ones like fcitx5 (input method), Firefox, VSCode etc, in any font size below 100px or so.

**Comment by be5invis** [comment]
You can try the unhinted version instead.

**Comment by 1nj0k** [comment]
> You can try the unhinted version instead.

I tested the unhinted version, it worked fine in kate with Sarasa Mono SC. Thanks.

Will the hinted version work in Linux like version 1.0.10 in the future? Or the changes introduced in version 1.0.11 are irreversible？

**Comment by syimyuzya** [comment]
> You can try the unhinted version instead.

This is weird, as the only difference between v1.0.10 and v1.0.11 is the version of Iosevka, but glyphs from Iosevka is unaffected at all... :thinking:

Also, neither AFDKO nor ttfautohint got new releases recently (or had the machine been using older versions of AFDKO for prebuilt font releases, but updated when building v1.0.11?)

**Comment by be5invis** [comment]
@1nj0k It looks like something building was broken (maybe because I interrupted it before?)
