### ISSUE TITLE
将 Sarasa 应用为 Windows 的用户界面字体 CJK 字符显示偏高

### ISSUE THREAD

**Issue by FreshP-0325** [be5invis/Sarasa-Gothic#393]
将 Sarasa 字体应用为 Windows 的用户界面字体的话，CJK 字符的显示位置在大多数地方都比英文数字字符偏高，如图所示。我在 Windows 10 和 11，简体中文系统和日语系统都有测试过，情况一样，字体版本是 1.0.12。

请问这是正常的吗。如果我想要微调字型的垂直位置，自己重新构建字体，请问我可以修改哪里实现呢。谢谢。

![image](https://github.com/be5invis/Sarasa-Gothic/assets/17758006/f78dd65e-6ff4-48ba-aca5-70612f4f71b1)

![image](https://github.com/be5invis/Sarasa-Gothic/assets/17758006/2138b6ae-6ffd-4faa-a79e-ec605f6d927c)

如果一整行字都是英文数字的话感觉还是恰好的。

![image](https://github.com/be5invis/Sarasa-Gothic/assets/17758006/8ea4205a-bc7e-4def-b781-a2e290d6612f)

其它软件如浏览器也是同样的情况，不仅是 Windows 本身的程序有这个问题。

![image](https://github.com/be5invis/Sarasa-Gothic/assets/17758006/f13507c2-1296-49c2-b5a3-d72833e74e79)

**Comment by FreshP-0325** [comment]
目前我这边找了别的办法解决了这个问题，虽然说并不知道这种办法是不是真的最好…

1. 使用 `ttx` 工具将 Sarasa 字体的 `OS/2` 的 table 导出
2. 将 `sCapHeight` 的值改为 800
3. 保持 `sTypoDescender` 和 `usWinDescent` 的值不变
4. 将 `sTypoAscender` 和 `usWinAscent` 的值改为 `sCapHeight` 与 `usWinDescent` 之和
5. 使用 `ttx` 工具将以上改动过的 table 再合并到 Sarasa 的字体文件中

**Comment by AspirinEny** [comment]
你好，请教一下如何将自定字体应用为 Windows 的用户界面字体，用的什么工具呢？

**Comment by FreshP-0325** [comment]
> @AspirinEny 你好，请教一下如何将自定字体应用为 Windows 的用户界面字体，用的什么工具呢？

我用的是这两种办法：

1. 注册表字体别名法
a. 备份注册表 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes`
b. 在上述注册表路径新增字符串值，名称写 `Segoe UI` 等要被替换的字体名，数据写 `Sarasa Gothic` 或其它自己喜欢的字体名称
c. 重新启动系统
这样做的话比较保险，缺点是对于比较现代的 Windows 10 / 11 的 UWP 应用，甚至开始菜单、任务栏都无法生效

2. 直接覆盖系统字体名称法
针对上面的问题，我试图将 Sarasa 字体直接更名使其与系统字体名称相同
a. 使用 `ttx` 工具将要被替换的字体的**所有粗细变种**，以及 Sarasa 字体的 `name` 的 table 导出
b. 将不同粗细的 `name` table 对应替换到 Sarasa 的 table 当中，最主要是换掉名称，粗细和是否斜体部分，区分大小写
c. 用 `ttx` 工具将新的 table 合并到 Sarasa 字体里
d. 用 `otf2otc` 工具将多个 ttf 文件压缩成一个 ttc，缩小了文件大小也方便维护
e. 将处理过的字体安装到系统当中
f. 备份注册表 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`
g. 在上述注册表路径将已有的，要被替换的字体的字符串值里的数据，设为空白
h. 最好再设置一下 FontLink，但是这部分我还没研究过
这样做的话风险比较大，建议先在虚拟机里试验好了再实机安装。如果被替换的字体，粗细变种没有被替换完整，可能还是会出现原来的字体，需要多次尝试。而且有个别软件可能还是会缺少字型然后显示方块或 "NO GLYPH"。这样替换字体的话，也会影响到 Windows Sandbox 内的字体正常显示

**Comment by be5invis** [comment]
The goal of Sarasa is not being used as a replacement font.
You can import some metrics (in `hhea` or `OS/2`) of the source font though.
Resolve as out of scope.

**Comment by Mr-Drinking** [comment]
> 目前我这边找了别的办法解决了这个问题，虽然说并不知道这种办法是不是真的最好…
> 
> 1. 使用 `ttx` 工具将 Sarasa 字体的 `OS/2` 的 table 导出
> 2. 将 `sCapHeight` 的值改为 `800`
> 3. 保持 `sTypoDescender` 和 `usWinDescent` 的值不变
> 4. 将 `sTypoAscender` 和 `usWinAscent` 的值改为 `sCapHeight` 与 `usWinDescent` 之和
> 5. 使用 `ttx` 工具将以上改动过的 table 再合并到 Sarasa 的字体文件中

我做了个[脚本](https://github.com/Mr-Drinking/Windows-System-Font-Modifier)，你可以看一下
