### ISSUE TITLE
为什么小写 “x” 字形有时候会不一样

### ISSUE THREAD

**Issue by kidzgy** [be5invis/Sarasa-Gothic#396]
Title:Why do lowercase "x" glyphs sometimes look different?

![2024-05-28_145732](https://github.com/be5invis/Sarasa-Gothic/assets/6967810/b5051620-3119-4586-a4a3-d03f7d51ca07)

测试链接：https://www.423down.com/search/Autodesk
字体版本：SarasaGothicSC-TTF-1.0.13

仔细看小写字母“x”，两个链接的x的字形是不一样的，不知道为什么要这样设计，感觉好别扭，能不能取消掉这种设计呢

-------------------------------------------------------------

Test link: https://www.423down.com/search/Autodesk
Font Version: SarasaGothicSC-TTF-1.0.13

Look carefully at the lowercase letter "x", the glyphs of the x's in the two links are not the same, I don't know why they are designed this way, it feels so awkward, can we eliminate this design?

**Comment by be5invis** [comment]
Inter's "feature".

**Comment by kidzgy** [comment]
I tried Sarasa UI SC and there is no such problem.

The problem with Sarasa Gothic SC is not the x-glyph transformation, but the instability of this transformation, where the same “x64” field is deformed in some cases and not in others.
