### ISSUE TITLE
Inter's font-feature-settings feature cannot be used.

### ISSUE THREAD

**Issue by kidzgy** [be5invis/Sarasa-Gothic#397]
Test font: 
SarasaGothicSC-TTF-1.0.13
SarasaUiSC-TTF-1.0.13

As shown in the https://rsms.me/inter/#features , using css styles, you can change the glyphs of some characters.

For example `font-feature-settings: 'cv08' 1,'cv05' 1; ` can Upper-case i with serif and Lower-case L with tail.

But it doesn't work for Sarasa fonts.

**Comment by be5invis** [comment]
I dropped Inter's CV/SS features **on purpose** (as well as Iosevka's) to reduce glyph count.
Resolve as by design.

**Comment by kidzgy** [comment]
I think it is very necessary to restore the glyph characteristics of "I" and "l" because these two characters are very difficult to distinguish under normal browsing.
