### ISSUE TITLE
我是小萌新...这个如果要替换windows下的全局字体方案如何操作呢?

### ISSUE THREAD

**Issue by Inf0Kill** [be5invis/Sarasa-Gothic#40]
我看雅黑有三个相关的字体文件MSYH MSYHL MSYHBD,一时竟不知如何下手,因为如果都替换的话没有light字体让我替换.另外还有宋体用不用替换?我试了试一替换就变豆腐块...

**Comment by be5invis** [comment]
打消这个想法吧，这个不能替换。
