### ISSUE TITLE
Idea2020.3.4上用的Sarasa Mono SC，为什么中文字体的字间距特别大？VSCode正常

### ISSUE THREAD

**Issue by ShrekerNil** [be5invis/Sarasa-Gothic#401]
我在VSCode上使用字体`Sarasa Mono SC`是正常的，但是在 Idea 2020.3.4 上配置后出现汉字的字间距特别大，没有其他的选项可以调整，请问这个怎么办，有哪位知道怎么办？字体版本：1.0.17
VSCode效果：
![微信截图_20240806175740](https://github.com/user-attachments/assets/6398dc50-c95e-4c9d-bced-4877d159fb8e)

Idea效果
![微信截图_20240806175718](https://github.com/user-attachments/assets/77f3cadf-ee38-42db-8d6c-261fcac3e2eb)

**Comment by ShrekerNil** [comment]
字体版本：1.0.17

**Comment by shuyuwa** [comment]
试试在setting->edit->font里面勾选Show only monospaced font？
