### ISSUE TITLE
remove emoji from Sarasa Mono

### ISSUE THREAD

**Issue by bigheadghost** [be5invis/Sarasa-Gothic#404]
SarasaMonoSC-TTF-1.0.19 here

Sarasa Mono contains emojis like 🙂{U+1F642}   🙃{U+1F643}, but displays in black and white, while Segoe UI Emoji displays them as colorful.

So how to force Sarasa Mono not to display emojis and leave that to Segoe UI Emoji?
or remove them from Sarasa Mono?

**Comment by be5invis** [comment]
Fixed in 1.20
