### ISSUE TITLE
中文标点符号请保持全宽

### ISSUE THREAD

**Issue by lost-bytes-x** [be5invis/Sarasa-Gothic#405]
SarasaMono 有时会将中文标点符号显示成一个字符宽度，例如在 `，` 前的 `）`。这会导致以下困扰：

1. 当中文 `）` 被渲染为半宽时，用肉眼很难与半宽的英文 `)` 区分开；
2. 在很多 IDE 中，格式化时，中文标点符号被认为占用两个字符宽度。从而导致格式化后内容不对齐；

希望出一款所有中文标点符号保持以全宽形式渲染的字体，万分感谢。

SarasaMono sometimes displays Chinese punctuation as single-character width, such as the `）` before `，`. This causes the following issues:

1. When the Chinese `）` is rendered as half-width, it becomes difficult to distinguish from the half-width English `)` by eye;
2. In many IDEs, when formatting code, Chinese punctuation is considered to take up two characters in width, leading to misalignment after formatting.

I hope a font can be developed that ensures all Chinese punctuation is rendered in full-width form. Thank you very much.

**Comment by jtc1246** [comment]
可以这样操作：

1. 先下载你需要字体的ttf版本
2. `pip install fonttools`
3. `ttx <path_to_ttf>`
4. 然后会得到一个ttx文件，格式类似于xml
5. 用文本编辑器打开，搜索GPOS和GSUB，把<GPOS> </GPOS>中间的部分删掉，<GSUB> </GSUB>中间的部分也删掉。
6. `ttx <path_to_ttx>`
7. 然后会得到修改后的ttf文件，这个就可以用了。但是在chrome里面会出现OTS parsing error的问题，所以需要把ttf转换成woff2，再把woff2转回ttf

**Comment by lost-bytes-x** [comment]
👍 @jtc1246 谢谢~ 我试下

**Comment by be5invis** [comment]
Need to fix the char categorizer to drop `halt` for `（）`.
