### ISSUE TITLE
能否推出只有英文等距字体？ Can  release a font that is only isometric in English?

### ISSUE THREAD

**Issue by kidzgy** [be5invis/Sarasa-Gothic#406]
现在的字体要么中英文全不等距，要么就是2英文等距1中文，似乎没有一款字体是只有英文字体等距。目前的等距字体中，英文字体看起来偏瘦，而且与中文搭配起来着实有点别扭。况且很多软件是不支持混合字体的，比如无法使用“Consolas+微软雅黑”，除非是用Word或css里的font-family属性，或者单独将这两个字体做个合并。

所以，我在设想，能不能推出一个只有非中文字体是等距的？（我的意思是，1个字符的非中文字体等距，2个字符的中文字体等距，但是2个非中文字体的宽度不等于1个中文字体的宽度）

Nowadays fonts are either all non-isometric in English and Chinese, or 2 English isometric and 1 Chinese, and none of the fonts seem to be isometric in English only. Among the current isometric fonts, the English fonts look thin and a bit awkward to match with the Chinese ones. Moreover, many software does not support mixed fonts, such as the inability to use “Consolas + Microsoft Yahei”, unless it is using Word or css in the font-family attribute, or separate the two fonts to do a merger.

So, I'm thinking, can we introduce a non-Chinese fonts only isometric? (I mean, 1 character non-Chinese fonts are isometric, 2 characters Chinese fonts are isometric, but the width of 2 non-Chinese fonts is not equal to the width of 1 Chinese font)

**Comment by CT-ABT** [comment]
Well, since all CJK characters are monospaced by nature, it then sounds like what you need is just one monospaced font for Western characters that suits your eyes, and then leave all the CJK characters to be felt back to whatever CJK font you like. This can be easily achieved if your editor supports font list and you list that monospaced Western font that does not support CJK characters in the first place.

**Comment by kidzgy** [comment]
> Well, since all CJK characters are monospaced by nature, it then sounds like what you need is just one monospaced font for Western characters that suits your eyes, and then leave all the CJK characters to be fallen back to whatever CJK font you like. This can be easily achieved if your editor supports font list and you list that monospaced Western font that does not support CJK characters in the first place.

What you mentioned can only be realized in the web interface through css style, or word file CJK and English font mix.

At present, a single editor can only support the modification of individual fonts, can not realize the mixed fonts. Unless, they use the font editor, the two fonts to do a merger, but the general user in the merger of fonts will appear a lot of problems.

**Comment by pffang** [comment]
> > Well, since all CJK characters are monospaced by nature, it then sounds like what you need is just one monospaced font for Western characters that suits your eyes, and then leave all the CJK characters to be fallen back to whatever CJK font you like. This can be easily achieved if your editor supports font list and you list that monospaced Western font that does not support CJK characters in the first place.
> 
> What you mentioned can only be realized in the web interface through css style, or word file CJK and English font mix.
> 
> At present, a single editor can only support the modification of individual fonts, can not realize the mixed fonts. Unless, they use the font editor, the two fonts to do a merger, but the general user in the merger of fonts will appear a lot of problems.
> 
> In fact, I'm looking forward to having a font that looks like this: Sarasa Gothic + Iosevka Extended

不理解，这个字体的英文部分就是源自Iosevka啊，你说的Sarasa Gothic + Iosevka Extended是指什么？
我确实见过英文宽度是约2/3汉字宽度的中英文混合字体。不如说不做处理的话，原本Source Han和英文等宽字体混合通常都这类。汉字和英文宽度2:1反而是调整过的。
我在GitHub上就见过能满足你需求的字体，但这个需求实在太少见了，对我来说也不实用，所以我没有收藏，不记得名字了，你可以找找。

**Comment by kidzgy** [comment]
> > > Well, since all CJK characters are monospaced by nature, it then sounds like what you need is just one monospaced font for Western characters that suits your eyes, and then leave all the CJK characters to be fallen back to whatever CJK font you like. This can be easily achieved if your editor supports font list and you list that monospaced Western font that does not support CJK characters in the first place.
> > 
> > 
> > What you mentioned can only be realized in the web interface through css style, or word file CJK and English font mix.
> > At present, a single editor can only support the modification of individual fonts, can not realize the mixed fonts. Unless, they use the font editor, the two fonts to do a merger, but the general user in the merger of fonts will appear a lot of problems.
> > In fact, I'm looking forward to having a font that looks like this: Sarasa Gothic + Iosevka Extended
> 
> 不理解，这个字体的英文部分就是源自Iosevka啊，你说的Sarasa Gothic + Iosevka Extended是指什么？ 我确实见过英文宽度是约2/3汉字宽度的中英文混合字体。不如说不做处理的话，原本Source Han和英文等宽字体混合通常都这类。汉字和英文宽度2:1反而是调整过的。 我看了一下，原始的Source Han Mono中英文宽度比例大概就是3:2，你可以试试。

Iosevka原版字体瘦小，很起来很费眼睛。Extended字宽我觉得恰到好处。我的应用场景就是方便记事本软件使用。

**Comment by pffang** [comment]
> > > > Well, since all CJK characters are monospaced by nature, it then sounds like what you need is just one monospaced font for Western characters that suits your eyes, and then leave all the CJK characters to be fallen back to whatever CJK font you like. This can be easily achieved if your editor supports font list and you list that monospaced Western font that does not support CJK characters in the first place.
> > > 
> > > 
> > > What you mentioned can only be realized in the web interface through css style, or word file CJK and English font mix.
> > > At present, a single editor can only support the modification of individual fonts, can not realize the mixed fonts. Unless, they use the font editor, the two fonts to do a merger, but the general user in the merger of fonts will appear a lot of problems.
> > > In fact, I'm looking forward to having a font that looks like this: Sarasa Gothic + Iosevka Extended
> > 
> > 
> > 不理解，这个字体的英文部分就是源自Iosevka啊，你说的Sarasa Gothic + Iosevka Extended是指什么？ 我确实见过英文宽度是约2/3汉字宽度的中英文混合字体。不如说不做处理的话，原本Source Han和英文等宽字体混合通常都这类。汉字和英文宽度2:1反而是调整过的。 我看了一下，原始的Source Han Mono中英文宽度比例大概就是3:2，你可以试试。
> 
> Iosevka原版字体瘦小，看起来很费眼睛。Extended字宽我觉得恰到好处。我的应用场景就是方便记事本软件使用。

那你可以直接用Iosevka Extended啊，记事本的话你改一下Windows注册表，把你的英文字体的fallback设置成你想用的中文字体就可以，参考https://superuser.com/questions/396160/how-to-change-configure-font-fallback

**Comment by fixet78** [comment]
> 1个字符的非中文字体等距，2个字符的中文字体等距，但是2个非中文字体的宽度不等于1个中文字体的宽度
> 1 character non-Chinese fonts are isometric, 2 characters Chinese fonts are isometric, but the width of 2 non-Chinese fonts is not equal to the width of 1 Chinese font

中文（CJK）这类方块字天生是等距的，而西文的等距字体虽不少，但**中英文严格等距（2:1）的字体**很罕见（**西文字形宽高比0.5**），这类中英文严格等距的字体在代码编辑中很有用，此项目就是专为此目的优化过的；西文字形宽高比0.5看上去一定是“瘦高”的。

而你的需求，随便将一个你喜欢的西文等距字体合并到任何一个中文字体中都能实现，你只是喜欢此字体的中文部分？那就是用的思源黑体，你在思源黑体基础上合并一个你喜欢的西文字体就可以了呀。

**Comment by cocoAutumn** [comment]
我的需求比这位楼主的更复杂一些，首先我和TA同样不是特别习惯中英 2:1 的瘦高英文（目前只有 LigConsolata 用的还算舒服，代价是英文比较矮需要调大字号），其次我需要【非 ASCII 标点符号】的字形和宽度都符合简体中文的标准规范（注意不是任何网络社区的规范），也就是像省略号、间隔号、单双引号、破折号（em-dash）这些，楼主所说的 css font-family 正好处理不了这个问题（好像有了个新的特性叫 unicode-range 但是只能用于前端）。

**Comment by ShikiSuen** [comment]
需求复杂的想找事主或专人订制服务的话，怎么着也得拿钱给对方意思一下才说得过去吧？

**Comment by fmnijk** [comment]
還是手動合併字體吧，這樣妳可以用任何一款你喜歡的等距英文字體和更紗黑體的中文部分合併

**Comment by be5invis** [comment]
I think your demand could be implemented by simply combining an western monospace font with a CJKV font together using a tool like _pyftmerge_.
Resolve as out of scope.
