### ISSUE TITLE
群主，请问下， CL/HC/J/K/SC/TC  带 Unhinted 和不带的，都是什么意思？

### ISSUE THREAD

**Issue by HeliusHao** [be5invis/Sarasa-Gothic#408]
实在是看不懂应该下哪个版本，谢谢

**Comment by CrotchBurnt** [comment]
CL 传统字形
HC 香港繁体
J 日文
K 韩文
SC 简体中文
TC 台湾繁体
高分辨率屏幕用unhinted的就行，简单理解hinted就是在低分辨率下会修改一些笔画，让字看的更清楚，高分辨率屏幕就不用了

**Comment by HeliusHao** [comment]
感谢解答。

**Comment by DOSforever** [comment]
> 高分辨率屏幕用unhinted的就行，简单理解hinted就是在低分辨率下会修改一些笔画，让字看的更清楚，高分辨率屏幕就不用了

为什么这个帖子里的解释和你的有些矛盾？
https://github.com/be5invis/Sarasa-Gothic/issues/364#issuecomment-1903900027
他的意思是一般不用 Unhinted ，而你的意思是高分辨率屏幕用Unhinted 。我想现在一般用的屏幕都是高分辨率，那么这“一般”到底是用还是不用 Unhinted ？
