### ISSUE TITLE
unslashed zero

### ISSUE THREAD

**Issue by WaffleLapkin** [be5invis/Sarasa-Gothic#413]
This font comes with slashed 0 by default. This is nice, however in some cases I want an _un_slashed 0, how can I get it?

I found #303, but the solution from there doesn't work anymore, I tried setting `cv71` to `1` in both vscode and typst, and neither showed any changes, so I assume something changed since then...

Could be nice to have all the OT features documented somewhere.

**Comment by be5invis** [comment]
Sarasa doesn't have variant support now (due to overflow of GID).
VSCode support specifying font fallback so you can add _Iosevka_ before this font and apply `cv10` to `1`.
