### ISSUE TITLE
orgmode table 中的希腊字母造成表格不能对齐

### ISSUE THREAD

**Issue by et2010** [be5invis/Sarasa-Gothic#42]
就像下图所示，看来Emacs把希腊字母当成两个字符宽度了，虽然实际上显示只占一个字符宽度，这个有办法解决吗？

![image](https://user-images.githubusercontent.com/11584902/41171218-51b1aae8-6b82-11e8-8cb7-c2733360f0a9.png)

更多讨论，见这里

https://emacs-china.org/t/topic/2613?source_topic_id=6059

**Comment by be5invis** [comment]
As a type designer I cannot make Greeks to be too wide. You may need to contact Emacs (or the author of the plugin)

发自我的 iPhone

在 2018年6月9日，01:14，et2010 <notifications@github.com<mailto:notifications@github.com>> 写道：


就像下图所示，看来Emacs把希腊字母当成两个字符宽度了，虽然实际上显示只占一个字符宽度，这个有办法解决吗？

[image]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11584902%2F41171218-51b1aae8-6b82-11e8-8cb7-c2733360f0a9.png&data=02%7C01%7C%7C04cba8129cd445940af608d5cd634e61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636640748752073825&sdata=bqrdc0etVDYtpCOL4EsRylZ07HzVMDwFgCAlqCvEPq8%3D&reserved=0>

更多讨论，见这里

https://emacs-china.org/t/topic/2613?source_topic_id=6059<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Femacs-china.org%2Ft%2Ftopic%2F2613%3Fsource_topic_id%3D6059&data=02%7C01%7C%7C04cba8129cd445940af608d5cd634e61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636640748752073825&sdata=ifx73WFoRm3OTsrBhRxkXUBl8fxtrqR8VN49vrg%2F%2Bvw%3D&reserved=0>

**Comment by et2010** [comment]
感谢您的快速回复，但是我看到论坛里有人说 Inziu_Iosevka_Slab_SC 12 号字体可以实现希腊字符等宽，这是什么原理？更纱黑体不能添加支持吗？

**Comment by be5invis** [comment]
I do not know. I think you should contact the author of Org mode and give options to decide, in your current mono-space font, whether non-ASCII European characters are full-width.

**Comment by et2010** [comment]
Thank you for your reply. I'll try your suggestions. May I close this?
