### ISSUE TITLE
Is this font provided as ttf-font?

### ISSUE THREAD

**Issue by acgtyrant** [be5invis/Sarasa-Gothic#43]
Someone tell me this is an OTC font which is is not suitable to provide as ttf-font.

**Comment by be5invis** [comment]
It is provided in both TTF and TTC.

发自我的 iPhone

在 2018年6月13日，08:45，Isaac Ge <notifications@github.com<mailto:notifications@github.com>> 写道：


Someone tell me this is an OTC font which is is not suitable to provide as ttf-font.

**Comment by acgtyrant** [comment]
So only the ttc is an OTF font while the ttf can provide the true ttf-font?

**Comment by be5invis** [comment]
Both are TTF outline.

发自我的 iPhone

在 2018年6月13日，09:03，Isaac Ge <notifications@github.com<mailto:notifications@github.com>> 写道：


So only the ttc is an OTF font while the ttf can provide the true ttf-font?
