### ISSUE TITLE
Korean Hangul

### ISSUE THREAD

**Issue by Immueggpain** [be5invis/Sarasa-Gothic#45]
I just found that the Hangul characters are not shown when using Sarasa fonts. But it's ok with Source Han Sans. Any idea what's wrong?

**Comment by be5invis** [comment]
There is no GID room for Korean support.

发自我的 iPhone

在 2018年6月17日，16:00，Immueggpain <notifications@github.com<mailto:notifications@github.com>> 写道：


I just found that the Hangul characters are not shown when using Sarasa fonts. But it's ok with Source Han Sans. Any idea what's wrong?

**Comment by Immueggpain** [comment]
Thanks for clearing that up.
