### ISSUE TITLE
于Notepad++ 中使用该款字型后出现异常卡顿的情况

### ISSUE THREAD

**Issue by xFelino** [be5invis/Sarasa-Gothic#46]
于Notepad++ 中使用该款字型后出现异常卡顿的情况，表现为上下翻页过程中，文本行缓慢逐行刷新，改用其他字型后未见该情况。

**字型信息**
sarasa-gothic-ttc-0.5.4

**Notepad++ 信息**
Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by devld** [comment]
Hi，我在 git-bash(其他 terminal 也有这个问题，比如 MobaXterm) 中也遇到了这个问题。但仅仅首次'渲染'时会卡顿，随后都正常。请问您解决了吗？
