### ISSUE TITLE
CAN U provide a Dockerfile to build this repo?

### ISSUE THREAD

**Issue by chenhw2** [be5invis/Sarasa-Gothic#47]
I try several times to build this repo with centos/arch linux/ubuntu. All failed.

So can u please provide a Dockerfile to build this repo?

**Comment by be5invis** [comment]
I do not use Linux actually...
Which step failed? Installing deps or what?

**Comment by chenhw2** [comment]
Fail at install ```otfcc```, ```ttfautohint```

**Comment by be5invis** [comment]
I think there are AUR packages for both the programs.

**Comment by chenhw2** [comment]
but failed both

**Comment by chenhw2** [comment]
```
==> Validating source files with sha256sums... 
    ttfautohint-1.8.1.tar.gz ... Passed
    ttfautohint-1.8.1.tar.gz.sig ... Skipped
==> Verifying source file signatures with gpg...
    ttfautohint-1.8.1.tar.gz ... FAILED (unknown public key C1A60EACE707FDA5)
==> ERROR: One or more PGP signatures could not be verified!
==> ERROR: Makepkg was unable to build ttfautohint.
==> Restart building ttfautohint ? [y/N]
==> ------------------------------------
```

**Comment by chenhw2** [comment]
seems lack of maintenance

**Comment by chenhw2** [comment]
I will try to build on windows later, Thanks a lot

**Comment by be5invis** [comment]
I looked at the packages and they are updated to the latest version.
I think you can learn how to add AUR public keys...
