### ISSUE TITLE
Please add Unicode 2AF4 char.

### ISSUE THREAD

**Issue by Magicloud** [be5invis/Sarasa-Gothic#48]
To make my code even cooler, I need to use that char as an operator. But right now, it is still a tofo.

Thanks.

**Comment by extrame911** [comment]
That character can be seen in https://unicode-table.com/cn/2AF4/

**Comment by Magicloud** [comment]
@extrame911 No. I have only system fonts, Google Noto, and Sarasa Gothic. And set browser fonts to Sarasa UI SC (Mono SC for monospace), the char is tofo.

**Comment by extrame911** [comment]
I'm not a font developer, I'm sorry I just wanted to give as much information as I know to see if it would help the author.

The Chinese version is usually updated slowly, so you can email the author to see if you can solve the problem.

**Comment by Magicloud** [comment]
@extrame911 , Ah, sorry. I thought you meant it could be displayed.

**Comment by 7sDream** [comment]
This codepoint is in [Supplemental Mathematical Operators](https://en.wikipedia.org/wiki/Supplemental_Mathematical_Operators) category, the range is U+2A00 to U+2AFF.

I checked this range, Sarasa Gothic can't show any codepoint in it. So only add one character seems like little strange.

I suggest use another fallback font to show this codepoint in VSCode, just add other font to `editor.fontFamily` config.

I found my computer has a little fonts support this codepoint using [my small script](https://github.com/7sDream/which_fonts_support).

![image](https://user-images.githubusercontent.com/7822577/47796850-1db80c00-dd60-11e8-983b-6100de92b6ff.png)

And then use `"editor.fontFamily": "'Sarasa Mono SC', 'STIXGeneral' , monospace"` for shows it, this is the preview:

![image](https://user-images.githubusercontent.com/7822577/47796530-7c30ba80-dd5f-11e8-9446-2b38068fe941.png)

It shows up, but can't achieve the "Mono".

So, if you just wan't to see it, you can try add a second font. But if you want mono also, it's indeed some difficulty here.

**Comment by Magicloud** [comment]
Thanks for the info, especially the little script.

**Comment by Magicloud** [comment]
Suddenly found that this char can be shown in Chromium in ArchLinux. But no idea which font provides that. Tried the script, failed.

**Comment by 7sDream** [comment]
You can try find it in Dev tools of chromium. In the element tab，select the element contains this character, then scroll to the bottom of styles view, It will shows what font chromium use to render the text.

**Comment by Magicloud** [comment]
Universalia—Network resource(1 glyph)
Let me see if I can use it.
