### ISSUE TITLE
Display issue in GUI of MacVim

### ISSUE THREAD

**Issue by tyfulcrum** [be5invis/Sarasa-Gothic#5]
Sarasa Gothis version: 0.2.1
Inziu Iosevka version: 1.13.2
OS version: macOS 10.13
MacVim version: 8.0.1207 Built from source using Homebrew on 2017-10-27 at 12:02:33 with: --with-override-system-vim
iTerm2 version: 3.1.4

Screenshot of issue (using Sarasa Mono SC): 
![Screenshot of issue](https://i.imgur.com/LCtrLr4.png)

Everything ok when using Inziu Iosevka SC: 
![Screenshot of MacVim GUI Version using Inziu Iosevka SC](https://i.imgur.com/TOyuEIz.png)

Everything ok in iterm2 using Sarasa Mono SC: 
![Screenshot of iterm2 using Sarasa Mono SC, which is OK](https://i.imgur.com/qckHND8.png)

Thanks a lot for your work on Inziu Iosevka and Sarasa Gothic.

**Comment by be5invis** [comment]
Looks like that in Pic 1, your editor DOES NOT load Sarasa.
Did you set an incorrect font name?

**Comment by tyfulcrum** [comment]
vimrc in Pic 1: 

`set guifont=Sarasa\ Mono\ SC:h16`

I used the name displayed in Font Book.app. 

vimrc in Pic 2: 

`set guifont=Inziu\ Iosevka\ SC:h16`

And if I set "Sarasa Gothic" as font of GUI: 

`set guifont=Sarasa\ Gothic\ SC:h16`

GUI would looks like that: 

![Screenshot of MacVim using Sarasa Gothic](https://i.imgur.com/VEG6ouc.png)

I think MacVim did load Sarasa, because if I use "asdfasdf" as font name intead in vimrc, GUI of editor would looks like this: 

![Screenshot of MacVim using default font](https://i.imgur.com/jjroGzg.png)

**Comment by be5invis** [comment]
@tyfulcrum The glyphs in P1 are **not** from Sarasa, maybe it cannot understand your files?
What is the version you installed? If you installed the TTC version, maybe you can update to the latest TTF version. It takes more disk space but more compatible.

**Comment by tyfulcrum** [comment]
I test again using TTC version 0.3.0 in gvim under openSUSE Tumbleweed (xfce) and no error found. I also test it in MacVim under latest offical binary relase (I used homebrew version before) and the same error occured. I even removed .vim and commented all content in .vimrc except "set guifont". I reboot my computer too. So I'm not sure if there are something wrong with my OS or it's a bug of MacVim. Maybe we can wait for other user report this problem (if it does exist) .
