### ISSUE TITLE
Some full-width charactors' width probably have some problem. (Not really equal to 2 half-width characters)

### ISSUE THREAD

**Issue by abc1236762** [be5invis/Sarasa-Gothic#51]
For example, in Notepad++ with 4 half-width tabs.
At line 1, `イヤイヤイヤイヤイヤイヤイヤ`should be 14 full-width (28 half-width), it width should equal to 28 half-width whitespaces and 7 tabs but actually it doesn't. Contrast line 1 with line 2 and line 3 can observe this problem quickly.
![default](https://user-images.githubusercontent.com/11353779/44948185-0043f000-ae4c-11e8-8bba-529e65490387.png)

**Comment by 7sDream** [comment]
![image](https://user-images.githubusercontent.com/7822577/47806087-d50a4e00-dd73-11e8-9799-fcdbc35fd96b.png)

Reproduce this on CotEditor, but not on VSCode, in macOS.

**Comment by be5invis** [comment]
It looks like the editor applied kerning on Kana?

**Comment by abc1236762** [comment]
No problem on Inziu Iosevka, so I temporarily use Inziu IosevkaCC TC until this bug fixed.

**Comment by be5invis** [comment]
This is kern OFF:
![image](https://user-images.githubusercontent.com/240091/47842633-3f64d200-ddf8-11e8-8236-3b8bbb804673.png)

This is kern ON:
![image](https://user-images.githubusercontent.com/240091/47842645-468be000-ddf8-11e8-8689-2ab535008543.png)

So the problem becomes: why does Notepad++ enabled kern?
