### ISSUE TITLE
windows平台下jetbrain系IDE的乱码问题

### ISSUE THREAD

**Issue by shuaihuaiyi** [be5invis/Sarasa-Gothic#52]
在使用本字体时，将抗锯齿方式设为subpixel就会触发，其它字体都没问题
![](https://user-images.githubusercontent.com/14048129/45854994-8afb7900-bd80-11e8-96bb-c1f3e50e6c12.jpg)

**Comment by aenerv7** [comment]
同样遇到此问题，但是只在使用 Sarasa Mono 系列字体的时候出现过，改为 Sarasa Term 系列字体就正常了
