### ISSUE TITLE
是否有可能加入对 Homebrew 的支持

### ISSUE THREAD

**Issue by 0x11901** [be5invis/Sarasa-Gothic#54]
Iosevka 字体可以很方便的通过 Homebrew 更新，是否能把这个便利也应用在 Sarasa-Gothic 上？

**Comment by 7sDream** [comment]
应该是已经有了，我一直在用；

```bash
brew tap homebrew/cask-fonts
brew cask install font-sarasa-gothic
```

**Comment by 0x11901** [comment]
> 应该是已经有了，我一直在用；
> 
> ```shell
> brew tap homebrew/cask-fonts
> brew cask install font-sarasa-gothic
> ```

完美，还是用 Homebrew 舒服！
