### ISSUE TITLE
Change identifier of fonts for Japanese from “J” to “JP.”

### ISSUE THREAD

**Issue by cmplstofB** [be5invis/Sarasa-Gothic#56]
In Sarasa-Gothic, the fonts for Japanese has identifier "**J**." (e.g. sarasa-gothic-**j**.ttf, named "Sarasa Gothic **J**")
But I think "JP" is better than "J." There are two reasons for that;
First: According to ISO 3166-1, code of Japan is **JP**, not J. (see also: https://www.cia.gov/library/publications/the-world-factbook/appendix/appendix-d.html)
Second: In international fonts, "JP" is more used than "J." For example, Noto Sans CJK, the identifier of fonts are; **SC**, **TC**, and **JP**. (see also: https://github.com/googlei18n/noto-cjk)

**Comment by be5invis** [comment]
The identifier follows Source Han Sans' assignments: `J` for Japanese orthography but including full Unicode support, while `JP` only contains JIS subset ideographs.
Closed.

**Comment by cmplstofB** [comment]
I see. Thank you for giving satisfactory reasons!
