### ISSUE TITLE
Windows 平台 JetBrains IDE 无法选择 Sarasa Mono SC 作为编辑器字体

### ISSUE THREAD

**Issue by ZeekoZhu** [be5invis/Sarasa-Gothic#57]
![image](https://user-images.githubusercontent.com/13861843/48065806-ab837380-e206-11e8-9bc8-2a9ec6dca1d6.png)

JetBrains IDE 中找不到 Sarasa Mono SC 的选项，强行修改配置文件的话，会被设置成 Monospace

字体版本：0.6.0

**Comment by Elderry** [comment]
在我的机器上可以
![image](https://user-images.githubusercontent.com/1892221/48925970-92680b80-ef04-11e8-9df1-2f4a6073e46c.png)
Win 10 Pro 1809, Intellij IDEA 2018.3

**Comment by lizhaode** [comment]
t tc cl j 什么的这些有什么区别呀

**Comment by wang-hz** [comment]
重新安装字体，右键选择“为所有用户安装”。

**Comment by ZeekoZhu** [comment]
> 重新安装字体，右键选择“为所有用户安装”。

实测有效
