### ISSUE TITLE
Line Break problems on VScode (Windows 10)

### ISSUE THREAD

**Issue by zhanghuimeng** [be5invis/Sarasa-Gothic#58]
OS: Windows10 家庭版 17134.407
VScode: version 1.29.1 x64
Sarasa version: [0.6.0 Release](https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.6.0/sarasa-gothic-ttf-0.6.0.7z)
Using: 等距更纱黑体 SC

<img width="668" alt="alignment" src="https://user-images.githubusercontent.com/26516581/48713386-1d1de180-ec4b-11e8-8a5f-ed31e8e6d9d6.PNG">

The problem is, if I use Chinese ellipsis in the line (in VScode), most of the rightmost character will get covered by the minimap. Substituting one or two ellipsis by ordinary Chinese character will make the character reappear.

I don't know if this is a problem of VScode or Sarasa-Gothic. Sorry for the inconvenience.

**Comment by be5invis** [comment]
It's Code. Code is thinking `…` is half-width.
You can try with Sarasa Term
Closed.
