### ISSUE TITLE
idea界面显示问题

### ISSUE THREAD

**Issue by Wanghua007** [be5invis/Sarasa-Gothic#61]
![image](https://user-images.githubusercontent.com/45291196/48967590-dd297680-f01d-11e8-9560-d33d4f4074bb.png)
使用0.7.0版本，在idea的2018.3版本中（win10系统），除了HC结尾的字体，其他都是显示乱码，请问这个是idea的问题？还是字体的问题？

**Comment by Artoria-0x04** [comment]
双击字体文件点安装字体，重启idea再选看看

**Comment by Wanghua007** [comment]
![image](https://user-images.githubusercontent.com/45291196/57570517-71a15d00-7435-11e9-8bf7-2269ab1846d2.png)
使用0.8.1版本，不带后缀的字体，还是显示乱码
