### ISSUE TITLE
部分全宽度字符显示为半宽度

### ISSUE THREAD

**Issue by panjie** [be5invis/Sarasa-Gothic#62]
比如■、□、★等字符都显示为半宽的，而实际应该是全宽的。

**Comment by CyanoHao** [comment]
各种字体对这些符号的处理：[test.pdf](https://github.com/be5invis/Sarasa-Gothic/files/2627530/test.pdf)。

这样看来，Sarasa 作为一个面向编程环境的字体，将这些符号处理为半宽没有问题。

当然，如果你喜欢全宽版本的，可以考虑用 Iosevka CC 变体 build 一个 Sarasa CC。
（具体过程非常简单：Fork → 添加 Iosevka CC 源文件到 `source/` 目录下 → 改 `config.json` → build。可参考 [Sarasa-Gothic-Slab](https://github.com/CyanoHao/Sarasa-Gothic-Slab) 和 [Firasia](https://github.com/patrick330602/Firasia)。）

**Comment by panjie** [comment]
多谢回答。
因为我这里会经常碰到一些日语的代码文件，其中大量使用这些字符，而在半宽的情况下，显示都不正常。
