### ISSUE TITLE
Em Dash is showed unusual on VS Code and Notepad++.

### ISSUE THREAD

**Issue by abc1236762** [be5invis/Sarasa-Gothic#63]
I use `Sarasa MonoT TC` 0.7.0 and open font ligatures.
![default](https://user-images.githubusercontent.com/11353779/49335145-7eb65680-f622-11e8-9b20-17fa8e3a8be7.png)
Left is VS Code, right is Notepad++.
Continuous 2-3 Em Dash are only showed in 1 full-width length, and 4 Em Dash are only showed in 2 full-width length.
I closed font ligatures and this problem also exists.

In `Sarasa Mono TC` 0.7.0 and close font ligatures, also unusual in 3 Em Dash and 4 Em Dash.
![default](https://user-images.githubusercontent.com/11353779/49335252-cf2eb380-f624-11e8-9a8a-365bd5414bab.png)

In `Sarasa Trem TC`, they are normally showed.
![default](https://user-images.githubusercontent.com/11353779/49335271-71e73200-f625-11e8-9650-5cb740903f65.png)

And I suggest that in MonoT, En Dash should be shown in 1 half-width length instead of 1 full-width length to distinguish it from Em Dash, just like `Inziu IosevkaCC`.

**Comment by be5invis** [comment]
Looks like an ligation SHS built in that transforms two EM-dashes into one “two EM-dash”.


________________________________
收件人: Yù-Jǐn Lín <notifications@github.com>
发送时间: 星期日, 十二月 2, 2018 11:16
收件人: be5invis/Sarasa-Gothic
抄送: Subscribed
主题: [be5invis/Sarasa-Gothic] Em Dash cannot be showed regularly on VS Code and Notepad++. (#63)


I use Sarasa MonoT TC 0.7.0 and open font ligatures.

[default]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11353779%2F49335145-7eb65680-f622-11e8-9b20-17fa8e3a8be7.png&data=02%7C01%7C%7C3dc4b6dd3a444bcc23d508d6580484f3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636793173768262150&sdata=Y3Hsn3NWQjnvlJjVM%2B9nMbhB1yJFAy8HmBx84eAQRkI%3D&reserved=0>
Left is VS Code, right is Notepad++.
Continuous 2-3 Em Dash are only showed in 1 full-width length, and 4 Em Dash are only showed in 2 full-width length.
I closed font ligatures and this problem also exists.

And I suggest that in MonoT, En Dash should be showed in 1 half-width length not 1 1 full-width length to distinguish it from Em Dash.

―

**Comment by abc1236762** [comment]
Will this be fixed?

**Comment by be5invis** [comment]
I think it is already fixed in 0.7.2.

**Comment by abc1236762** [comment]
I just tried 0.7.2 and yes it fixed! Thanks.
But why in `Sarasa MonoT`, En Dash is fullwidth, not halfwidth like in `Inziu IosevkaCC`?
Em Dash is also fullwidth, I think why not make En Dash be halfwidth to distinguish it from Em Dash?

| Sarasa MonoT | Inziu IosevkaCC |
| - | - |
| ![default](https://user-images.githubusercontent.com/11353779/52696362-ce61b880-2fa9-11e9-85c5-c8d871823e78.png) | ![default](https://user-images.githubusercontent.com/11353779/52696387-dfaac500-2fa9-11e9-9630-2cf359c8b604.png) |

**Comment by be5invis** [comment]
I have a fix in Master. Closed.
