### ISSUE TITLE
无法正常显示声调字母

### ISSUE THREAD

**Issue by acgtyrant** [be5invis/Sarasa-Gothic#67]
我在 Chromium 用更纱黑体 UI J，我发现 http://www.zdic.net/z/1c/js/6D12.htm 和 https://hanzi.unihan.com.cn/Search?key=%E6%AF%94 都无法正常显示声调字母。

![2018-12-14-105020_375x248_scrot](https://user-images.githubusercontent.com/3921062/49980362-19e9ed00-ff8e-11e8-930f-9bb3c465d9a2.png)
![2018-12-14-105032_1011x315_scrot](https://user-images.githubusercontent.com/3921062/49980363-19e9ed00-ff8e-11e8-97ba-f93d46d3609e.png)

**Comment by CyanoHao** [comment]
这看起来不像是 Sarasa UI，Sarasa UI 的拉丁字母应该更胖一些。

**Comment by acgtyrant** [comment]
@CyanoHao 我把文泉驿字体删了，声调字母就正常显示了，谢谢你！
