### ISSUE TITLE
non-mono-space fonts have no half width single quote

### ISSUE THREAD

**Issue by TTTPOB** [be5invis/Sarasa-Gothic#68]
![image](https://user-images.githubusercontent.com/19909103/50320757-cbe26580-0508-11e9-8205-134914671969.png)

is this by design? Because I see many other Chinese fonts also don't have it. But I don't get the point why it should be like this.

**Comment by be5invis** [comment]
Have you just tried Sarasa UI?

**Comment by Risiamu** [comment]
Sorry if I’m prying, but I’m really curious about this behavior, too. Where did this design come from?
