### ISSUE TITLE
“=” character rendering weird in Android Studio between font size 15~22

### ISSUE THREAD

**Issue by b4nst0n** [be5invis/Sarasa-Gothic#7]
font size 16 it rendering like "-"
![sarasa_0](https://user-images.githubusercontent.com/11738364/32430401-1d1c0a2e-c30a-11e7-8e0e-47be41c3164b.png)
font size 15:
![sarasa_1](https://user-images.githubusercontent.com/11738364/32430404-1e0787f6-c30a-11e7-8033-dfa6b3b5b299.png)
font size 13 seems like correct:
![sarasa_2](https://user-images.githubusercontent.com/11738364/32430405-1e5eacf2-c30a-11e7-94df-de2b6e12a402.png)
adnr font size 22 seems like correct too:
![sarasa_3](https://user-images.githubusercontent.com/11738364/32430491-791f4386-c30a-11e7-821d-662a9e56acdc.png)

**Comment by b4nst0n** [comment]
I turn off Mactype and it seems all correctly now.
My mistake.

**Comment by b4nst0n** [comment]
do you have any idea about rendering weird under Mactype in Win10?
Seems other font do not have this issue.
What can I do to fix?

**Comment by NathanIceSea** [comment]
It seems all good with me, MacType 2013 with Japanese Patch(v 26) service mode,  configuration is Ftp Opt, tested on Scrivener & Android Studio
