### ISSUE TITLE
在 PHPStorm 2018.3 版本后无法选择字体了。

### ISSUE THREAD

**Issue by tlerbao** [be5invis/Sarasa-Gothic#71]
之前版本的 PHPStorm 中可以选择到 Iosevka 字体，但是现在 Iosevka 和 Sarasa-Gothic 都无法在字体列表中选择到。已经取消Show only monospaced fonts选项；这两个字体我都有安装并且在Sublime Text中可以成功使用，在最新版的PHPStorm中却找不到；请问作者知道怎么解决吗。

**Comment by CyanoHao** [comment]
It seems to be related to #57 .

**Comment by be5invis** [comment]
Report a bug to JetBrains.
Java hates modern typography.

**Comment by be5invis** [comment]
Maybe related: https://www.reddit.com/r/Windows10/comments/9o1rxb/build_1809_breaks_user_installed_fonts_for_java/
