### ISSUE TITLE
在idea中配置后，并不等宽

### ISSUE THREAD

**Issue by cwt9562** [be5invis/Sarasa-Gothic#72]
我在idea中设置为该字体后， 发现并不等宽
像图片所示，理论上民字应该和H右对齐的
试了mono、monot 都不可以

![image](https://user-images.githubusercontent.com/5601727/51900647-d12cad00-23f0-11e9-9298-0997335baa48.png)

**Comment by be5invis** [comment]
You are using an odd number of text size, where Java did bad job of halving an odd number.
THEY ROUNDED IT.

**Comment by cwt9562** [comment]
设置为14字号 确实解决了
感谢 秒回啊
