### ISSUE TITLE
PhpStorm 中文显示异常

### ISSUE THREAD

**Issue by sndwow** [be5invis/Sarasa-Gothic#73]
IDE：
PhpStorm 2018.3.4
Build #PS-183.5429.47, built on February 8, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

更纱黑体 v0.7.2

文本编码为UTF8

![default](https://user-images.githubusercontent.com/18691029/52829069-4fce5d80-3106-11e9-9522-936595b2afc6.png)

![default](https://user-images.githubusercontent.com/18691029/52829075-5361e480-3106-11e9-954f-417cf95e67e8.png)

**Comment by be5invis** [comment]
Please do not overlap install fonts because Java hates that.
**Java really hates modern typography.**
Uninstall all existing fonts, remove all Sarasa* files under `C:\Windows\Fonts`, and do a clean install.
