### ISSUE TITLE
字体的字母缩写分别代表什么

### ISSUE THREAD

**Issue by eachann1026** [be5invis/Sarasa-Gothic#74]
压缩包太太太多字体文件了 , 想知道这些字母分别都代表什么

**Comment by be5invis** [comment]
Read the README, please.


________________________________
发件人: eachann <notifications@github.com>
发送时间: 星期六, 二月 16, 2019 10:04
收件人: be5invis/Sarasa-Gothic
抄送: Subscribed
主题: [be5invis/Sarasa-Gothic] 字体的字母缩写分别代表什么 (#74)


压缩包太太太多字体文件了 , 想知道这些字母分别都代表什么

―

**Comment by AlexanderMisel** [comment]
想问一下CL T SC之类的是什么意思，readme里也没说

**Comment by Peng52050** [comment]
cl：代表 Cyrillic & Latin，包含西里尔和拉丁字符（根据「思源黑体」家族 
cl 字体定义推想，不确定在「更纱黑体」中是否亦如此）;
hc: 代表 Hong Kong Chinese（或 CJK Hong Kong），即港版汉字（根据「思源黑体」家族 hc 字体定义推想，不确定在「更纱黑体」中是否亦如此。另外「朝鲜汉字」也有一个本地化的英文名词“Hanja”，但中日港台都用意译英文单词而非本地化的特定名词表示字体名称，所以我不认为在这里 hc： 代表 Hanja Chinese，除非作者特意为之。）
j：代表 Japanese，即日文，包含和制汉字
sc：代表 Simplified Chinese，即简体中文，就是简化字
tc：代表 Traditional Chinese，即传统中文，就是繁体字（或称「正体字」）

**Comment by be5invis** [comment]
CL - Classic Orthography
SC - Simplified Chinese Orthography
TC - TW Orthography
HC - Hong Kong Orthography
J - Japan Orthography
