### ISSUE TITLE
Support multiple weights

### ISSUE THREAD

**Issue by stone-zeng** [be5invis/Sarasa-Gothic#75]
Source Han Sans itself has 7 weights, and Iosevka has even more. Have you considered to add the other weights into Sarasa Gothic?

**Comment by be5invis** [comment]
I am testing a newer version with 5 weights (EL, L, R, M, B). I will publish it soon.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/53297260-b1a16c80-3856-11e9-9bc9-6bc606722123.png)
