### ISSUE TITLE
GNOME Terminal 无法识别0.7.2版本的字体

### ISSUE THREAD

**Issue by chenzhongxiang** [be5invis/Sarasa-Gothic#76]
# GNOME Terminal 无法识别0.7.2版本的字体
* 当更新字体为0.7.2版本到我的系统中后，它无法出现在GNOME Terminal字体选择列表中。我使用的环境是Cent OS 7 并且安装了GNOME图形界面。
* 我猜测这可能和GNOME Terminal没有正确将字体识别为等宽字体有关？
* 我尝试回滚到上一个版本0.7.0则可以正常识别并使用。

**Comment by CyanoHao** [comment]
可能是 GNOME Terminal 字体选择列表的问题。
在这个列表中，思源黑体 HW 的 5 个地区版本 (2.000 OTC) 都无法识别、MS ゴシック (Windows 10 1809) 也不行。

GNOME 其他地方的字体选择列表，比如 GNOME Tweak，都是正常的。
如果强行用 dconf 把 `/org/gnome/terminal/legacy/profiles:/:<uuid>/font` 的值改成那些没有出现在字体选择列表里面的等宽字体，GNOME Terminal 完全能正常显示。

**Comment by chenzhongxiang** [comment]
新版本似乎解决了这个问题，所以我关闭该问题。有遇相同问题的更新到新版本即可。
