### ISSUE TITLE
一些字的字形问题

### ISSUE THREAD

**Issue by leviathan-n** [be5invis/Sarasa-Gothic#77]
在chrome中，Standard Serif Sans-Serif均使用更纱黑体 SC
「后」字有时候显示为
![image](https://user-images.githubusercontent.com/28513139/53882473-5ee36400-4051-11e9-872c-fc188fb5a438.png)
而有时候为
![image](https://user-images.githubusercontent.com/28513139/53882548-94884d00-4051-11e9-9003-38da39161a5d.png)

**Comment by be5invis** [comment]
Fixed in 0.8. Closed.
