### ISSUE TITLE
请问mono和term字体的长宽比能不能改

### ISSUE THREAD

**Issue by yw662** [be5invis/Sarasa-Gothic#78]
比如说半角长宽比2:1，全角长宽比1:1这样……感觉现在的mono英文有点窄

**Comment by virtualcca** [comment]
我也感觉用起来怪怪的（特别跟其他字体一对比的时候更明显觉得太窄了）

**Comment by be5invis** [comment]
The narrow aspect ratio is used to guarantee perfect alignment when you mix ideographs and latins.
