### ISSUE TITLE
What shoule be the font name of Sarasa Mono that can be used in vscode?

### ISSUE THREAD

**Issue by gnaggnoyil** [be5invis/Sarasa-Gothic#8]
What is the font name of Sarasa Mono that can be used as an option of `editor.fontFamily` in VSCode's user settings under Windows10? Like the following:

```
{
  // This setting works correctly with Wenquanyi Microhei font series.
  "editor.fontFamily": "WenQuanYi Micro Hei Mono"
}
```

I've tried `Sarasa Mono`, `Sarasa Mono SC` and `更纱黑体` but none of them works.

Running command `(New-Object System.Drawing.Text.InstalledFontCollection).Families` in powershell gives the following results:

```
...
更纱黑体 CL
更纱黑体 J
更纱黑体 SC
更纱黑体 TC
更纱黑体 UI CL
更纱黑体 UI J
更纱黑体 UI SC
更纱黑体 UI TC
...
等距更纱黑体 CL
等距更纱黑体 J
等距更纱黑体 SC
等距更纱黑体 TC
...
```

**Comment by be5invis** [comment]
It should be “Sarasa Mono SC” or “等距更纱黑体 SC”.

发自我的 iPhone

在 2017年11月29日，05:02，gnaggnoyil <notifications@github.com<mailto:notifications@github.com>> 写道：


What is the font name of Sarasa Mono that can be used as an option of editor.fontFamily in VSCode's user settings under Windows10? Like the following:

{
  // This setting works correctly with Wenquanyi Microhei font series.
  "editor.fontFamily": "WenQuanYi Micro Hei Mono"
}


I've tried Sarasa Mono, Sarasa Mono SC and 更纱黑体 but none of them works.

Running command (New-Object System.Drawing.Text.InstalledFontCollection).Families in powershell gives the following results:

...
更纱黑体 CL
更纱黑体 J
更纱黑体 SC
更纱黑体 TC
更纱黑体 UI CL
更纱黑体 UI J
更纱黑体 UI SC
更纱黑体 UI TC
...
等距更纱黑体 CL
等距更纱黑体 J
等距更纱黑体 SC
等距更纱黑体 TC
...

**Comment by be5invis** [comment]
This is my config and works perfectly on my PC (Windows 10 RS3):

```
{
	"editor.fontFamily": "Sarasa Mono SC"
}
```

**Comment by gnaggnoyil** [comment]
Thanks! Confirmed `Sarasa Mono SC` worked for me. Thought I was having some typo.

**Comment by Blealtan** [comment]
`等距更纱黑体 SC` works for me.

**Comment by quanbrew** [comment]
Maybe this should be written to README
