### ISSUE TITLE
Sarasa Mono 的空格非等宽

### ISSUE THREAD

**Issue by wangqr** [be5invis/Sarasa-Gothic#81]
在Notepad++中，Sarasa Mono字体的空格似乎等于1/2中文字符，但短于英文字符

![图片](https://user-images.githubusercontent.com/8182182/54495328-4842d580-48b9-11e9-944e-76e3103db5e7.png)

**Comment by be5invis** [comment]
Is your text size an odd number? If so, there will be rounding error, and you can try to increase/decrease text size by one, and see whether it is well aligned.

________________________________
发件人: wangqr <notifications@github.com>
发送时间: Monday, March 18, 2019 1:34:14 AM
收件人: be5invis/Sarasa-Gothic
抄送: Subscribed
主题: [be5invis/Sarasa-Gothic] Sarasa Mono 的空格非等宽 (#81)


在Notepad++中，Sarasa Mono字体的空格似乎等于1/2中文字符，但短于英文字符

[图片]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8182182%2F54495328-4842d580-48b9-11e9-944e-76e3103db5e7.png&data=02%7C01%7C%7Cc60461c0246049543be708d6aafec700%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636884408562476384&sdata=bDSkf3qvbZ6HnNJg%2Fq%2FPE32zbBpEQF%2B5jtCQGXk187I%3D&reserved=0>

―

**Comment by wangqr** [comment]
Changing the font size does fix the issue.
