### ISSUE TITLE
Wsl 终端中使用该字体无法正常显示powerline特殊字符

### ISSUE THREAD

**Issue by Whale-fall** [be5invis/Sarasa-Gothic#86]
![ZCX(VO~Q2AHQJMA9DYJQCMV](https://user-images.githubusercontent.com/22662209/55663530-bb54c180-5851-11e9-9bee-e388c1f5c7c2.png)

使用的是zsh的spaceship主题，但是在Hyper中能正常显示，是字体的问题还是别的什么配置的问题么
![K{@R5F_J489`0H2FXIU}FW4](https://user-images.githubusercontent.com/22662209/55663512-7466cc00-5851-11e9-9b79-1bd40046f795.png)

**Comment by CyanoHao** [comment]
Sarasa 有这个字 [🅒](https://unicode-table.com/en/1F152/)，但似乎 Windows Console 不支持 BMP 以外的字。
![image](https://user-images.githubusercontent.com/14287996/55664671-58205a80-5864-11e9-8490-37b0a6603520.png)

**Comment by Whale-fall** [comment]
哦哦，那大概就是win10控制台的问题了，谢谢你昂
