### ISSUE TITLE
"!=" shown as "≠" in Virtual Studio 2019

### ISSUE THREAD

**Issue by JAustinal** [be5invis/Sarasa-Gothic#88]
With the fonts Sarasa-mono-sc and Sarasa-monoT-sc, "!=" are shown as "≠" in Virtual Studio 2019. I perfer "!=" to "≠".
![image](https://user-images.githubusercontent.com/30486766/55705316-1bde2d00-5a11-11e9-870f-6dca08ce3d3c.png)

**Comment by be5invis** [comment]
Use the “Sarasa Term” variant, which does not contain ligatures.
Closed.
