### ISSUE TITLE
字体使用中遇到的一些问题

### ISSUE THREAD

**Issue by ShynHan** [be5invis/Sarasa-Gothic#9]
我用过两款字体 Sarasa-Gothic 和 Iosevka。
在使用的过程中遇到了一些小问题。

### Iosevka
1. winxp 下有部分字体无法安装成功（具体是哪几个我也忘记了，电脑不在手边，而且我现在改用 Sarasa-Gothic 了，在 winxp 系统下可以全部安装）。
2. 字号较大的时候，字体会显示不全（一级标题、二级标题那种大的字号，在 win10 与 winxp 系统中都会这样）

### Sarasa-Gothic
winxp 下，部分软件内使用 Sarasa-Gothic 会乱码。比如 IDEA12 中把编辑器位置的字体设置成 Sarasa-Gothic 就会乱码，使用其他字体就不会有问题（使用 Iosevka 也没有问题，所以我现在这两种字体混合使用）

以上问题大部分是 winxp 下发生的，在 win10 中没发现什么问题。

还有一个比较个人的问题。
我在使用 mushclient 客户端（类似一个加强版的 cmd 终端）玩一款 mud 游戏（纯文字的游戏）
里面有一些 文字与制表符或特殊符号等组成的图形，涉及到对齐问题，所以字体很重要。
比如使用楷体可以达到下面的效果：
![01](https://user-images.githubusercontent.com/12025422/34135759-8de37602-e49d-11e7-8150-fd9ceac41f9f.jpg)
可以达到同样效果的目前我测试出来的有 宋体、新宋、仿宋、幼圆，还有一个就是楷体。

我使用 Sarasa-Gothic 的效果是这样的：
![02](https://user-images.githubusercontent.com/12025422/34135976-a6ae85a4-e49e-11e7-83db-d048288633df.jpg)
（等距更纱黑体 SC、TC、CL、J 和 更纱黑体 CL、TC.. 更纱黑体 UI CL... 等等所有都试过，结果都一样）

只有 Iosevka 的 CC 系列字体（Inziu IosevkaCC SC、Inziu IosevkaCC TC 等等）可以达到最好的效果如下：
![03](https://user-images.githubusercontent.com/12025422/34136162-90ac94fc-e49f-11e7-8819-6ceb2e6bbcac.jpg)
但是依然有一点小问题，就是图中用圈出来的地方，应该是「Ψ」这个符号占了半个汉字字符宽度引起的，这里的「★」符号占了一个汉字字符宽度，那么能否让「Ψ」这个符号同样占一个汉字字符的宽度呢？

**Comment by be5invis** [comment]
Sarasa is NOT designed to be compatible with legacy CJK fonts. They are not designed for Windows XP either, since it is a product released 17 years ago.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
