### ISSUE TITLE
Clarification about this font

### ISSUE THREAD

**Issue by Trollwut** [be5invis/Sarasa-Gothic#90]
Hi folks!

I'm a big fan of Iosevka and thinking about learning Japanese.

Is this font simply Iosevka plus added Japanese characters or do I miss something Iosevka is offering me?

Also can I somehow see which version of Iosevka this font is using?

**Comment by be5invis** [comment]
Iosevka does not have any CJK part.
This font is a composite of Iosevka and Noto Sans CJK, so you can access the ideographs.
Closed.
