### ISSUE TITLE
小白菜鸟强迫症请教

### ISSUE THREAD

**Issue by tlerbao** [be5invis/Sarasa-Gothic#91]
![1](https://user-images.githubusercontent.com/20442232/55922989-22012300-5c36-11e9-9b1b-3e4311d36f18.png)

如图 安装字体后 会产生 中文的 更纱黑体 xx 一些列 和 Sarasa Term CL 几个

我在编辑器 例如 vscode 中 指定 fontFamily 的时候是写 更纱黑体 CL 好呢 还是写 Sarasa Term CL 好呢；都尝试了似乎看不出去区别。

由于字体知识的完全空白，问题可能有点傻逼，敬请谅解。

**Comment by showerying** [comment]
看 Readme
编辑器设置 Sarasa Term SC 就好了
