### ISSUE TITLE
 otfcc, AFDKO and ttfautohint 这三个东西要怎么下载

### ISSUE THREAD

**Issue by aika7469** [be5invis/Sarasa-Gothic#92]

**Comment by showerying** [comment]
网站左上角有搜索栏。

**Comment by aika7469** [comment]
External dependency <ttx> not found.
External dependency <otc2otf> not found.
External dependency <otf2otc> not found.
External dependency <otfccdump> not found.
External dependency <otfccbuild> not found.
External dependency <ttfautohint> not found.


执行npm install的时候遇到这个错误

**Comment by iamzeki** [comment]
```
External dependency <ttx> not found.
External dependency <otc2otf> not found.
External dependency <otf2otc> not found.
External dependency <otfccdump> not found.
External dependency <otfccbuild> not found.
External dependency <ttfautohint> not found.
```

**Comment by aika7469** [comment]
> ```
> External dependency <ttx> not found.
> External dependency <otc2otf> not found.
> External dependency <otf2otc> not found.
> External dependency <otfccdump> not found.
> External dependency <otfccbuild> not found.
> External dependency <ttfautohint> not found.
> ```
