### ISSUE TITLE
idea下面显示不正常

### ISSUE THREAD

**Issue by Matrix-Zhang** [be5invis/Sarasa-Gothic#93]
![图片](https://user-images.githubusercontent.com/1751829/56032067-bca35400-5d53-11e9-91fc-16ef2f73d8d2.png)

**Comment by Matrix-Zhang** [comment]
系统了，结果更糟了。。。

**Comment by ghsgz** [comment]
安装的时候是**为所有用户安装**嘛？，readme有提这个。

**Comment by Matrix-Zhang** [comment]
有，我又重装了系统好了。。。
