### ISSUE TITLE
Registry value name too long

### ISSUE THREAD

**Issue by hillin** [be5invis/Sarasa-Gothic#94]
As the Sarasa fonts are installed on a Windows system, some of its variants generate extremely long entries under registry key `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`. For example:
> Sarasa Gothic CL Medium & Sarasa Gothic SC Medium & Sarasa Gothic TC Medium & Sarasa Gothic HC Medium & Sarasa Gothic J Medium & Sarasa UI CL Medium & Sarasa UI SC Medium & Sarasa UI TC Medium & Sarasa UI HC Medium & Sarasa UI J Medium & Sarasa Mono CL Medium

This 259-character long entry BREAKS any program which is targeted to .NET Framework 3.5 or lower and tries to enumerate system installed fonts. Here is a test code:

    using System;
    using Microsoft.Win32;

    namespace FontEnumerationTest
    {
        internal class Program
        {
            private const string InstalledWindowsFontsRegistryKey = @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts";

            private static void Main(string[] args)
            {
                using (var fontsKey = Registry.LocalMachine.OpenSubKey(InstalledWindowsFontsRegistryKey))
                {
                    foreach (var fontValue in fontsKey.GetValueNames())
                    {
                        var fileName = fontsKey.GetValue(fontValue) as string;

                        Console.WriteLine(fileName);
                    }
                }

                Console.ReadKey();
            }
        }
    }

This code throws an IOException under .NET Framework 3.5. I believe this is an internal bug/limitation (of maximally 256-characters in a value name) in .NET Framework, which seems has been fixed in .NET Framework 4.0. But this behavior widely exists in many .NET Framework 3.5 apps (any GUI program would naturally enumerate the installed fonts). So I guess it would be great if this can be fixed on your side.

Much appreciated!

**Comment by be5invis** [comment]
Per [Registry Element Size Limits](https://docs.microsoft.com/en-us/windows/desktop/sysinfo/registry-element-size-limits), registry value names can go up to `16384` characters. Sarasa did **nothing** wrong. It's a problem os `.NET`.
If you want to solve this, install the TTF version instead (and that's why I build the TTF version).
Closed as by-design.

**Comment by hillin** [comment]
Thanks, I'll try the TTF version.
