### ISSUE TITLE
Does not work in powershell

### ISSUE THREAD

**Issue by gaoshijun1993** [be5invis/Sarasa-Gothic#95]
I downloaded the fonts and get they installed, the fonts could be selected in powershell font select options, however, when I click the confirm button, the default font will be switched to Song again. I've read the MD, and got no clue. So what's the correct way to use it......

**Comment by be5invis** [comment]
The language should match your codepage, i.e., `SC` for `936`.

**Comment by gaoshijun1993** [comment]
Thanks a lot☺
