### ISSUE TITLE
依照字型或語言分開壓縮字型檔案

### ISSUE THREAD

**Issue by jmlntw** [be5invis/Sarasa-Gothic#99]
加入各種字種之後釋出的 7z 壓縮檔增加到 200 MB 以上。希望能像 Source Han Sans 和 Noto Sans CJK 一樣依照字型或語言提供分別的壓縮檔（例如 Gothic 和 Mono 分成兩個 7z 檔案、或 JP、HC、TC、SC 個別分開），節省下載時間。

**Comment by be5invis** [comment]
I tried this before, but it doesn't reduce much. Sarasa shares the most glyph set among all variants, so one language + style's size is equivalent to the entire family.

**Comment by jmlntw** [comment]
Understood. Thanks for replying.
